// Konsilier AI Terms of Use — English translation of the Russian source in terms.ts.
import type { LegalDoc } from "./terms";

const en: LegalDoc = {
  title: "Terms of Use",
  edition: "Version of 28 September 2026",
  summaryTitle: "Key points",
  summary: [
    "Konsilier AI is an information technology (IT) service. We are not an advocate or a legal consultant, and we do not provide legal assistance.",
    "AI answers are for general information only, and the documents we prepare are drafts. Review them carefully: AI can make mistakes. You make the decisions and file documents yourself.",
    "When legal assistance is needed, it is provided by advocates and legal consultants under a separate agreement made directly with you.",
    "Names, IINs and phone numbers are replaced with tags before any text is passed to AI. The Service's servers are located in Kazakhstan.",
    "If there is a threat to life or health, call 112.",
  ],
  sections: [
    {
      h: "1. Definitions",
      p: [
        "“Service”, “Platform” means the Konsilier AI software: the konsilier.com website, the web application and the Telegram bot.",
        "“Operator” means the legal entity that operates the Service: Konsilier AI LLP, BIN 260940036818, address: 222 Akseleu Seidimbek St., Kuramys microdistrict, Nauryzbay district, Almaty 050000, Republic of Kazakhstan.",
        "“User”, “you” means any individual or legal entity that uses the Service.",
        "“Lawyer” means an advocate or a legal consultant who is a member of a chamber of legal consultants, or a human rights organization, working with Users through the Platform.",
        "“AI” means the artificial intelligence systems the Service uses to answer questions and prepare draft documents.",
        "“Case” means your matter in the Service: the description, answers, files, draft documents and history of steps.",
      ],
    },
    {
      h: "2. What the Service does",
      p: [
        "The Service provides software tools: an AI chat with links to the official texts of regulatory legal acts (Adilet legal information system), a tool that builds draft documents from your answers, suggestions on possible recipients and filing methods, deadline reminders, a directory of lawyers, signing of documents with EDS, and forwarding of your requests to lawyers.",
        "The Service is provided on an “as is” basis. Its features may change; we announce material changes on the website.",
      ],
    },
    {
      h: "3. The Service is not legal assistance",
      p: [
        "3.1. The Operator is not an advocate, a legal consultant or a member of a chamber of legal consultants, and does not provide legal assistance within the meaning of the Law of the Republic of Kazakhstan “On Advocacy and Legal Assistance”.",
        "3.2. The Service does not represent your interests in court or before state bodies and organizations. You file documents yourself and in your own name. A document is sent to a recipient by e-mail only on your express instruction, as a technical communication channel.",
        "3.3. AI answers are for information and reference only and may be incomplete, inaccurate or out of date. Check them against the official text of the provision via the link.",
        "3.4. Scenarios and documents that have not yet been reviewed by a lawyer may contain legal provisions, deadlines and recipients that need to be checked.",
        "3.5. In complex and high-risk situations, such as criminal prosecution, disputes concerning children, large sums or missed deadlines, contact an advocate or a legal consultant. The Service will show you how to do this.",
        "3.6. The Operator does not guarantee the outcome of a case, a recipient's response, or a decision of a court or state body.",
      ],
    },
    {
      h: "4. Lawyers on the Platform",
      p: [
        "4.1. Lawyers work independently. An agreement for legal assistance is made directly between you and the Lawyer; the Operator is not a party to that agreement and is not responsible for the quality of the legal assistance.",
        "4.2. The Operator verifies a Lawyer's status against the documents provided and public registries. Profiles marked “demo” are examples, not real lawyers.",
        "4.3. Your data is passed to a Lawyer only with your consent: when you send a request to a lawyer or sign a consent and an agreement with them.",
      ],
    },
    {
      h: "5. Use of artificial intelligence",
      p: [
        "5.1. The Service uses AI systems. Output generated by AI is labelled in accordance with the Law of the Republic of Kazakhstan “On Artificial Intelligence”.",
        "5.2. AI models are provided by third-party providers; their servers may be located outside Kazakhstan. Before text is passed to a provider, names, IINs, document numbers, phone numbers and addresses are replaced with tags.",
        "5.3. Some providers may use requests to improve their models. Do not share unnecessary personal data in the chat.",
        "5.4. AI does not make decisions for you. The choice of actions and responsibility for the documents filed remain with you.",
      ],
    },
    {
      h: "6. Account",
      p: [
        "6.1. You can start a case without registering: your browser stores an anonymous access key. To see your cases from any device, sign in with your e-mail, phone number, EDS or through eGov Mobile.",
        "6.2. You are responsible for the accuracy of the information you provide and for keeping access to your account and EDS secure.",
      ],
    },
    {
      h: "7. Rules of use",
      p: [
        "7.1. It is prohibited to: provide knowingly false information; use the Service for knowingly false denunciation, defamation, fraud, pressure or threats; upload other persons' personal data without a lawful basis; interfere with the operation of the Service.",
        "7.2. If these rules are breached, the Operator may suspend access to the Service and, in cases provided for by law, pass information to the competent authorities.",
      ],
    },
    {
      h: "8. Prices and payment",
      p: [
        "8.1. The AI chat is free of charge; a daily message limit applies.",
        "8.2. Document preparation is paid; the price is shown before payment. Payment is made by transfer using the details on the payment page; the document becomes available once the payment is confirmed.",
        "8.3. The fee for legal assistance is set by the Lawyer in the agreement with you. Human rights organizations help free of charge.",
        "8.4. Refunds are made in accordance with the Law of the Republic of Kazakhstan “On Consumer Rights Protection”.",
      ],
    },
    {
      h: "9. Personal data",
      p: [
        "9.1. By using the Service, you consent to the collection and processing of your personal data in accordance with the Law of the Republic of Kazakhstan “On Personal Data and Their Protection” for the purposes of handling your case, preparing documents, sending deadline notifications and communicating with you.",
        "9.2. The following is processed: the information you provide in the description and answers, uploaded files, and contact details for sign-in and notifications. An IIN used for sign-in is stored only as an encrypted fingerprint; only the last digits are shown on screen.",
        "9.3. The Service's servers and file storage are located in the Republic of Kazakhstan (Yandex Cloud, kz1 region).",
        "9.4. Data is passed to third parties only for the operation of the Service: to AI providers — text with tags in place of personal data (Section 5); to the e-mail service — the address and text of a message in order to send notifications; to a Lawyer — with your consent (Section 4); to state bodies — in cases provided for by law.",
        "9.5. Data is stored for as long as it is needed for your case and account, and for the periods established by law. You may request access to, correction or deletion of your data, and withdraw your consent, by writing to info@konsilier.com.",
      ],
    },
    {
      h: "10. Liability",
      p: [
        "10.1. The Operator is liable for the operation of the Service to the extent established by the legislation of the Republic of Kazakhstan.",
        "10.2. The Operator is not liable for decisions you make on the basis of AI answers and documents prepared by the Service, for the actions and decisions of recipients, courts and state bodies, or for legal assistance provided by Lawyers.",
        "10.3. Nothing in these Terms limits your rights as a consumer under the legislation of the Republic of Kazakhstan.",
      ],
    },
    {
      h: "11. Changes to these Terms",
      p: [
        "A new version is published on this page with its date. We give advance notice of material changes on the website or by e-mail. If you continue to use the Service after the new version takes effect, you accept it.",
      ],
    },
    {
      h: "12. Governing law and disputes",
      p: [
        "These Terms are governed by the law of the Republic of Kazakhstan. Disputes are resolved through negotiation and, failing agreement, in court in the manner established by the legislation of the Republic of Kazakhstan; a consumer may bring a claim in court, including at their place of residence.",
      ],
    },
    {
      h: "13. Contacts",
      p: [
        "Konsilier AI LLP, BIN 260940036818, 222 Akseleu Seidimbek St., Kuramys microdistrict, Nauryzbay district, Almaty 050000, Republic of Kazakhstan. E-mail: info@konsilier.com.",
      ],
    },
  ],
};

export default en;
