import type { Dict } from "./types";

const en: Dict = {
  nav: {
    account: "Sign in",
    start: "Start", cases: "My cases", admin: "Admin", lawyers: "Lawyers", forLawyers: "For lawyers",
    howItWorks: "How it works", coverage: "Coverage", menu: "Menu", language: "Language",
    skip: "Skip to content", main: "Main menu",
  },
  footer: {
    lawyerCabinet: "Lawyer's cabinet",
    tagline: "Describe your problem — Konsilier prepares the document under your country's law, tells you where to file it, tracks the deadlines and, when needed, brings in a verified lawyer.",
    product: "Product", lawyers: "For lawyers", designSystem: "Design system",
  },
  level: {
    pending: { label: "Finding your path", desc: "We are working out what happened. As soon as it is clear, we will show the right path and the first step." },
    verified: { label: "Lawyer-verified", desc: "Ready scenario: laws, deadlines and recipients signed off by a lawyer. Full autopilot." },
    scenario_draft: { label: "Common situation", desc: "There is a ready scenario for this situation: questions, document and next steps. A lawyer checks the references to laws and deadlines separately." },
    universal: { label: "Tailored document", desc: "We draft a document for your situation: the text from your story and evidence, the recipient from the registry of authorities. You file a claim, complaint or application yourself with step-by-step instructions; a lawyer reviews court filings first." },
    lawyer: { label: "Lawyer needed", desc: "A complex or risky case: we build a case file and pass it to a verified lawyer." },
    soon: { label: "Coming soon", desc: "Not accepting cases yet. Leave your contact and we will let you know at launch." },
  },
  path: {
    document: { title: "Document", text: "A complaint, claim, application or lawsuit based on your words and evidence." },
    forum: { title: "Recipient", text: "An authority or organization taken only from a verified registry. We never make them up." },
    deadline: { title: "Deadlines", text: "We track the response deadline and remind you. If the deadline is not in our data, a lawyer will confirm it." },
    escalation: { title: "Escalation", text: "No reply or a refusal? We prepare the next step: a higher authority or court." },
    lawyer: { title: "Lawyer", text: "When needed, we connect a verified lawyer rated by results." },
  },
  emergency: {
    title: "Safety first",
    continue: "I am safe, continue",
    sample: "If there is a threat to life or health right now, call emergency services.",
  },
  helper: {
    photo: "Take a photo",
    attach: "Attach a file",
    more: "More examples",
    examplesTitle: "Examples — tap to use",
    suggestTitle: "Is it like this?",
    servicesTitle: "Where to file — we tell you what goes where",
    eotinish: "Appeals and complaints to state bodies",
    sud: "Lawsuits and motions to court",
    egov: "Certificates and public services",
    step1: "Describe the problem",
    step2: "Answer a few questions and attach documents",
    step3: "Download the document and file it step by step",
    planTitle: "Proposed solution",
    planDoc: "We draft",
    planTo: "Addressed to",
    planVia: "How to file",
    planAttach: "Prepare and attach",
    planSelf: "You file it yourself — we give step-by-step instructions",
    planLawyer: "A lawyer checks the document before filing",
    planUpload: "Upload a document",
    examples: { 1: "Bought a phone on Kaspi, it broke a week later, the seller won't refund", 2: "My employer hasn't paid my salary for three months", 3: "I was dismissed without notice and not paid my final settlement", 4: "A microloan was taken out in my name without my knowledge", 5: "Debt collectors call and threaten me over someone else's debt", 6: "A marketplace order never arrived and the money isn't refunded", 7: "My landlord won't return the deposit", 8: "I was fined for a violation I didn't commit" },
    exampleCount: "8",
    doc_download: "Download",
    doc_print: "Print",
    doc_save: "Save",
    doc_send: "Send",
    doc_sign: "Sign with EDS",
    doc_signUnavailable: "Signing with EDS on the site is unavailable right now. You can sign on the portal when filing (eOtinish, Court cabinet) or sign by hand.",
    doc_signed: "Signed with EDS",
    doc_fmtPdf: "PDF — to print and file",
    doc_fmtWord: "Word — to edit",
    doc_toWhatsapp: "WhatsApp",
    doc_toTelegram: "Telegram",
    doc_toMail: "E-mail",
    doc_toOther: "Another app",
    doc_fileReady: "The file is downloaded — attach it in the window that opened.",
    doc_savedTo: "Saved",
  },
  cta: {
    title: "Ready to start?",
    lead: "Describe the situation in your own words — we will show the path and prepare the first document.",
    start: "Describe your situation",
    lawyer: "Find a lawyer",
    more: "Learn more",
    next: "Next",
    startCase: "Start a case",
    complain: "File a complaint",
    join: "Are you a lawyer? Join us",
    caseLawyerTitle: "Need a lawyer's help?",
    caseLawyerText: "A lawyer can review your documents or take over the whole case.",
    lawyersLead: "Describe the situation — we prepare the documents and bring in a lawyer when you need one.",
  },
  home: {
    eyebrow: "Your AI assistant for legal matters",
    title: "Any legal problem, from complaint to resolution",
    sub: "Describe what happened. We will prepare the document, tell you where to file it and keep track of deadlines. If you need a lawyer, we will connect a verified one.",
    promise1: "A document under the laws of your country",
    promise2: "Recipient from a verified registry",
    promise3: "Deadline reminders and the next step",
    promise4: "Verified lawyers when you really need one",
    describe: "Describe what happened",
    cta: "Continue",
    privacy: "Names and document numbers are replaced with labels before AI processing. Documents are filed in your name.",
    situationsEyebrow: "Life situations",
    situationsTitle: "What we help with",
    situationsLead: "You do not need to know which area of law it is. Pick a similar situation or just describe yours.",
    pathEyebrow: "Path map",
    pathTitle: "How your case moves forward",
    pathLead: "At each step you can see who checked it and when a lawyer steps in.",
    levelsEyebrow: "Honest about coverage",
    levelsTitle: "Three levels: you always know where your case stands",
    levelsLead: "We guide you all the way: document, filing, deadline tracking and a lawyer when you need one.",
    howLink: "Learn more about how it works",
    coverageTitle: "Kazakhstan is live. CIS and the Middle East are coming soon",
    coverageLead: "Uzbekistan, Kyrgyzstan, Azerbaijan, Turkey, the UAE, Saudi Arabia and other countries are in the launch plan.",
    coverageCta: "Coverage by country",
  },
  situations: {
    cheated: { label: "I was cheated on a purchase", hint: "Goods, services, marketplaces, refunds.", placeholder: "What you bought, from whom, when, for how much and what went wrong" },
    fired: { label: "Fired or not paid wages", hint: "Dismissal, unpaid wages, discrimination.", placeholder: "Where you work, what happened and when, how much you are owed" },
    family: { label: "Divorce and children", hint: "Divorce, child support, who the child lives with, dividing property.", placeholder: "Briefly: what is happening and what you want to achieve" },
    fine: { label: "A fine", hint: "Appealing a fine or a ruling.", placeholder: "What the fine is for, who issued it, when and why you disagree" },
    crime: { label: "A crime against me", hint: "Theft, fraud, assault. Facts only: what, where, when.", placeholder: "What happened, where and when, who saw it, what the damage is" },
    stateBody: { label: "Dispute with a government body", hint: "Refusal, inaction, no reply to your request.", placeholder: "Which body, what you asked for and what they replied" },
    bank: { label: "Bank, loans, debt collectors", hint: "A loan in your name, a dispute with a bank, pressure from collectors.", placeholder: "Which bank or microlender, what happened, what amounts" },
    business: { label: "Business dispute", hint: "A counterparty's debt, breach of contract.", placeholder: "Who the contract is with, what was breached, what amount" },
    inheritance: { label: "Inheritance", hint: "Accepting an inheritance, disputes between heirs.", placeholder: "Who died and when, who the heirs are, what the issue is" },
    housing: { label: "Housing and neighbors", hint: "Rent, utilities, neighbors.", placeholder: "What kind of housing, who the dispute is with, what happened" },
  },
  board: {
    intake: "Request", qualified: "Details collected", action_ready: "Document ready", submitted: "Filed, awaiting reply",
    escalated: "Escalation", handed_to_lawyer: "With a lawyer", resolved: "Resolved",
    empty: "Empty", stepOf: "Step {n} of {total}",
    attention: { hold: "Under review", ack: "Confirmation needed", expired: "Response deadline passed", approval: "Awaiting lawyer review", chooseForum: "Choose a recipient" },
  },
  ack: {
    false_report: { title: "Liability for knowingly false reports", button: "I understand and confirm", text: "Knowingly filing a false report is a criminal offense. Describe only facts you know." },
    special_category: { title: "Consent to process sensitive data", button: "I consent", text: "Your case may include data about health, religion or criminal record. We keep the minimum and use it only for your document." },
  },
  forum: {
    chooseTitle: "Where to file",
    chooseLead: "Choose a recipient. The list comes only from this country's registry of authorities; the differences are shown below.",
    type: { court: "Court", prosecutor: "Prosecutor's office", police: "Police", regulator: "Regulator", ministry: "Ministry",
      ombudsman: "Ombudsman", local_authority: "Local authority", arbitration: "Arbitration", mediation: "Mediation",
      private_org: "Organization" },
    effect: { binding: "Decision is binding", advisory: "Advisory decision", none: "No legal force" },
    verified: "Lawyer-verified", unverified: "A lawyer will confirm the details", deadlineByLawyer: "A lawyer will confirm the deadline",
    channels: "How to file", channel: { portal: "online portal", email: "email", post: "mail", in_person: "in person", whatsapp: "WhatsApp", telegram: "Telegram" },
    choose: "Choose",
  },
  common: { loading: "Loading…", sending: "Sending…" },
  roadmap: {
    title: "Case roadmap",
    best: "Best case",
    worst: "If all steps are needed",
    openEnded: "then work with a lawyer, timing as agreed",
    done: "Done",
    current: "Now",
    upcoming: "Next",
    skipped: "Not needed",
    ifNeeded: "if needed",
    due: "due",
    estimated: "estimated",
    finished: "completed",
    todoNorm: "a lawyer will confirm the deadline",
  },
  trust: {
    title: "How we protect you from fraud and empty promises",
    verifiedTitle: "Only verified lawyers",
    verified: "Advocate or legal consultant status is checked against registries, and identity via digital signature (EDS). No verification, no access to clients.",
    escrowTitle: "Pay per stage, money held in reserve",
    escrow: "You do not pay everything upfront. The amount is held by a payment partner and released to the lawyer only when a stage is done: claim filed, reply received, lawsuit filed.",
    ratingTitle: "Rating based on proven results",
    rating: "The rating is based on real cases on the platform: how many were won, adjusted for difficulty, how much money was recovered, and whether deadlines were met. Reviews only after a deal.",
    roadmapTitle: "You see where your case is",
    roadmap: "A roadmap: what is done, what is happening now, what comes next and when to expect a decision, in the best and worst case.",
    soon: "Safe deals with lawyers are in development",
    more: "Learn more",
    less: "Show less",
    now: "Now",
    verifiedMore: "Advocate: membership in a bar association and a valid license.\nLegal consultant: membership in the chamber of legal consultants.\nIdentity is confirmed with a digital signature (EDS), so no one can work under someone else's name.\nIf a license is revoked or a member is expelled from the chamber, the profile is hidden.",
    verifiedNow: "For now, our team checks lawyer applications manually against documents. Automatic registry checks and EDS sign-in are in development.",
    verifiedLink: "How to become a platform lawyer",
    escrowMore: "The price and stages are fixed in the contract before work starts.\nMoney for a stage is held by the payment partner, not the lawyer.\nThe lawyer gets paid when the stage is confirmed: document filed, reply received.\nIf a stage is not completed, the money for it is returned to you.\nDisputes are reviewed by the platform based on the documents in the case.",
    escrowNow: "In development: we are choosing a payment partner in Kazakhstan. Until launch, do not prepay lawyers for the whole case.",
    ratingMore: "The outcome is recorded when the case is closed on the platform, not based on the lawyer's word.\nResults are compared with the average for the same category, so easy cases do not inflate the rating.\nWeights: success 45%, meeting deadlines 20%, money recovered 20%, reviews 15%.\nNew lawyers' scores are pulled toward the platform average until they have 30+ cases.\nReviews can only be left after a real deal.",
    ratingNow: "For now we show an example with demo profiles: the real rating will appear once lawyers close their first cases on the platform.",
    ratingLink: "See a sample rating",
    roadmapMore: "Every step of the case: claim, waiting for a reply, complaint to a regulator, lawsuit.\nFor each step: the legal deadline and the date it expires.\nTwo forecasts: the best case (resolved after the claim) and if all steps are needed.\nWe remind you of deadlines so you do not miss any.",
    roadmapNow: "Already live: the roadmap opens in every case right after you describe the situation.",
    roadmapLink: "Start a case",
    cta: "See a sample rating",
    joinLawyer: "Are you a lawyer? Join us",
  },
  lawyers: {
    title: "Lawyers and advocates",
    subtitle: "Rated by proven results on the platform, not by advertising.",
    score: "Rating",
    confidence: { low: "few cases", medium: "medium sample", high: "large sample" },
    vsBaseline: "vs. platform average",
    cases: "verified cases",
    recovered: "money recovered",
    onTime: "stages on time",
    reviews: "post-deal reviews",
    from: "from",
    proBono: "free (pro bono)",
    response: "average response time",
    hours: "h",
    years: "years of practice",
    verifiedLicense: "License verified",
    verifiedId: "Identity verified",
    success: "success",
    platform: "average",
    methodTitle: "How the rating works",
    method1: "Only cases handled through the platform: the outcome is recorded when the case closes, not based on the lawyer's word.",
    method2: "Results are compared with the average for the same case category, so picking easy cases does not raise the rating.",
    method3: "Small samples are pulled toward the average: 3 wins out of 3 will not beat 180 out of 220.",
    method4: "Weights: success 45%, meeting stage deadlines 20%, share of money recovered 20%, post-deal reviews 15%.",
    choose: "Choose",
    chooseSoon: "Choosing a lawyer will open together with safe deals",
    pp: "pp",
    mln: "M",
  },
  landing: {
    promise: "Your case, from the first document to the result",
    sub: "Describe the situation in your own words. Konsilier.AI will prepare a claim or complaint under the laws of Kazakhstan, tell you where to file it and keep track of deadlines. If that is not enough, a professional platform lawyer will see the case through.",
    usp1: "Ready documents, without searching for a lawyer or internet templates",
    usp2: "Deadlines under control: we remind you and prepare the next step",
    usp3: "Platform lawyers: verified and rated by real results",
    startWeb: "Start on the website",
    startTelegram: "Open in Telegram",
    scenariosTitle: "What we can do already",
    howTitle: "How it works",
    how1: "Tell us what happened",
    how2: "Answer a few short questions and upload receipts or screenshots",
    how3: "Get the document and filing instructions",
    how4: "We track the response deadline and suggest the next step",
    countryTitle: "Your country",
    countryLive: "Available",
    countrySoon: "Coming soon",
    waitlistTitle: "We do not work in this country yet",
    waitlistText: "Leave your contact and we will let you know when we launch.",
    waitlistContact: "Email or Telegram",
    waitlistProblem: "What problem are you facing? (optional)",
    waitlistSend: "Notify me at launch",
    waitlistDone: "Thank you! We will let you know when we launch.",
    price: "Price",
    disclaimer: "Documents are filed in your name, and you control every step.",
  },
  start: {
    eyebrow: "New case",
    country: "Country: Kazakhstan.",
    otherCountry: "Another country",
    busy: "Analyzing your situation… This may take up to a minute.",
    title: "What happened?",
    placeholder: "For example: I bought a phone from an online store on 12.08.2026 for 150,000 tenge, it broke a week later and they won't refund me",
    submit: "Continue",
  },
  case: {
    back: "All cases",
    untitled: "New case",
    holdTitle: "Case under manual review",
    draftTitle: "Draft",
    lawyerTitle: "The case is being passed to a lawyer",
    lawyerCta: "Verified lawyers",
    lawyerText: "We saved your description and are passing the case to a verified platform lawyer.",
    uplTitle: "Who we are",
    thinking: "Preparing a reply… On a slow connection this may take up to a minute.",
    working: "Working on it… Please keep this page open.",
    send: "Reply",
    answerPlaceholder: "Your answer",
    more: "Add details",
    morePlaceholder: "What exactly you bought or signed up for, from whom, when, for how much, and what went wrong",
    skip: "Skip",
    doneUploading: "Done",
    upload: "Upload file",
    uploadHint: "Photo or PDF, up to 15 MB",
    found: "Found in the file",
    confirm: "All correct",
    nothingFound: "File saved. We could not read the data automatically.",
    facts: "Case details",
    prepare: "Prepare document",
    handoff: "Pass to a lawyer",
    awaitingApproval: "A lawyer is reviewing the document. We will let you know when it is ready.",
    rejected: "The lawyer sent the document back for changes.",
    download: "Download",
    instructions: "How to file",
    submitted: "I have sent it",
    sendEmail: "Send it by email for me",
    deadline: "Response deadline",
    gotResponse: "I got a reply",
    noResponse: "No reply",
    responsePlaceholder: "Paste the reply text",
    responseSend: "Analyze the reply",
    responseFile: "or upload the reply file",
    close: "Close case",
    closeWon: "Fully recovered",
    closePartial: "Partly",
    closeLost: "Not recovered",
    amountRecovered: "Amount recovered",
    outcome: "Outcome",
    days: "days",
    response: "Reply",
    notifications: "Notifications",
    datePlaceholder: "DD.MM.YYYY",
    classes: { full: "In full", partial: "Partly", refusal: "Refusal", none: "No reply" },
    deadlineStatus: { active: "running", met: "reply received", expired: "expired", cancelled: "cancelled" },
  },
  cases: {
    title: "My cases", empty: "No cases yet.", open: "Open", new: "New case",
    lead: "Each case is a card on the board, from request to resolution. Cases do not disappear; they move through the stages.",
  },
  coverage: {
    eyebrow: "Coverage",
    title: "Where and with what we already help",
    lead: "What already works by country and area of law: where there are ready scenarios, where we draft a document for your situation, and what is coming soon.",
    legend: "What the statuses mean",
    liveLead: "Status of each area of law in this country.",
    plannedTitle: "Coming soon: CIS and the Middle East",
    plannedLead: "We are preparing verified data for these countries with local lawyers. Not accepting cases yet.",
    waitlistTitle: "Notify me at launch",
    sourcesTitle: "Official sources of law",
    sourcesLead: "We only link to and cite official government databases. Links open in a new tab.",
    sourceKind: { legislation: "Legislation", case_law: "Case law", gazette: "Official gazette", registry: "Registry" },
  },
  how: {
    eyebrow: "How it works",
    title: "Konsilier — your AI assistant for legal matters",
    lead: "Describe your problem — Konsilier prepares the document under your country's law, tells you where to file it, tracks the deadlines and, when needed, brings in a verified lawyer.",
    pathTitle: "Path map",
    pathLead: "Document → recipient → deadline → escalation → lawyer.",
    levelsTitle: "Three coverage levels",
    levelsLead: "The level is set automatically and always shown in your case.",
    level: {
      verified: { title: "Verified scenario", when: "For common situations where a lawyer has signed off the laws, deadlines and recipients.", get: { 1: "A document from a verified template", 2: "Legal response deadlines and reminders", 3: "The next step from a known sequence" } },
      universal: { title: "Tailored document", when: "When there is no ready scenario, but the area of law is clear and a suitable authority is in the registry.", get: { 1: "A document drafted from your story and evidence", 2: "Step-by-step filing: where, how and what to attach; court filings after a lawyer's review", 3: "Laws and deadlines only from data; otherwise \"a lawyer will confirm\"" } },
      lawyer: { title: "Handover to a lawyer", when: "Criminal defense, children, large amounts, deadlines about to expire, unclear situations.", get: { 1: "A case file based on your description", 2: "A verified lawyer rated by results", 3: "Defense documents are written only by an advocate" } },
    },
    rolesTitle: "Who does what",
    ai: {
      title: "AI",
      does: { 1: "Understands your story and asks short questions", 2: "Writes the statement of facts and sets out the demands", 3: "Reads the recipient's reply and suggests the next step", 4: "Works only with anonymized data" },
      neverTitle: "AI never",
      never: { 1: "Makes up laws, articles or deadlines", 2: "Chooses the authority to file with", 3: "Determines religion or ethnicity", 4: "Writes defense documents in criminal cases" },
    },
    lawyer: {
      title: "Lawyer",
      does: { 1: "Signs off scenarios: laws, deadlines, recipients", 2: "Reviews lawsuits and court appeals before filing", 3: "Handles complex cases and represents you", 4: "Is responsible for the legal accuracy of the registry of authorities" },
    },
    promiseTitle: "What we promise and what we don't do",
    promiseLead: "No big promises: only what depends on us.",
    promise: { title: "We promise", 1: "A clear path for your case", 2: "A ready document and filing instructions", 3: "Deadline tracking and reminders", 4: "A verified lawyer when you need one" },
    dont: { title: "We don't", 1: "Represent you in court ourselves; platform lawyers do that", 2: "File in court without a lawyer's review", 3: "Write defense documents in criminal cases", 4: "Make up authorities, laws, deadlines or fees" },
    safetyTitle: "Safety",
    safety: {
      emergency: { title: "Emergencies", text: "If there is a threat to life, violence or a child in danger, we first show the country's emergency numbers." },
      falseReport: { title: "False reports", text: "In crime reports we warn about liability and ask you to describe facts, not opinions." },
      abuse: { title: "Abuse protection", text: "Mass complaints against one person, harassment, blackmail and defamation go to manual review." },
    },
  },
  ds: {
    title: "Design system", lead: "Konsilier tokens and components: trust, clarity and accessibility on phone and desktop, in five languages.",
    colors: "Colors", type: "Typography", buttons: "Buttons", badges: "Level badges", notices: "Notices",
    noticesLead: "Emergency numbers, false-report warnings, the service's legal status and \"Draft\" are components, not fine print.",
    uplSample: "Konsilier.AI is a document preparation service and a technology intermediary with lawyers.",
    draftSample: "This scenario has not yet been signed off by a lawyer. References to laws and deadlines need to be checked.",
    forms: "Input fields", progress: "Case stages", board: "Case board", icons: "Icons",
  },
  errors: {
    title: "Something went wrong",
    saved: "Your data is saved and the case is not lost. We received an error report. Reload the page to continue.",
    translate: "If your browser's automatic page translation is on, turn it off for this site.",
    reload: "Reload page",
    retry: "Try again",
  },
  admin: {
    lawyers: {
      lead: "Approve only applications made with ЭЦП, and only after checking the licence number against the public registry.",
      ecp: "ЭЦП",
      noEcp: "No ЭЦП",
      license: "Licence",
      nameDiffers: "The application gives another name: {name}",
      verify: "Approve",
      assign: "Pass to a lawyer",
      assignButton: "Pass",
      assigned: "Passed to {name}. Papers to sign were created.",
    },
    title: "Admin",
    tabs: { lawyers: "Lawyers", queue: "Review queue", board: "Board", holds: "Under review", forums: "Registry of authorities", demand: "Demand", errors: "Browser errors" },
    forum: "Recipient", hold: "On hold", release: "Release from review",
    forums: {
      registry: "Registry (from package)", registryLead: "The source of truth is YAML in the repository. Changes reach production only through a PR reviewed by a lawyer.",
      newDraft: "New entry (draft)", draftNote: "The draft is validated against the schema but does not affect production until it is exported and accepted in a PR.",
      save: "Save draft", saved: "Draft saved", drafts: "Drafts",
    },
    demand: { title: "Demand: situations without a ready scenario", lead: "Which situations come in without a ready scenario: candidates for the next verified scenarios.", country: "Country", dispute: "Dispute type", level: "Level", count: "Cases" },
    token: "Admin token",
    save: "Sign in",
    needsReview: "Only needs_review",
    pendingApproval: "Awaiting approval",
    all: "All",
    approve: "Approve",
    reject: "Send back",
    note: "Lawyer's comment",
    preview: "Document text",
    audit: "Log",
    closeCase: "Close case",
    waitlist: "Waitlist",
    tick: "Run reminders",
  },
  account: {
    eyebrow: "Account",
    title: "Sign in and verify your identity",
    lead: "Sign in to see your cases on any device. Verifying with a digital signature (ЭЦП) or eGov Mobile also confirms who you are.",
    verifiedTitle: "Verified",
    waysTitle: "Ways to sign in",
    soon: "Soon",
    done: "Done: you are signed in. Your cases are now linked to your account.",
    privacy: "We store an encrypted fingerprint of your IIN, not the IIN itself, and show only its last digits. Codes are valid for 10 minutes.",
    kind: {
      email: "E-mail",
      phone: "Phone",
      iin: "IIN",
    },
    email: {
      title: "By e-mail",
      hint: "We will send a six-digit code to your inbox.",
      label: "E-mail address",
      sent: "We sent a code to {target}. Check your spam folder too.",
    },
    phone: {
      title: "By phone number",
      hint: "We will send a code by SMS.",
      label: "Phone number",
      sent: "We sent an SMS code to {target}.",
    },
    ecp: {
      title: "Digital signature (NCALayer)",
      hint: "An ЭЦП key on your computer: a file or an ID card. Confirms your identity.",
      step1: "Install and start NCALayer:",
      step2: "Press the button and choose your authentication key (AUTH_RSA or AUTH_GOST).",
      step3: "Enter the key password in the NCALayer window.",
      button: "Sign in with ЭЦП",
      waiting: "Waiting for the signature in NCALayer…",
      not_running: "NCALayer is not running. Start it and try again.",
      cancelled: "Signing was cancelled.",
      failed: "NCALayer could not sign. Try again.",
    },
    egov: {
      title: "eGov Mobile",
      hint: "Confirm sign-in in the eGov Mobile or eGov Business app with a QR code.",
      button: "Show QR code",
      scan: "Open eGov Mobile → QR scanner and point the camera at the code.",
      onPhone: "On a phone? Open the app with a button:",
      waiting: "Waiting for confirmation in the app…",
      expired: "Time is up. Create a new code.",
      qrAlt: "QR code to sign in with eGov Mobile",
    },
    sendCode: "Get code",
    codeLabel: "Code from the message",
    confirm: "Confirm",
    changeTarget: "Change address",
    errors: {
      too_soon: "A code was just sent. You can request another in a minute.",
      rate_limited: "Too many attempts. Try again in an hour.",
      wrong_code: "Wrong code.",
      code_expired: "The code has expired. Request a new one.",
      too_many_attempts: "Too many wrong attempts. Request a new code.",
      invalid_email: "Check the e-mail address.",
      invalid_phone: "Check the phone number, e.g. +7 701 123 45 67.",
      method_unavailable: "This method is not available yet.",
      send_failed: "Could not send the code. Try later.",
      invalid_signature: "The signature did not pass verification.",
      certificate_invalid: "The certificate is invalid or revoked.",
      wrong_data: "The wrong data was signed. Try again.",
      challenge_expired: "Time to sign ran out. Try again.",
      verifier_unavailable: "Signature checking is temporarily unavailable. Try later.",
      no_iin: "The certificate has no IIN.",
    },
  },
  sign: {
    signedByLawyer: "Signed with ЭЦП by the lawyer: {name} ({id})",
    lead: "Sign the document with your ЭЦП — a signed document is harder to dispute. The signed file goes with the e-mail.",
    ncalayer: "Sign with ЭЦП (NCALayer)",
    egov: "Sign in eGov Mobile",
    signedBy: "Signed with ЭЦП: {name} ({id})",
    download: "Download the signed file (.cms)",
    verifyHint: "The signature can be checked in ezSigner or on sigex.kz.",
    errors: {
      use_sign_key: "Choose your signing key (RSA or GOST), not the sign-in key (AUTH).",
      signer_mismatch: "The applicant must sign: the IIN in the key differs from the IIN in the case.",
      document_changed: "The document changed. Start signing again.",
      wrong_data: "A different file was signed. Try again.",
      awaiting_approval: "The document is still being reviewed by a lawyer.",
    },
  },
  agreements: {
    yourLawyer: "Your lawyer",
    unreviewed: "These are platform templates not yet reviewed by the platform's lawyer. The lawyer on your case checks the terms and confirms them by signing.",
    leadCustomer: "Sign with your ЭЦП, then the lawyer signs.",
    leadLawyer: "The client has signed. Check the terms and sign with the ЭЦП you registered with.",
    waitCustomer: "Waiting for the client's signature.",
    waitLawyer: "Waiting for the lawyer's signature.",
    status: {
      awaiting_customer: "Awaiting the client's signature",
      awaiting_lawyer: "Awaiting the lawyer's signature",
      signed: "Signed by both parties",
    },
    kind: {
      advocate: "Advocate",
      legal_consultant: "Legal consultant",
      human_rights: "Human-rights defender",
      other: "Lawyer",
    },
  },
  lawyer: {
    eyebrow: "For lawyers",
    title: "Lawyer's cabinet",
    lead: "Cases the platform has passed to you, and the papers with the client signed with ЭЦП.",
    ecpNeeded: "Sign in with ЭЦП: this confirms who you are, and only this ЭЦП can sign papers with clients.",
    ecpSignIn: "Sign in with ЭЦП",
    ecpOk: "Identity confirmed with ЭЦП",
    cabinetLink: "Open the lawyer's cabinet",
    noApplication: "You have not applied to join yet.",
    apply: "Apply",
    noCases: "No cases have been passed to you yet.",
    aboutProgram: "About the partner programme",
    status: {
      new: "Your application is being checked against the registry. This usually takes 1–2 working days.",
      rejected: "Your application was rejected. Write to us if this is a mistake.",
    },
  },
  gov: {
    ecpOnly: "Needs ЭЦП",
    title: "Certificates from egov.kz",
    lead: "These certificates can strengthen your case. Get them yourself on egov.kz — with your ЭЦП or eGov Mobile — and upload them here: they are added to the evidence.",
    needsEcp: "egov.kz sign-in: ЭЦП or SMS code",
    open: "No sign-in",
    get: "Get on egov.kz",
    upload: "Upload certificate",
    uploaded: "Uploaded",
    disclaimer: "We do not sign in to egov.kz on your behalf and cannot see your data there — you get the certificate yourself.",
  },
};

export default en;
