import type { Dict } from "./types";

const en: Dict = {
  nav: {
    account: "Sign in",
    start: "Start", cases: "My cases", admin: "Admin", lawyers: "Lawyers", forLawyers: "For lawyers",
    howItWorks: "How it works", coverage: "Services", menu: "Menu", language: "Language",
    skip: "Skip to content", main: "Main menu",
    app: "App",
  },
  legal: {
    disclaimer: "Konsiliér AI is your AI assistant for legal questions. AI answers are for general information only, and documents are drafts: review them before filing.",
    terms: "Terms of Use",
    accept: "By sending a message you accept the",
    version: "version",
    languageNote: "The Terms are drawn up in Kazakh and Russian; this is an English translation.",
  },
  footer: {
    company: "Konsilier AI LLP · BIN 260940036818",
    said: "Konsiliér AI [kon-seel-YER] — your AI assistant for legal questions",
    contacts: "Contacts",
    lawyerCabinet: "Lawyer dashboard",
    tagline: "Tell us what happened. Konsiliér AI prepares your document under your country's law, shows you where to file it, keeps track of deadlines and, if you need one, helps you find a lawyer.",
    product: "Product", lawyers: "For lawyers", designSystem: "Design system", support: "Contact us",
  },
  level: {
    pending: { label: "Finding your path", desc: "We are working out what happened. As soon as it is clear, we will show the right path and the first step." },
    verified: { label: "Lawyer-verified", desc: "Ready-made scenario: laws, deadlines and recipients signed off by a lawyer. Full autopilot." },
    scenario_draft: { label: "Common situation", desc: "There is a ready-made scenario for this situation: questions, a document and the steps to take. A lawyer checks the references to laws and deadlines separately." },
    universal: { label: "Tailored document", desc: "We prepare a document for your situation: the text from your story and evidence, the recipient from the registry of authorities. You file the claim, complaint or application yourself, following step-by-step instructions; a lawsuit is reviewed by a lawyer before it is filed." },
    lawyer: { label: "Lawyer needed", desc: "A complex or risky case: we build a case file and help you find a lawyer." },
    soon: { label: "Coming soon", desc: "Not accepting cases yet. Leave your contact and we will let you know at launch." },
  },
  path: {
    document: { title: "Document", text: "A complaint, claim, application or lawsuit based on your words and evidence." },
    forum: { title: "Where to file", text: "An authority or organization taken only from a verified registry. We never make them up." },
    deadline: { title: "Deadlines", text: "We calculate the response deadline and remind you. If the deadline is not in our data, a lawyer will confirm it." },
    escalation: { title: "If refused or ignored", text: "No reply or a refusal? We prepare the next step: a higher authority or court." },
    lawyer: { title: "Lawyer", text: "When needed, we help you find a lawyer from the platform directory." },
  },
  emergency: {
    title: "Safety first",
    continue: "I am safe, continue",
    sample: "If there is a threat to life or health right now, call emergency services.",
  },
  metrics: {
    claude: { title: "Claude spend", lead: "Documents only. When a budget is used up, the free model writes the documents.", today: "Today", month: "This month" },
    lead: "Real cases on the platform only",
    users: "Users",
    cases: "Cases",
    documents: "Documents",
    submitted: "Filed",
    positive: "Resolved in the user's favor",
    recovered: "Recovered",
    atStake: "Amount in dispute",
    medianDays: "Median days to resolution",
    funnel: "Case funnel",
    table: "Weekly table",
    week: "Week",
    topScenarios: "Top scenarios",
    more: "More",
    repeat: "Came back with a new case",
    lawyer: "Handed to a lawyer",
    lawyerApps: "Lawyer applications",
    waitlist: "Waitlist (other countries)",
    countries: "Countries",
    weekly: { cases: "New cases per week", users: "New users per week", documents: "Documents per week", submitted: "Filed documents per week" },
    step: { created: "Created", classified: "Classified", intake_done: "Interview done", document_ready: "Document ready", submitted: "Filed", response: "Reply received", resolved_positive: "Resolved in the user's favor" },
  },
  pwa: {
    openSafari: "Open in Safari",
    openChrome: "Open in Chrome",
    noHomeScreen: "No “Add to Home Screen”? Open in Safari",
    // after the browser's install dialog: where the icon is now
    done: {
      android: "Done — the Konsiliér AI icon is on your home screen and in the app list.",
      windows: "Done — Konsiliér AI is on your desktop and in the Start menu. If the browser asks, tick “Desktop shortcut”.",
      mac: "Done — Konsiliér AI is in Launchpad and Applications. To keep it in the Dock: right-click its Dock icon → Options → Keep in Dock.",
      other: "Done — Konsiliér AI is installed and opens in its own window.",
    },
    install: "Install",
    offlineTitle: "No internet connection",
    offlineText: "Your cases are saved on the server. Reload the page once you're back online — everything will be there.",
    bannerTitle: "Get the Konsiliér AI app",
    bannerText: "Deadline alerts and your documents, right on your phone",
    // one line where the browser has no install dialog; {share} is drawn as the Share icon, {site} is the host
    hint: {
      ios: "Tap {share} and choose “Add to Home Screen”",
      ios26: "Tap “•••”, then {share} and “Add to Home Screen”",
      iosChrome: "1. Tap {share} at the right of the address bar\n2. At the bottom, tap “View More”\n3. “Add to Home Screen”\n4. “Add”",
      iosEdge: "1. Tap “•••” at the bottom\n2. {share} “Share”\n3. Scroll down to “Add to Home Screen”\n4. “Add”",
      iosFirefox: "1. Tap the ≡ menu at the bottom right\n2. {share} “Share”\n3. Scroll down to “Add to Home Screen”\n4. “Add”",
      iosOther: "1. Browser menu → {share} “Share”\n2. “Add to Home Screen” — not visible? Tap “More” or scroll down\n3. “Add”",
      iosInApp: "Apps can't be installed here — open the site in Safari or Chrome with one tap",
      androidInApp: "Apps can't be installed here — open the site in Chrome with one tap",
      androidChrome: "Menu ⋮ at the top right → “Install app” or “Add to Home screen” → “Install”",
      androidSamsung: "Menu ≡ at the bottom right → “Add page to” → “Home screen”",
      androidFirefox: "Menu ⋮ → “Install” or “Add to Home screen”",
      androidEdge: "Menu ··· at the bottom → “Add to phone”",
      menu: "Browser menu ⋮ → “Install app” or “Add to Home screen”",
      desktopChrome: "Click the install icon at the right of the address bar, or menu ⋮ → “Cast, save and share” → “Install page as app”. Already installed? Click “Open in app” in the address bar.",
      desktopEdge: "Menu ··· at the top right → “Apps” → “Install this site as an app”",
      desktopOther: "Click the install icon at the right of the address bar, or open the browser menu → “Install”",
      macSafari: "File → “Add to Dock”",
      firefox: "Firefox can't install websites as apps. Drag the padlock icon from the address bar to your desktop to make a shortcut, or open {site} in Chrome or Edge and click “Install”.",
      other: "Open {site} in Chrome or Edge to install",
    },
  },
  push: {
    title: "Notifications on this device",
    lead: "Deadline reminders, payment updates and finished documents reach you instantly, even when the site is closed.",
    short: "Get notified about deadlines and documents",
    enable: "Turn on notifications",
    disable: "Turn off",
    on: "Notifications are on for this device",
    denied: "Notifications are blocked in your browser settings. Allow them for konsilier.com and tap “Turn on” again.",
    ios: "On iPhone and iPad, notifications work only in the app: in Safari tap “Share” → “Add to Home Screen”, open Konsiliér AI from the Home Screen and turn notifications on there.",
    iosShort: "On iPhone, notifications arrive in the app on your Home Screen.",
    howTo: "How to install",
    unsupported: "This browser can't show notifications. Open the site in Chrome, Edge, Firefox or Safari.",
  },
  share: {
    eyebrow: "Files from another app",
    title: "Which case are these for?",
    lead: "Choose a case. The files will be added to it, and Konsiliér AI will read them and pick out the details it needs.",
    files: "Files: {n}",
    where: "Case",
    newCase: "New case",
    noCases: "You have no cases here yet.",
    signIn: "Sign in to see your cases",
    startCase: "Start a new case",
    attach: "Attach to the case",
    uploading: "Uploading {n} of {total}…",
    emptyTitle: "No files received",
    emptyText: "Share the files again: pick a photo, PDF or Word document and tap “Share” → Konsiliér AI.",
  },
  appPage: {
    title: "Konsiliér AI on your phone",
    lead: "Install Konsiliér on your phone or computer: your cases are always at hand, and you get reminders about deadlines.",
    installed: "The app is already installed on this device. Open it from the desktop, the Dock or “Open in app” in the address bar.",
    qrAlt: "QR code of the app page",
    qrTitle: "Open on your phone",
    qrText: "Point your camera at the code and tap “Install”.",
  },
  helper: {
    photo: "Take a photo",
    attach: "Attach a file",
    more: "More examples",
    examplesTitle: "Examples — tap to use",
    suggestTitle: "Does this match?",
    servicesTitle: "Where to file — we tell you what goes where",
    eotinish: "Requests and complaints to government bodies",
    sud: "Lawsuits and motions to court",
    egov: "Certificates and public services",
    step1: "Describe the problem",
    step2: "Answer a few questions and attach documents",
    step3: "Download the document and file it following the instructions",
    planTitle: "Proposed solution",
    planDoc: "We prepare",
    planTo: "Addressed to",
    planVia: "How to file",
    planAttach: "Prepare and attach",
    planSelf: "You file it yourself — we give step-by-step instructions",
    planLawyer: "A lawyer checks the document before filing",
    planUpload: "Upload a document",
    examples: { 1: "Get a refund for a faulty product", 2: "Recover unpaid wages", 3: "Appeal a traffic fine", 4: "Get my rental deposit back", 5: "Get back money debited from my card without consent", 6: "How to apply for a child benefit", 7: "How to get a grant to grow a business", 8: "How to get a study grant or scholarship", 9: "How to prepare a tender bid", 10: "How to apply for child support", 11: "Get a refund for an order that never arrived", 12: "Get my final pay after leaving a job" },
    exampleCount: "12",
    doc_download: "Download",
    doc_print: "Print",
    doc_save: "Save",
    doc_send: "Send",
    doc_sign: "Sign with EDS",
    doc_signUnavailable: "EDS signing on the site is not available right now. You can sign the document with your EDS on the portal when you file it (eOtinish, Judicial Cabinet) or sign it by hand.",
    doc_signed: "Signed with EDS",
    doc_fmtPdf: "PDF — to print and file",
    doc_fmtWord: "Word — to edit",
    doc_toWhatsapp: "WhatsApp",
    doc_toTelegram: "Telegram",
    doc_toMail: "Email",
    doc_toOther: "Another app",
    doc_fileReady: "The file has been downloaded — attach it in the window that opened.",
    doc_savedTo: "Saved",
  },
  cta: {
    pickSituation: "Choose a situation",
    draftDocument: "Prepare a document",
    title: "Start with your question.",
    lead: "Describe the situation in your own words — we will show the path and prepare the first document.",
    start: "Describe your situation",
    lawyer: "Find a lawyer",
    more: "Learn more",
    next: "Next",
    startCase: "Start a case",
    complain: "File a complaint",
    join: "Are you a lawyer? Join us",
    caseLawyerTitle: "Need a lawyer's help?",
    caseLawyerText: "A lawyer can review your documents or take over the whole case.",
    lawyersLead: "Describe the situation — we prepare the documents and bring in a lawyer when you need one.",
  },
  app: {
    toEnd: "To the latest message",
    tabs: { home: "Home", chat: "Chat", cases: "Cases", documents: "Documents", profile: "Profile" },
    signIn: "Sign in",
    newQuestion: "New question",
    toSite: "Back to the website",
    recent: "Recent cases",
    docs: { title: "Documents", lead: "All draft documents from your cases in one place.", empty: "No documents yet", emptyHint: "Describe your situation in the chat, and Konsiliér AI will gather the facts and prepare a draft document.", create: "Prepare a document", search: "Search by title", draft: "Draft", ready: "Ready to file", submitted: "Filed", open: "Open case", count: "Documents: {n}" },
    digits: "{n} of {total}",
    back: "Back",
    more: "More",
    close: "Close",
    cancel: "Cancel",
    roadmap: "Roadmap",
    facts: "Case details",
    documents: "Documents",
    lawyer: "Lawyer",
    gov: "eGov certificates",
    law: "Ask about the law",
    about: "About the service",
    account: "My account",
    home: "Home",
    photo: "Take a photo",
    file: "Choose a file",
    today: "Today",
    yesterday: "Yesterday",
    weekAgo: "A week ago",
    monthAgo: "A month ago",
    dontRemember: "Don't remember",
    dontRememberWord: "не помню",  // sent to the interview: a skip word of the case language
    noFacts: "No details yet — answer the questions in the conversation.",
    chat: "Chat",
    hint: {
      digits: "Digits only: {n} characters.",
      date: "Pick the date in the calendar or tap “Today” or “Yesterday”.",
      money: "Digits only — we add the spaces.",
      number: "Enter a number.",
      phone: "Phone number, e.g. +7 700 000 00 00.",
      email: "Email address.",
      text: "A short answer.",
    },
  },
  chat: {
    more: "More details",
    notice: "You are chatting with Konsiliér AI, your AI assistant for legal questions. Names and document numbers are masked before the AI processes your messages.",
    subtitle: "Your AI assistant for legal questions",
    greet: {"morning": "Good morning!", "day": "Good afternoon!", "evening": "Good evening!", "night": "Good evening!"},
    cancel: "Cancel recording",
    stop: "Stop response",
    copied: "Copied",
    copy: "Copy",
    share: "Share",
    voiceTitle: "Read replies aloud",
    placeholderNext: "Message",
    brand: "Konsiliér AI",
    freeShort: "Chat is free",
    eyebrow: "Free chat",
    title: "How can I help?",
    lead: "Type or use your voice, and attach photos or documents.",
    placeholder: "Describe what happened…",
    send: "Send",
    attach: "Attach a file",
    remove: "Remove file",
    mic: "Speak",
    micStop: "Stop recording",
    listening: "Go ahead — I'm recording…",
    transcribing: "Transcribing…",
    recordingLimit: "Recording up to 2 minutes, then the text appears in the box",
    speak: "Read aloud",
    stopSpeak: "Stop",
    voiceOn: "Replies aloud: on",
    voiceOff: "Replies aloud: off",
    thinking: "Thinking…",
    lookingUp: "Checking the official text of the law…",
    remaining: "{n} of {limit} free messages left (24-hour limit)",
    interrupted: "The answer was cut off — only its beginning is shown above.",
    retry: "Retry",
    article: "Article {n}",
    doc: "Prepare a document",
    docPrice: "from 1,990 ₸",
    lawyer: "Lawyer or advocate",
    lawyerPrice: "paid or free",
    free: "The chat is free. Konsiliér AI is an AI assistant, not a substitute for a lawyer.",
    open: "Open chat",
    errors: {
      agent_unavailable: "The AI chat is unavailable right now. Please try later or prepare the document step by step.",
      agent_failed: "The AI assistant could not answer. Please try again in a minute.",
      too_many_messages: "Limit reached: {limit} free messages per 24 hours. New ones become available 24 hours after the ones you sent — and you can prepare the document step by step right now.",
      busy: "We're under heavy load right now. Please try again in a minute.",
      mic_denied: "No access to the microphone. Allow it in your browser or phone settings and try again.",
      no_mic: "No microphone found. Connect one or type your message.",
      no_speech: "I didn't catch any speech. Speak closer to the microphone and try again.",
      mic_failed: "Couldn't start recording. Try again or type your message.",
      transcribe_unavailable: "Voice input isn't available right now. Please type your message.",
      transcribe_busy: "We're under heavy load and couldn't transcribe that. Try again in a minute.",
      transcribe_failed: "Couldn't transcribe the recording. Please try again.",
      transcribe_network: "The recording wasn't sent — check your connection and try again.",
      too_many_transcriptions: "Too many voice recordings this hour. Wait a little or type your message.",
      audio_too_large: "The recording is too long. Speak for up to 2 minutes at a time.",
    },
  },
  home: {
    placeholder: "Describe what happened…",
    eyebrow: "Konsiliér AI",
    title: "Your AI assistant for legal questions",
    sub: "Know your rights under the law and get your claim, complaint or lawsuit drafted for you.",
    promise1: "Finds the relevant articles in official legal texts",
    promise2: "Drafts your claim, complaint or application under the law",
    promise3: "Shows you where and how to file it",
    promise4: "Tracks deadlines and suggests the next step",
    describe: "Describe what happened",
    cta: "Ask a question",
    privacy: "Names and document numbers are replaced with placeholders before AI processing. Documents are filed in your name.",
    mySituation: "My situation",
    mySituationText: "Not on the list? Describe it in your own words — we'll tell you what to do.",
    situationsEyebrow: "Life situations",
    situationsTitle: "Where would you like to start?",
    situationsLead: "You do not need to know which area of law it is. Pick a similar situation or just describe yours.",
    pathEyebrow: "Path map",
    pathTitle: "How your case moves forward",
    pathLead: "At each step you can see who checked it and when a lawyer steps in.",
    levelsEyebrow: "Honest about what we can do",
    levelsTitle: "Three levels: you always know where your case stands",
    levelsLead: "We guide you all the way: document, filing, deadline tracking and a lawyer when you need one.",
    howLink: "Learn more about how it works",
    coverageTitle: "Kazakhstan is live. CIS and the Middle East are coming soon",
    coverageLead: "Uzbekistan, Kyrgyzstan, Azerbaijan, Turkey, the UAE, Saudi Arabia and other countries are in the launch plan.",
    coverageCta: "All services",
    stepsTitle: "From your question to the next step",
    steps: {
      share: "Know colleagues who could use this? Send them the link.",
      s1t: "Tell us what happened",
      s1d: "In text or by voice. You can attach photos of receipts, contracts, messages.",
      s2t: "Get an answer for free",
      s2d: "We explain your rights and what to do next, with links to the official texts of the law.",
      s3t: "File the document yourself",
      s3d: "Konsiliér AI drafts your claim, complaint or lawsuit, shows you where to file it and reminds you of deadlines. If your case needs an advocate, Konsiliér AI will tell you so plainly.",
    },
    priceTitle: "What it costs",
    price: {
      people: "For individuals",
      business: "For business",
      start: "Start",
      buy: "Sign up",
      perCase: "per case",
      perMonth: "per month",
      chatT: "AI chat",
      chatP: "Free",
      chatD: "AI chat: your rights and a plan of action, in text or by voice.",
      docT: "One document",
      docP: "1,990 ₸",
      docD: "A claim, complaint, application or lawsuit with instructions on where and how to file it.",
      caseT: "Full case",
      caseP: "9,990 ₸",
      caseD: "Every document in one case until the result: claim, complaint, lawsuit. Deadlines tracked, and the next step if the answer is a refusal or never comes.",
      bizT: "Business",
      bizP: "29,990 ₸",
      bizD: "For sole proprietors and small businesses: up to 20 documents a month — claims against counterparties, debt recovery, inspections.",
      bizproT: "Business Pro",
      bizproP: "59,990 ₸",
      bizproD: "For companies: up to 60 documents a month — for a steady flow of disputes.",
    },
    trustTitle: "Why you can trust us",
    trust: {
      t1: "We cite only the official texts of the law (Adilet legal information system).",
      t2: "Names, ID numbers and phone numbers are replaced with placeholders before AI processing.",
      t3: "You file the document yourself, in your own name — we send nothing without your decision.",
    },
    more: "Learn more",
  },
  training: { title: "Help make Konsiliér AI smarter", text: "I allow this case to be used to train Konsiliér AI — without my name, ID number, phone or address. I can withdraw any time." },
  situations: {
    cheated: { label: "I was cheated on a purchase", hint: "Goods, services, marketplaces, refunds.", placeholder: "What you bought, from whom, when, for how much and what went wrong" , ex1: "Get a refund for a phone that broke after a week", ex2: "Get a refund for an order that never arrived", ex3: "Get a poor-quality repair redone", ex4: "Get a refund for unused course lessons" },
    fired: { label: "Fired or wages not paid", hint: "Dismissal, unpaid wages, discrimination.", placeholder: "Where you work, what happened and when, how much you are owed" , ex1: "Recover three months of unpaid wages", ex2: "Get my final pay after dismissal", ex3: "Challenge a resignation I was pressured to sign", ex4: "Get paid for unused leave and overtime on leaving" },
    family: { label: "Divorce and children", hint: "Divorce, child support, who the child lives with, dividing property.", placeholder: "Briefly: what is happening and what you want to achieve" , ex1: "How to apply for child support", ex2: "How to file for divorce through the court", ex3: "How to set a schedule for contact with a child", ex4: "How to divide property acquired during marriage" },
    fine: { label: "A fine", hint: "Appealing a fine or a ruling.", placeholder: "What the fine is for, who issued it, when and why you disagree" , ex1: "Appeal a fine for a violation I didn't commit", ex2: "Appeal a camera fine when someone else was driving", ex3: "Challenge a tow when there was no sign", ex4: "Appeal a parking fine in my own courtyard" },
    crime: { label: "A crime against me", hint: "Theft, fraud, assault. Facts only: what, where, when.", placeholder: "What happened, where and when, who saw it, what the damage is" , ex1: "How to file a police report", ex2: "How to recover money taken from my card by fraud", ex3: "What to do if the police won't accept a report", ex4: "How to get back a prepayment made to an online seller" },
    stateBody: { label: "Dispute with a government body", hint: "Refusal, inaction, no reply to your request.", placeholder: "Which body, what you asked for and what they replied" , ex1: "Get a government body to answer my request", ex2: "Appeal a local authority's refusal of a land plot", ex3: "Appeal a refused benefit application", ex4: "Get a certificate the service center won't issue" },
    bank: { label: "Bank, loans, debt collectors", hint: "A loan in your name, a dispute with a bank, pressure from collectors.", placeholder: "Which bank or microlender, what happened, what amounts" , ex1: "Dispute a microloan taken out without my knowledge", ex2: "Stop collector calls about someone else's debt", ex3: "Get back money debited from my card without consent", ex4: "How to get a deferral on a loan" },
    business: { label: "Business dispute", hint: "A counterparty's debt, breach of contract.", placeholder: "Who the contract is with, what was breached, what amount" , ex1: "Collect a debt from a customer for delivered goods", ex2: "Get money back under an unfulfilled supply contract", ex3: "Draft a claim to a supplier for a short delivery", ex4: "Challenge early termination of a commercial lease" },
    inheritance: { label: "Inheritance", hint: "Accepting an inheritance, disputes between heirs.", placeholder: "Describe the inheritance and your question" , ex1: "How to accept an inheritance by law", ex2: "How to restore a missed deadline to accept an inheritance", ex3: "How to divide an inheritance between heirs", ex4: "What to do if the notary refused an inheritance certificate" },
    housing: { label: "Housing and neighbors", hint: "Rent, utilities, neighbors.", placeholder: "What kind of housing, who the dispute is with, what happened" , ex1: "Get my rental deposit back", ex2: "Claim damages after my neighbors flooded my apartment", ex3: "Dispute management company bills for services never provided", ex4: "What to do if the developer delays handing over the building" },
    benefits: { label: "Benefits and allowances", hint: "Child and disability benefits, social assistance, a refused payment.", placeholder: "Which payment you want, or what was refused, by whom and when", ex1: "How to apply for the childbirth benefit", ex2: "How to get the childcare allowance", ex3: "How to apply for targeted social assistance", ex4: "Appeal a refused benefit application" },
    grants: { label: "Grants and funding for business", hint: "A grant for a business idea, Damu, state support: documents and a business plan.", placeholder: "Your business or idea, what the money is for, which program", ex1: "How do I apply for a state grant for a new business idea", ex2: "I want non-repayable funding for my sole proprietorship: where do I start", ex3: "What business plan do I need for a state grant", ex4: "Which documents does a Damu fund grant require" },
    study: { label: "Study: grants and scholarships", hint: "A state grant by UNT score, Bolashak, scholarships, admission.", placeholder: "Where you are applying, your scores and documents", ex1: "How do I get a state education grant with my UNT score", ex2: "Which documents do I need for the education grant competition", ex3: "How do I apply for the Bolashak scholarship to study abroad", ex4: "I want to study abroad and need a motivation letter and a CV" },
    tenders: { label: "Tenders and public procurement", hint: "A tender bid, its documents, challenging the results.", placeholder: "The procurement number, what is bought, and whether you need a bid or a complaint", ex1: "How do I prepare a bid for a public tender", ex2: "Which documents does a company need to take part in public procurement", ex3: "How to win a tender: what to check in the tender documents", ex4: "Our tender bid was rejected and we want to challenge the results" },
  },
  inbox: { title: "Notifications", titleUnread: "Notifications, {n} new", empty: "No notifications yet. Deadline reminders, payments and ready documents will appear here.", readAll: "Mark all as read", markRead: "Mark as read", openCase: "Open case", openSupport: "Open request", new: "New" },
  board: {
    intake: "Request", qualified: "Details collected", action_ready: "Document ready", submitted: "Filed, awaiting response",
    escalated: "Appealing to a higher authority", handed_to_lawyer: "With a lawyer", resolved: "Resolved",
    empty: "Empty", stepOf: "Step {n} of {total}",
    attention: { hold: "Under review", ack: "Confirmation needed", expired: "Response deadline passed", approval: "Awaiting lawyer review", chooseForum: "Choose a recipient" },
    deadline: { left: "{n} days left", today: "Last day today", expired: "Deadline passed" },
  },
  ack: {
    false_report: { title: "Liability for knowingly false reports", button: "I understand and confirm", text: "Knowingly filing a false report is a criminal offense. Describe only facts you know." },
    special_category: { title: "Consent to process sensitive data", button: "I consent", text: "Your case may include data about health, religion or criminal record. We keep the minimum and use it only for your document." },
  },
  forum: {
    chooseTitle: "Where to file",
    chooseLead: "Choose a recipient. The list comes only from this country's registry of authorities; the differences are shown below.",
    type: { court: "Court", prosecutor: "Prosecutor's office", police: "Police", regulator: "Regulator", ministry: "Ministry",
      ombudsman: "Ombudsman", local_authority: "Local authority", arbitration: "Arbitration", mediation: "Mediation",
      private_org: "Organization" },
    effect: { binding: "Decision is binding", advisory: "Advisory decision", none: "No legal force" },
    verified: "Lawyer-verified", unverified: "A lawyer will confirm the details", deadlineByLawyer: "A lawyer will confirm the deadline",
    channels: "How to file", channel: { portal: "online portal", email: "email", post: "mail", in_person: "in person", whatsapp: "WhatsApp", telegram: "Telegram" },
    choose: "Choose",
  },
  common: { loading: "Loading…", sending: "Sending…" },
  roadmap: {
    title: "Case roadmap",
    best: "Best case",
    worst: "If all steps are needed",
    openEnded: "then work with a lawyer, timing as agreed",
    done: "Done",
    current: "Now",
    upcoming: "Next",
    skipped: "Not needed",
    ifNeeded: "if needed",
    due: "due",
    estimated: "estimated",
    finished: "completed",
    todoNorm: "a lawyer will confirm the deadline",
  },
  trust: {
    title: "How we protect you from fraud and empty promises",
    verifiedTitle: "How we check lawyers",
    verified: "Advocate or legal consultant status is checked against registries, and identity via digital signature (EDS). No verification, no access to clients.",
    escrowTitle: "Pay per stage, money held in reserve",
    escrow: "You do not pay everything upfront. The amount is held by a payment partner and released to the lawyer only when a stage is done: claim filed, reply received, lawsuit filed.",
    ratingTitle: "Rating based on proven results",
    rating: "The rating is based on real cases on the platform: how many were won, adjusted for difficulty, how much money was recovered, and whether deadlines were met. Reviews only after a deal.",
    roadmapTitle: "You see where your case is",
    roadmap: "A roadmap: what is done, what is happening now, what comes next and when to expect a decision, in the best and worst case.",
    soon: "Secure deals with lawyers (escrow) are in development",
    more: "Learn more",
    less: "Show less",
    now: "Now",
    verifiedMore: "Advocate: membership in a bar association and a valid license.\nLegal consultant: membership in the chamber of legal consultants.\nIdentity is confirmed with a digital signature (EDS), so no one can work under someone else's name.\nIf a license is revoked or a member is expelled from the chamber, the profile is hidden.",
    verifiedNow: "For now, our team checks lawyer applications manually against documents. Automatic registry checks and EDS sign-in are in development.",
    verifiedLink: "How to become a platform lawyer",
    escrowMore: "The price and stages are fixed in the contract before work starts.\nMoney for a stage is held by the payment partner, not the lawyer.\nThe lawyer gets paid when the stage is confirmed: document filed, reply received.\nIf a stage is not completed, the money for it is returned to you.\nDisputes are reviewed by the platform based on the documents in the case.",
    escrowNow: "In development: we are choosing a payment partner in Kazakhstan. Until launch, do not prepay lawyers for the whole case.",
    ratingMore: "The outcome is recorded when the case is closed on the platform, not based on the lawyer's word.\nResults are compared with the average for the same category, so easy cases do not inflate the rating.\nWeights: success 45%, meeting deadlines 20%, money recovered 20%, reviews 15%.\nNew lawyers' scores are pulled toward the platform average until they have 30+ cases.\nReviews can only be left after a real deal.",
    ratingNow: "For now we show an example with demo profiles: the real rating will appear once lawyers close their first cases on the platform.",
    ratingLink: "See a sample rating",
    roadmapMore: "Every step of the case: claim, waiting for a reply, complaint to a regulator, lawsuit.\nFor each step: the legal deadline and the date it expires.\nTwo forecasts: the best case (resolved after the claim) and if all steps are needed.\nWe remind you of deadlines so you do not miss any.",
    roadmapNow: "Already live: the roadmap opens in every case right after you describe the situation.",
    roadmapLink: "Start a case",
    cta: "See a sample rating",
    joinLawyer: "Are you a lawyer? Join us",
  },
  request: {
    back: "Lawyers and advocates",
    title: "Request to a lawyer",
    lead: "Describe the situation and leave your contacts. We register the case and pass it to a lawyer together with the documents.",
    story: "What happened",
    contacts: "Your contacts",
    name: "Full name",
    phone: "Phone",
    email: "Email (optional)",
    consent: "I agree to the processing of my personal data so that Konsiliér AI can pass the case to a lawyer, and I accept the",
    submit: "Send the request",
    note: "Booking a specific lawyer will become available together with payment through a payment partner. For now, we will pick a lawyer in the right field from the directory and let you know.",
    doneTitle: "Request registered",
    doneText: "The case is created and your contacts are saved. We will contact you once the case is passed to a lawyer.",
    proceed: "Add details to the case",
    continueHint: "Answer a few questions and attach documents — the lawyer gets a complete file and can quote a price right away.",
  },
  lawyers: {
    filter: "Show",
    all: "All lawyers",
    freeOnly: "Free",
    freeNote: "Human rights organizations and pro bono lawyers help for free. State-guaranteed free legal aid on some matters (child support, pensions and benefits, etc.) is also provided through bar associations and chambers of legal consultants.",
    freeNone: "No free lawyers in the directory yet.",
    title: "Lawyers and advocates",
    subtitle: "Rated by proven results on the platform, not by advertising.",
    score: "Rating",
    confidence: { low: "few cases", medium: "medium sample", high: "large sample" },
    vsBaseline: "vs. platform average",
    cases: "cases on the platform",
    recovered: "money recovered",
    onTime: "stages on time",
    reviews: "post-deal reviews",
    from: "from",
    proBono: "free (pro bono)",
    response: "average response time",
    hours: "h",
    years: "years of practice",
    verifiedLicense: "License verified",
    verifiedId: "Identity verified",
    success: "success",
    platform: "average",
    methodTitle: "How the rating works",
    method1: "Only cases handled through the platform: the outcome is recorded when the case closes, not based on the lawyer's word.",
    method2: "Results are compared with the average for the same case category, so picking easy cases does not raise the rating.",
    method3: "Small samples are pulled toward the average: 3 wins out of 3 will not beat 180 out of 220.",
    method4: "Weights: success 45%, meeting stage deadlines 20%, share of money recovered 20%, post-deal reviews 15%.",
    choose: "Contact",
    chooseSoon: "Booking a lawyer directly is not available yet: start a case and we will pass it to a lawyer with the collected documents.",
    pp: "pp",
    mln: "M",
    details: "More about results",
    sample: "Example",
    newProfile: "New platform partner: the rating will appear after the first completed cases.",
  },
  landing: {
    promise: "Your case, from the first document to the result",
    sub: "Describe the situation in your own words. Konsiliér AI will prepare a claim or complaint under the laws of Kazakhstan, tell you where to file it and keep track of deadlines. If that is not enough, a professional platform lawyer will see the case through.",
    usp1: "Ready documents, without searching for a lawyer or internet templates",
    usp2: "Deadlines under control: we remind you and prepare the next step",
    usp3: "A lawyer from the platform directory when you need a person",
    startWeb: "Start on the website",
    startTelegram: "Open in Telegram",
    scenariosTitle: "What we can do already",
    howTitle: "How it works",
    how1: "Tell us what happened",
    how2: "Answer a few short questions and upload receipts or screenshots",
    how3: "Get the document and filing instructions",
    how4: "We track the response deadline and suggest the next step",
    countryTitle: "Your country",
    countryLive: "Available",
    countrySoon: "Coming soon",
    waitlistTitle: "We do not work in this country yet",
    waitlistText: "Leave your contact and we will let you know when we launch.",
    waitlistContact: "Email or Telegram",
    waitlistProblem: "What problem are you facing? (optional)",
    waitlistSend: "Notify me at launch",
    waitlistDone: "Thank you! We will let you know when we launch.",
    price: "Price",
    disclaimer: "Documents are filed in your name, and you control every step.",
  },
  start: {
    eyebrow: "New case",
    country: "Country: Kazakhstan.",
    otherCountry: "Another country",
    busy: "Analyzing your situation… This may take up to a minute.",
    title: "What happened?",
    placeholder: "For example: I bought a phone from an online store on 12.08.2026 for 150,000 tenge, it broke a week later and they won't refund me",
    submit: "Continue",
  },
  case: {
    paid: "Paid",
    back: "All cases",
    untitled: "New case",
    holdTitle: "Case under manual review",
    draftTitle: "Please note",
    lawyerTitle: "The case is being passed to a lawyer",
    lawyerCta: "Lawyers in the directory",
    lawyerText: "We saved your description and are passing the case to a lawyer from the platform directory.",
    uplTitle: "Who we are",
    thinking: "Preparing a reply… On a slow connection this may take up to a minute.",
    working: "Working on it… Please keep this page open.",
    send: "Reply",
    answerPlaceholder: "Your answer",
    more: "Add details",
    morePlaceholder: "What exactly you bought or signed up for, from whom, when, for how much, and what went wrong",
    skip: "Skip",
    doneUploading: "Continue",
    upload: "Upload file",
    uploadHint: "Photo or PDF, up to 15 MB",
    found: "Found in the file",
    confirm: "Details are correct",
    nothingFound: "File saved. We could not read the data automatically.",
    facts: "Case details",
    prepare: "Prepare document",
    handoff: "Pass to a lawyer",
    awaitingApproval: "The document is being checked; this usually takes a few minutes. We will notify you as soon as it is ready.",
    rejected: "The lawyer sent the document back for changes.",
    download: "Download",
    instructions: "How to file",
    submitted: "Document filed",
    sendEmail: "Send to the recipient by email",
    deadline: "Response deadline",
    gotResponse: "Response received",
    noResponse: "No response received",
    responsePlaceholder: "Paste the text of the response",
    responseSend: "Analyze the response",
    responseFile: "or upload the response as a file",
    close: "Close the case",
    closeWon: "Fully resolved",
    closePartial: "Partly resolved",
    closeLost: "Not resolved",
    amountRecovered: "Amount received",
    outcome: "Outcome",
    days: "days",
    response: "Response",
    notifications: "Notifications",
    datePlaceholder: "DD.MM.YYYY",
    classes: { full: "Demand met", partial: "Partly met", refusal: "Refused", none: "No response" },
    deadlineStatus: { active: "running", met: "response received", expired: "expired", cancelled: "cancelled" },
    submittedHint: "Tap once you have handed in or sent the document to the recipient yourself. From that day we count the response deadline and remind you.",
  },
  cases: {
    title: "My cases", empty: "You have no cases yet", open: "Open", new: "New case",
    lead: "Questions, documents and next steps — together.",
    emptyHint: "Tell us what happened — it's free.",
  },
  coverage: {
    eyebrow: "Services",
    title: "Where we already help, and with what",
    lead: "What already works by country and area of law: where there are ready-made scenarios, where we prepare a document for your situation, and what is coming soon.",
    legend: "What the statuses mean",
    liveLead: "Status of each area of law in this country.",
    plannedTitle: "Coming soon: CIS and the Middle East",
    plannedLead: "We are preparing verified data for these countries with local lawyers. Not accepting cases yet.",
    waitlistTitle: "Notify me at launch",
    otherCountries: "Other countries — coming soon ({n})",
    sourcesTitle: "Official sources of law",
    sourcesLead: "We only link to and cite official government databases. Links open in a new tab.",
    sourceKind: { legislation: "Legislation", case_law: "Case law", gazette: "Official gazette", registry: "Registry" },
  },
  how: {
    eyebrow: "How it works",
    title: "Konsiliér AI — your AI assistant for legal questions",
    lead: "Tell us what happened. Konsiliér AI prepares your document under your country's law, shows you where to file it, keeps track of deadlines and, if you need one, helps you find a lawyer.",
    pathTitle: "How a case moves",
    pathLead: "Document → where to file → response deadline → next step → lawyer.",
    levelsTitle: "Three levels of help",
    levelsLead: "The level is set automatically and always shown in your case.",
    level: {
      verified: { title: "Verified scenario", when: "For common situations where a lawyer has signed off on the laws, deadlines and recipients.", get: { 1: "A document from a verified template", 2: "Legal response deadlines and reminders", 3: "The next step from a known sequence" } },
      universal: { title: "Tailored document", when: "When there is no ready-made scenario, but the area of law is clear and a suitable authority is in the registry.", get: { 1: "A document prepared from your story and evidence", 2: "Step-by-step filing: where, how and what to attach; a lawsuit only after a lawyer's review", 3: "Laws and deadlines only from data; otherwise \"a lawyer will confirm\"" } },
      lawyer: { title: "Handover to a lawyer", when: "Criminal defense, children, large amounts, deadlines about to expire, unclear situations.", get: { 1: "A case file based on your description", 2: "A lawyer from the platform directory", 3: "Defense documents are written only by an advocate" } },
    },
    rolesTitle: "Who does what",
    ai: {
      title: "AI",
      does: { 1: "Understands your story and asks short questions", 2: "Writes the statement of facts and sets out the demands", 3: "Reads the recipient's reply and suggests the next step", 4: "Works only with anonymized data" },
      neverTitle: "AI never",
      never: { 1: "Makes up laws, articles or deadlines", 2: "Chooses the authority to file with", 3: "Determines religion or ethnicity", 4: "Writes defense documents in criminal cases" },
    },
    lawyer: {
      title: "Lawyer",
      does: { 1: "Signs off on scenarios: laws, deadlines, recipients", 2: "Reviews lawsuits and court appeals before filing", 3: "Handles complex cases and represents you", 4: "Is responsible for the legal accuracy of the registry of authorities" },
    },
    promiseTitle: "What we promise and what we don't do",
    promiseLead: "No big promises: only what depends on us.",
    promise: { title: "We promise", 1: "A clear path for your case", 2: "A ready document and filing instructions", 3: "Deadline tracking and reminders", 4: "Help finding a lawyer when you need one" },
    dont: { title: "We don't", 1: "Represent you in court ourselves; platform lawyers do that", 2: "File a lawsuit without a lawyer's review", 3: "Write defense documents in criminal cases", 4: "Make up authorities, laws, deadlines or fees" },
    safetyTitle: "Safety",
    safety: {
      emergency: { title: "Emergencies", text: "If there is a threat to life, violence or a child in danger, we first show the country's emergency numbers." },
      falseReport: { title: "False reports", text: "In crime reports we warn about liability and ask you to describe facts, not opinions." },
      abuse: { title: "Abuse protection", text: "Mass complaints against one person, harassment, blackmail and defamation go to manual review." },
    },
  },
  ds: {
    title: "Design system", lead: "Konsiliér AI tokens and components: trust, clarity and accessibility on phone and desktop, in five languages.",
    colors: "Colors", type: "Typography", buttons: "Buttons", badges: "Level badges", notices: "Notices",
    noticesLead: "Emergency numbers, false-report warnings, the service's legal status and \"Please note\" are components, not fine print.",
    uplSample: "Konsiliér AI is a document preparation service and a technology intermediary with lawyers.",
    draftSample: "This document was prepared by the Konsiliér AI IT service based on your data. Check the details before filing.",
    forms: "Input fields", progress: "Case stages", board: "Case board", icons: "Icons",
  },
  errors: {
    title: "Something went wrong",
    saved: "Your data is saved and the case is not lost. We received an error report. Reload the page to continue.",
    translate: "If your browser's automatic page translation is on, turn it off for this site.",
    reload: "Reload page",
    retry: "Try again",
  },
  admin: {
    lawyers: {
      lead: "Approve only applications made with EDS, and only after checking the license number against the public registry.",
      ecp: "EDS",
      noEcp: "No EDS",
      license: "License",
      nameDiffers: "The application gives another name: {name}",
      verify: "Approve",
      assign: "Pass to a lawyer",
      assignButton: "Pass",
      assigned: "Passed to {name}. Documents for signing have been created.",
    },
    title: "Admin",
    tabs: { metrics: "Metrics", lawyers: "Lawyers", queue: "Review queue", board: "Board", holds: "Under review", forums: "Registry of authorities", demand: "Demand", errors: "Browser errors" },
    forum: "Recipient", hold: "On hold", release: "Release from review",
    forums: {
      registry: "Registry (from the pack)", registryLead: "The source of truth is YAML in the repository. Changes reach production only through a PR reviewed by a lawyer.",
      newDraft: "New entry (draft)", draftNote: "The draft is validated against the schema but does not affect production until it is exported and accepted in a PR.",
      save: "Save draft", saved: "Draft saved", drafts: "Drafts",
    },
    demand: { title: "Demand: situations without a ready-made scenario", lead: "Which situations come in without a ready-made scenario: candidates for the next verified scenarios.", country: "Country", dispute: "Dispute type", level: "Level", count: "Cases" },
    token: "Admin token",
    save: "Sign in",
    needsReview: "Only needs_review",
    pendingApproval: "Awaiting approval",
    all: "All",
    approve: "Approve",
    reject: "Send back",
    note: "Lawyer's comment",
    preview: "Document text",
    audit: "Log",
    closeCase: "Close case",
    waitlist: "Waitlist",
    tick: "Run reminders",
  },
  notFoundPage: { title: "This page doesn't exist", home: "Go to the home page" },
  theme: { title: "Appearance", light: "Light", dark: "Dark", system: "System" },
  account: {
    signOut: "Sign out",
    signOutConfirm: "Sign out on this device? Your cases are kept — sign in again the same way to see them.",
    moreWaysTitle: "More ways to sign in",
    otherWays: "Other ways: digital signature, eGov",
    withEmail: "Continue with email",
    withEcp: "Sign in with EDS key",
    withEgov: "Sign in with eGov Mobile",
    withGoogle: "Sign in with Google",
    withApple: "Sign in with Apple",
    methodSoon: "soon",
    signInLead: "One step, and your cases and documents are on any device.",
    signInOrUp: "Sign in or sign up",
    resendIn: "Send the code again in {n} s",
    resend: "Send the code again",
    bonus: "Free documents: {n} — for inviting friends. They are prepared without payment in any of your cases.",
    eyebrow: "Account",
    title: "Profile",
    lead: "Sign in to have your cases and documents on any device.",
    verifiedTitle: "Verified",
    waysTitle: "Ways to sign in",
    soon: "Soon",
    done: "Done: you are signed in. Your cases are now linked to your account.",
    privacy: "We store an encrypted fingerprint of your IIN, not the IIN itself, and show only its last digits. Codes are valid for 10 minutes.",
    kind: {
      email: "Email",
      phone: "Phone",
      iin: "IIN",
      google: "Google",
      apple: "Apple ID",
    },
    email: {
      title: "By email",
      hint: "We will send a six-digit code to your inbox.",
      label: "Email address",
      sent: "We sent a code to {target}. Check your spam folder too.",
    },
    phone: {
      title: "By phone number",
      hint: "We will send a code by SMS.",
      label: "Phone number",
      sent: "We sent an SMS code to {target}.",
    },
    ecp: {
      title: "Digital signature (NCALayer)",
      hint: "An EDS key on your computer: a file or an ID card. Confirms your identity.",
      step1: "Install and start NCALayer:",
      step2: "Click the button and choose your authentication key (AUTH_RSA or AUTH_GOST).",
      step3: "Enter the key password in the NCALayer window.",
      button: "Sign in with EDS",
      waiting: "Waiting for the signature in NCALayer…",
      not_running: "NCALayer is not running. Start it and try again.",
      cancelled: "Signing was cancelled.",
      failed: "NCALayer could not sign. Try again.",
    },
    egov: {
      title: "eGov Mobile",
      hint: "Confirm sign-in in the eGov Mobile or eGov Business app with a QR code.",
      button: "Show QR code",
      scan: "Open eGov Mobile → “QR scanner” and point the camera at the code.",
      onPhone: "On a phone? Open the app with this button:",
      waiting: "Waiting for confirmation in the app…",
      expired: "Time is up. Create a new code.",
      qrAlt: "QR code to sign in with eGov Mobile",
    },
    google: {
      button: "Sign in with Google",
      failed: "Could not open Google sign-in. Check your connection or try again later.",
    },
    apple: {
      button: "Sign in with Apple",
      failed: "Could not sign in with Apple. Please try again.",
    },
    sendCode: "Get code",
    codeLabel: "Code from the message",
    confirm: "Confirm",
    changeTarget: "Change address",
    errors: {
      too_soon: "A code was just sent. You can request another in a minute.",
      rate_limited: "Too many attempts. Try again in an hour.",
      wrong_code: "Wrong code.",
      code_expired: "The code has expired. Request a new one.",
      too_many_attempts: "Too many wrong attempts. Request a new code.",
      invalid_email: "Check the email address.",
      invalid_phone: "Check the phone number, e.g. +7 701 123 45 67.",
      method_unavailable: "This method is not available yet.",
      send_failed: "Could not send the code. Try later.",
      invalid_signature: "The signature did not pass verification.",
      certificate_invalid: "The EDS certificate is invalid or revoked.",
      chain: "We could not verify the EDS certificate against the Kazakhstan NCA chain. We are on it — try again later or sign in with eGov Mobile.",
      revoked: "The EDS certificate has been revoked. Get a new key at pki.gov.kz or sign in with eGov Mobile.",
      ocsp_unavailable: "The NCA server did not report the certificate status. Try again in a few minutes.",
      expired: "The EDS certificate has expired or is not valid yet. Get a new key at pki.gov.kz.",
      unsupported_alg: "This key type is not supported yet. Sign in with eGov Mobile or another method.",
      data_mismatch: "The signature does not match the data. Please try again.",
      wrong_data: "The wrong data was signed. Try again.",
      challenge_expired: "Time to sign ran out. Try again.",
      verifier_unavailable: "Signature checking is temporarily unavailable. Try later.",
      no_iin: "The certificate has no IIN.",
      invalid_token: "Sign-in could not be confirmed. Please try again.",
      token_expired: "Sign-in timed out. Please try again.",
      wrong_nonce: "This sign-in is out of date. Refresh the page and try again.",
      email_not_verified: "The email of this Google account is not verified. Verify it with Google or use another way to sign in.",
      provider_unavailable: "The sign-in service is temporarily unavailable. Please try later.",
      foreign_challenge: "Sign-in was started on another device. Refresh the page and try again.",
    },
  },
  sign: {
    signedByLawyer: "Signed with EDS by the lawyer: {name} ({id})",
    lead: "Sign the document with your EDS — a signed document is harder to dispute. The signed file will be attached to the email.",
    ncalayer: "Sign with EDS (NCALayer)",
    egov: "Sign with eGov Mobile",
    signedBy: "Signed with EDS: {name} ({id})",
    download: "Download the signed file (.cms)",
    verifyHint: "The signature can be checked in ezSigner or on sigex.kz.",
    errors: {
      use_sign_key: "Choose your signing key (RSA or GOST), not the sign-in key (AUTH).",
      signer_mismatch: "The applicant must sign: the IIN in the key differs from the IIN in the case.",
      document_changed: "The document changed. Start signing again.",
      wrong_data: "A different file was signed. Try again.",
      awaiting_approval: "The document is still being reviewed by a lawyer.",
    },
  },
  agreements: {
    yourLawyer: "Your lawyer",
    unreviewed: "These are platform templates not yet reviewed by the platform's lawyer. The lawyer on your case checks the terms and confirms them by signing.",
    leadCustomer: "Sign with your EDS, then the lawyer signs.",
    leadLawyer: "The client has signed. Check the terms and sign with the EDS you registered with.",
    waitCustomer: "Waiting for the client's signature.",
    waitLawyer: "Waiting for the lawyer's signature.",
    status: {
      awaiting_customer: "Awaiting the client's signature",
      awaiting_lawyer: "Awaiting the lawyer's signature",
      signed: "Signed by both parties",
    },
    kind: {
      advocate: "Advocate",
      legal_consultant: "Legal consultant",
      human_rights: "Human rights defender",
      other: "Lawyer",
    },
  },
  invite: {
    story: "Story card",
    storyTitle: "I know my rights",
    storyLine: "Konsiliér AI is a free AI assistant for legal questions. It helped me understand my situation and prepare a document.",
    storyOffer: "Through my link — a free document for us both after your first payment",
    storyScan: "Point your camera to open the site",
    bigTitle: "Send it to a friend — a free document for you both",
    bigLead: "When your friend pays for their first document through your link, you both get one more document free. Send the ready message in one tap.",
    other: "Another app",
    offer: "Invite a friend: when they pay for a document, you each get one document free",
    title: "Invite people who need it",
    lead: "Send your link to friends and family who have a similar problem. The chat is free for them.",
    share: "Share link",
    copied: "Link copied",
    invited: "People who came by your link: {n}",
    shareText: "Any legal situation — from getting your money back to a dispute with a state body. Konsiliér explains your rights in plain words and prepares the claim, complaint or application. Through my link we both get a document as a gift once you prepare your first document:",
  },
  send: {
    open: "Show the contacts found and all ways",
    title: "Sending wizard",
    lead: "You send it yourself, in your own name. We found contacts in the case documents and prepared a short text. The response deadline counts from the day you send it.",
    whom: "To whom",
    nothingFound: "We found no contacts in the case documents. Enter a phone number or e-mail below.",
    siteHint: "Contacts are usually in the website footer:",
    manual: "Another phone number or e-mail",
    manualPlaceholder: "+7 700 000 00 00 or name@company.kz",
    how: "How to send — fastest first",
    otherAddress: "another address",
    kinds: { whatsapp: "WhatsApp", phone: "Phone", telegram: "Telegram", instagram: "Instagram", email: "E-mail", website: "Website", bin: "BIN", address: "Address" },
    channels: { whatsapp: "WhatsApp", telegram: "Telegram", instagram: "Instagram", email: "E-mail", app_dispute: "Dispute in the bank or Kaspi app", other: "Other" },
    src: { evidence: "from the document “{label}”", story: "from your story", case: "from the case details" },
    shortText: "Short text — the full document is attached (PDF):",
    copy: "Copy text",
    copied: "Copied",
    openChat: "Open the chat",
    sharePdf: "Send the PDF",
    disputeHow: "If you paid through Kaspi or by bank card: open the app, find this payment in the history and choose “Dispute” or “Report a problem” (the name depends on the app). Attach the PDF and paste the short text.",
    proofHint: "Sent it? Mark it here — the response deadline counts from this moment. A screenshot showing “delivered” or “read” is your proof (you can add it later).",
    screenshot: "Attach a screenshot",
    iSent: "Send",
    sendTo: "Send via {app}",
    sentTo: "Sent via {app}",
    disputeDone: "I have opened a dispute",
    emailTo: "Recipient's e-mail (one address)",
    emailHint: "The letter goes from claims@konsilier.com in your name. Replies come to your e-mail, and so does a copy of the letter. Letters left for this document: {n}.",
    preview: "Preview the letter",
    from: "From",
    to: "To",
    replyTo: "Reply to",
    cc: "Copy",
    subject: "Subject",
    consent: "By pressing “Send” you instruct Konsiliér AI to pass your document to this recipient. We are a technical channel, not your representative.",
    sendNow: "Send",
    change: "Change",
    needEmail: "The recipient's reply will come to your e-mail — confirm your e-mail with a code.",
    sentList: "Sent",
    receiptSaved: "Screenshot saved",
    receiptAdd: "Add a screenshot",
    receiptMore: "Add another screenshot",
    plan: {
      title: "Where we will send it",
      emailAuto: "E-mail {to} — we send it ourselves as soon as you press (replies come to you)",
      emailOff: "E-mail {to} — sending by e-mail is not available now",
      messenger: "{app} {to} — we open the chat with one button, you send it from your own account",
      gov: "{to} — a state body: filed as a separate step, see how below",
      portal: "{to} — a state body: you file it on {portal} yourself; we show what to choose, give the text and the PDF, and read the number and date from the confirmation",
      portalDone: "{portal}: the appeal is filed and registered",
      portalGo: "File on {portal}",
      manual: "We found no contacts of the other side in the documents — add an address under “Other ways”",
      signAndSend: "Sign and send",
      send: "Send",
      signLead: "Sign the document with your electronic signature — we send it right after.",
      noSign: "Send without a signature — on my confirmation",
      openMessenger: "Open {app}",
      govNext: "Filing with the state body is a separate step: see how below.",
      other: "Other ways and another address",
    },
    status: { sending: "Sending", sent: "Sent", delivered: "Delivered", bounced: "Not delivered", complained: "Marked as spam", failed: "Sending failed", reported: "Sent by you", replied: "Replied" },
    errors: {
      confirm_required: "Press “Send” to confirm your instruction.",
      payment_required: "Sending is available once the document is paid for.",
      unavailable: "Sending by e-mail is not available yet. Send it through a messenger or mark it as submitted.",
      limit_document: "The letter limit for this document has been reached.",
      limit_case_day: "Today's letter limit for this case has been reached. Try tomorrow.",
      too_many: "Too many sendings in a row. Try again in an hour.",
      bad_email: "Check the address: one e-mail is needed, e.g. name@company.kz.",
      send_failed: "The letter did not go out. Please try again a little later.",
      not_ready: "The document is not ready to be sent yet.",
      cannot_submit_now: "It cannot be sent now: the case is at another stage.",
      email_required: "Confirm your e-mail.",
      too_large: "The file is too large.",
      bad_file: "A screenshot (image) or a PDF is needed.",
    },
  },
  submit: {
    courtName: "Judicial Cabinet",
    title: "File online via {portal}",
    lead: { eotinish: "eOtinish is the official portal for appeals to state bodies. You file in your own name; sign in and sign with an EDS or eGov Mobile.", court: "The Judicial Cabinet is the official portal for filing documents with Kazakhstan's courts. Sign in and sign with an EDS or eGov Mobile.", site: "The document is filed on the recipient's official website in your name." },
    s1: "Download the document and copy the cover text",
    download: "Download document",
    copy: "Copy text",
    copied: "Text copied",
    s2: "Open {portal} and send",
    open: "Open {portal}",
    how: { eotinish: "Sign in with an EDS or eGov Mobile, create an appeal, choose “{to}” as the recipient, paste the copied text, attach the file and send. The appeal number arrives in a notification.", court: "Sign in with an EDS or eGov Mobile, choose to file a document with a court, select “{to}”, attach the file and sign.", site: "Fill in the form on the recipient's website and attach the file." },
    s3: "Mark the document as filed",
    s3hint: "Tap “{btn}” at the bottom of the screen — we start counting the response deadline and remind you of the next step.",
    cover: "Please consider the attached document “{title}”. The full text and details are in the attachment.",
  },
  eotinish: {
    title: "File on eOtinish",
    lead: "eOtinish is the official portal for appeals to state bodies. You file the appeal yourself, in your own name, with your own digital signature or eGov Mobile. We have prepared everything for the form and keep track of the response deadline.",
    cta: "File on eOtinish",
    loading: "Preparing the guide…",
    s1: "What to choose in the eOtinish form",
    appealType: "Type of appeal",
    recipient: "Recipient",
    category: "Category / Subcategory",
    categoryAny: "Choose the topic closest to your appeal",
    unverified: "Names in the portal's lists may differ slightly — choose the closest one. Pick the region from the place stated in the document.",
    type: { statement: "Application", complaint: "Complaint", proposal: "Proposal", request: "Request" },
    s2: "Text of the appeal",
    copy: "Copy",
    copied: "Copied",
    s3: "File to attach",
    downloadPdf: "Download PDF",
    downloadDocx: "Download document",
    s4: "Open eotinish.kz and send",
    open: "Open eotinish.kz",
    how: "Sign in with your digital signature or eGov Mobile → «Submit an appeal» → choose the type, recipient and category from step 1 → paste the text → attach the file → sign and send. The appeal number arrives by SMS or appears in your account.",
    s5: "After filing — attach the confirmation",
    proofLead: "Attach the eOtinish screenshot, PDF or notification e-mail — we will read the appeal number and date ourselves.",
    proofAttach: "Attach confirmation",
    proofPaste: "Paste the SMS or e-mail text",
    proofPasteHint: "For example: «Appeal No. … of …»",
    proofRead: "Read",
    proofManual: "Enter the number manually",
    proofReading: "Reading the number and date…",
    proofFound: "Found in the confirmation — please check:",
    proofConfirm: "All correct",
    proofEdit: "Edit",
    proofNotFound: "Could not read the number or date. Enter them manually — the confirmation is already saved in the case.",
    number: "Appeal number",
    numberHint: "For example, ЖТ-2026-01234567",
    date: "Filing date",
    receipt: "Receipt or a screenshot with the number (optional — you can add it later)",
    receiptAttach: "Attach receipt",
    save: "Save and start the countdown",
    saveHint: "We count the response deadline from the filing date and remind you in advance.",
    filedTitle: "Appeal filed on eOtinish",
    receiptSaved: "Receipt saved in the case",
    filedHint: "The body will answer you through eOtinish. When you get the answer, tap «Response received».",
    err: {
      bad_number: "Check the appeal number: enter it exactly as eOtinish shows it (letters and digits).",
      date_in_future: "The filing date cannot be later than today.",
      date_before_document: "The filing date is earlier than the document was prepared. Check the date.",
      bad_receipt: "Could not attach the receipt. Try uploading the file again.",
      already_filed: "This document is already marked as filed.",
    },
  },
  support: {
    title: "Contact us",
    lead: "Ask a question about the service, report a problem or suggest an improvement. The reply will be sent to your email and will also appear on this page.",
    sentTitle: "Request No. {n} received",
    sentText: "The reply will be sent to your email and will also appear below under “My requests”.",
    kind: "Topic",
    kinds: { question: "Question", complaint: "Complaint", suggestion: "Suggestion", data: "My data", plan: "Plan request" },
    textLabel: { question: "Your question", complaint: "What went wrong", suggestion: "What could be better", data: "Which data and what to do with it", plan: "Tell us what you need" },
    planTitle: "Request for the “{plan}” plan",
    planText: "I would like to sign up for the “{plan}” plan.",
    case: "Which case is this about",
    noCase: "Not about a case",
    contacts: "Where to reply",
    contactHint: "Enter an email address, a phone number or both.",
    phoneOnly: "We reply by email. Without an email address, our reply will only appear on this page — add one so you don't miss it.",
    send: "Send",
    mine: "My requests",
    status: { new: "Received", in_progress: "In progress", done: "Resolved" },
    team: "Konsiliér AI",
    you: "You",
    replyPlaceholder: "Reply",
  },
  lawyer: {
    casesTitle: "Your cases",
    requests: {
      title: "Client requests",
      empty: "No new requests yet.",
      status: {
        new: "New",
        accepted: "Accepted",
        declined: "Declined",
        paid: "Paid",
        closed: "Closed",
      },
      category: "Category",
      city: "City",
      amount: "Amount in dispute",
      price: "Your price",
      payout: "Your payout (platform commission {pct}%)",
      accept: "Accept",
      decline: "Decline",
      waitPayment: "Waiting for the client's payment. Once paid, the case file and the client's contact details open.",
      client: "Client's contact details",
    },
    dossier: {
      open: "Open the case file",
      hide: "Hide the case file",
      story: "The client's story",
      narrative: "Summary for the documents",
      facts: "Facts",
      evidence: "Evidence",
      deadlines: "Deadlines",
      documents: "Documents",
      none: "None yet.",
      download: "Download",
    },
    steps: {
      title: "Joining as a lawyer",
      applied: "Application sent",
      appliedHint: "Fill in a short form: status, organization, fields of practice.",
      ecp: "Confirm your identity with EDS",
      ecpHint: "This is required: it shows the application is really yours, and you will sign documents with clients only with this EDS.",
      ecpDo: "Confirm with EDS",
      check: "Status check by the team",
      checkHint: "We check your advocate or legal consultant status against the registry and contact you by the contact you gave. Usually 1–2 working days.",
      access: "Access to cases",
      accessHint: "The dashboard opens automatically: cases, documents and signing agreements with clients.",
      doneLead: "One step left: confirm your identity with EDS, then the application goes to the status check.",
    },
    eyebrow: "For lawyers",
    title: "Lawyer dashboard",
    lead: "Cases the platform has passed to you, and documents with clients that are signed with EDS.",
    ecpNeeded: "Sign in with EDS: this confirms your identity, and only with this EDS will you be able to sign documents with clients.",
    ecpSignIn: "Sign in with EDS",
    ecpOk: "Identity confirmed with EDS",
    cabinetLink: "Open the lawyer dashboard",
    noApplication: "You have not applied to join yet.",
    apply: "Apply",
    noCases: "No cases have been passed to you yet.",
    aboutProgram: "About the partner program",
    status: {
      new: "Your application is being checked against the registry. This usually takes 1–2 working days.",
      rejected: "Your application was rejected. Write to us if this is a mistake.",
      rejectedReason: "Reason: {reason}",
    },
  },
  draft: {
    title: "Draft",
    lead: "This is how your document will look. You can read the beginning now; the full text opens after payment.",
    locked: "Full text after payment",
    blanks: "Fill in the empty fields — they go into the document",
    save: "Save to the document",
    error: { pattern: "Wrong format. A BIN or IIN has 12 digits.", address: "Enter the city, street and building number.", date: "The date was not recognised.", date_future: "The date cannot be in the future.", money: "Enter the amount as a number.", email: "The e-mail looks wrong.", phone: "Check the phone number.", generic: "Check the value." },
  },
  pilot: {
    inviteChecking: "Checking the link…",
    inviteInvalid: "This invitation link is invalid or has expired. Please ask the Konsiliér AI team for a new one: info@konsilier.com.",
    title: "Lawyer at a tap",
    lead: "The lawyer gets a ready file on your case: your story, the facts, the evidence and the documents. The lawyer first accepts your request, then you pay for their work.",
    empty: "Lawyers will appear here soon.",
    choose: "Send a request",
    contactsHint: "The lawyer sees your contact details and the case materials only after payment.",
    consent: "I agree to the processing of my personal data and to the case materials being passed to the chosen lawyer after payment.",
    send: "Send request",
    cancel: "Cancel",
    formError: "Check your name and phone number and tick the consent box.",
    waitingTitle: "Request sent",
    waiting: "{name} has received your request. We will let you know when they reply.",
    accepted: "{name} has accepted your request. Pay so that they receive the case materials.",
    pay: "Pay {price}",
    payLater: "Payment through the platform will open soon. The lawyer will contact you at the phone number you gave.",
    payTo: "Recipient: {name}",
    payLink: "Pay with Kaspi",
    payAccount: "Bank details for the transfer",
    payCode: "Payment code: enter it in the payment comment",
    companyNote: "The payment goes to the account of Konsilier AI, not to anyone's personal account.",
    paidBtn: "I have paid",
    checking: "We are checking the payment. As soon as it is confirmed, the lawyer will receive the case materials.",
    notFound: "No payment with code {code} was found. Check the amount and the comment and press «I have paid» again.",
    paid: "Paid. {name} has received the case materials.",
    declined: "{name} cannot take this case. Please choose another lawyer.",
  },
  formErrors: {
    required: "Please fill in this field",
    invalid: "Please check this value",
    too_long: "This value is too long",
    name_length: "2 to 100 characters",
    name_chars: "Letters, spaces, hyphens and apostrophes only — no digits, dots or other symbols",
    name_words: "Enter your full surname and given name — at least two words",
    phone_format: "Kazakhstan phone number: +7 and 10 digits, e.g. +7 701 123 45 67",
    phone_operator: "After +7 the number must start with 7 (701, 747, 777…). Enter a Kazakhstan number",
    email_format: "Please check the email, e.g. name@mail.kz",
    city_format: "Enter the city in letters",
    license_format: "Letters, digits, «№», «/» and hyphens only; at least one digit",
    kind_required: "Select your status",
    license_number_required: "A license or certificate number is required for advocates and legal consultants",
    consent_required: "We cannot accept the application without your consent to data processing",
    phone_duplicate: "An application with this number already exists — no need to apply again. You can see its status in the lawyer dashboard.",
    ecp_duplicate: "An application with this EDS already exists. You can see its status in the lawyer dashboard.",
    too_many: "Too many applications from this address. Please try again in an hour.",
    fix: "Please check the fields marked in red.",
  },
  gov: {
    ecpOnly: "Needs EDS",
    title: "Certificates from egov.kz",
    lead: "These certificates can strengthen your case. Get them yourself on egov.kz — with your EDS or eGov Mobile — and upload them here: they are added to the evidence.",
    needsEcp: "egov.kz sign-in: EDS or SMS code",
    open: "No sign-in",
    get: "Get on egov.kz",
    upload: "Upload certificate",
    uploaded: "Uploaded",
    disclaimer: "We do not sign in to egov.kz on your behalf and cannot see your data there — you get the certificate yourself.",
  },
  reports: {
    title: "Case reports by email",
    lead: "When your case moves, we send a report: where it stands, what is done and the next step, with detailed instructions. If it stalls, we remind you every 3 days.",
    toggle: "Send to {email}",
    needEmail: "Confirm your email below (“By email”) to get reports.",
    hint: "Get case reports and next-step reminders by email.",
    hintCta: "Confirm email",
  },
  payment: {
    applicant: { title: "Your details for the document", lead: "They appear in the document as the applicant's details. Fill them in once and we go on to payment.", continue: "Continue to payment" },
    contact: {
      phone: "Your phone — we will send the document and remind you of the deadline",
      email: "Your email — we will send the document and remind you of the deadline",
      lead: "Confirm it with a code — the case stays yours even if you switch browser or device.",
    },
    title: "Document payment",
    lead: "The chat is free; document preparation is paid. Transfer the amount via Kaspi using the details below — the document becomes available once the payment is confirmed.",
    recipient: "Recipient",
    kaspi: "Kaspi number for the transfer",
    code: "Payment code — put it in the transfer comment",
    copy: "Copy",
    copied: "Copied",
    steps: "Kaspi → Transfers → by phone number: enter the number and the amount, and put the payment code in the comment. After the transfer, tap “Pay”.",
    paid: "Pay",
    waiting: "We are checking the transfer. As soon as the payment is confirmed, the document is created automatically — you can close this window.",
    checking: "Checking the payment…",
    refresh: "Check payment status",
    notFound: "No transfer with this code has been found yet. Check the amount and the transfer comment, then tap “Pay” again or contact support.",
    unavailable: "Payment is temporarily unavailable, so documents cannot be issued right now. Please try later or contact support.",
    price: "Document preparation costs {price}. Payment by transfer; the document becomes available once the payment is confirmed.",
    titleCase: "Payment for “Full case”",
    choose: "How would you like to pay for the documents in this case?",
    option: { document: "One document — {price}", case: "Full case — {price}" },
    caseHint: "Full case: every document of this case until the result — claim, complaint, lawsuit.",
    service: "Service",
    serviceDocument: "Document",
    serviceCase: "Full case",
    cost: "Price",
    afterPay: "Your document will appear here right after payment",
    owed: "We couldn't find your previous Kaspi payment. Please pay — documents will be available again after that.",
    ways: {
      title: "How to pay",
      kaspi_transfer: "Kaspi transfer",
      kaspi_link: "Kaspi — by link",
      kaspi_qr: "Kaspi QR",
      kaspi_invoice: "Bill in Kaspi",
      bank_invoice: "Invoice for a company",
      openKaspi: "Open Kaspi",
      qrAlt: "Kaspi QR for payment",
      amount: "Amount",
      message: "Message to the seller — payment code",
      linkSteps: "In Kaspi.kz enter the amount and put the payment code in the message to the seller. Then press «Pay».",
      qrSteps: "Scan the QR in the Kaspi.kz app, enter the amount and the payment code in the message. Then press «Pay».",
      phoneLabel: "The number your Kaspi.kz is on",
      invoiceHint: "We will send a bill for this amount. It arrives in Kaspi.kz → Messages → Remote payment and is valid for 24 hours.",
      invoiceSend: "Send a bill to Kaspi",
      invoiceSent: "We are sending a bill to {phone}. Pay it in Kaspi.kz → Messages → Remote payment. The document is made after payment — you can close this window.",
      bankLead: "To pay from a company or sole trader bank account. Payee — {seller}.",
      buyer: "Payer — company or sole trader name",
      buyerPlaceholder: "LLP «…» or IE …",
      bin: "Payer’s BIN or IIN",
      address: "Payer’s address (optional)",
      bankDownload: "Download the invoice",
      bankSteps: "Pay the invoice from the bank account with the invoice number and payment code in the payment details. Then press «Pay».",
    },
  },
  plans: {
    title: "Plans for business",
    lead: "A 30-day subscription with a document limit. Pay by Kaspi transfer; the plan starts once the payment is confirmed.",
    active: "The “{plan}” plan is active until {date}. Documents left: {n}.",
    documents: "Up to {n} documents in {days} days, for any of your cases.",
    buy: "Sign up",
    signIn: "Sign in to get a plan, so that the payment is linked to you.",
    signInCta: "Sign in",
    payTitle: "Payment for the “{plan}” plan",
    forPeople: "Need one document or help with one case?",
    forPeopleCta: "Describe your situation",
  },
  filing: {
    title: "How to file",
    to: "Where",
    fileBy: "File by",
    respond: "They must answer {term}",
    within: {
      calendar: { one: "within {n} calendar day", other: "within {n} calendar days" },
      business: { one: "within {n} business day", other: "within {n} business days" },
    },
    norm: "Legal basis: {ref}",
    lawyer: "a lawyer will confirm",
    overdue: "This date has passed — discuss the next step with a lawyer",
    ways: "Ways to file",
    signature: "Signature",
    phone: "From a phone",
    desktop: "From a computer",
    open: "Open {portal}",
    stepByStep: "Step by step",
  },
  law: {
    title: "Ask about the law",
    lead: "Ask about your case. The AI finds the relevant provisions on the official Adilet portal (adilet.zan.kz), opens the articles and answers with links — every quote is checked against the official text.",
    placeholder: "For example: how soon must the employer pay me after dismissal?",
    ask: "Ask",
    busy: "Searching the law…",
    busyHint: "Usually 20–60 seconds: the AI opens articles on adilet.zan.kz.",
    verified: "Provisions checked against the official text",
    needsLawyer: "A lawyer will confirm: not every point is backed by the official text, or the question needs a lawyer.",
    norms: "What the answer rests on",
    article: "Article {n}",
    source: "Open on adilet.zan.kz",
    dropped: "Unconfirmed references dropped: {n}",
    disclaimer: "This is information from the official texts of the law, not a legal opinion. For complex cases we bring in a lawyer.",
    errors: {
      agent_unavailable: "Ask this question in the free AI chat.",
      agent_failed: "Could not answer right now. Try again a little later.",
      too_many_questions: "You have asked many questions about this case today. Please try again tomorrow.",
    },
  },
};

export default en;
