import type { Dict } from "./types";

const en: Dict = {
  nav: {
    start: "Start", cases: "My cases", admin: "Admin", lawyers: "Lawyers", forLawyers: "For lawyers",
    howItWorks: "How it works", coverage: "Coverage", menu: "Menu", language: "Language",
    skip: "Skip to content", main: "Main menu",
  },
  footer: {
    tagline: "From complaint to resolution: document, filing, deadlines and verified lawyers.",
    product: "Product", lawyers: "For lawyers", religious: "Religious bodies", designSystem: "Design system",
  },
  level: {
    verified: { label: "Lawyer-verified", desc: "Ready scenario: laws, deadlines and recipients signed off by a lawyer. Full autopilot." },
    scenario_draft: { label: "Scenario awaiting sign-off", desc: "The scenario works, but a lawyer has not yet signed off the laws and deadlines: documents are marked \"Draft\"." },
    universal: { label: "Universal path", desc: "No ready scenario. We prepare the document from a universal template, the recipient comes from the registry of authorities, and a lawyer reviews the document before filing." },
    lawyer: { label: "Lawyer needed", desc: "A complex or risky case: we build a case file and pass it to a verified lawyer." },
    soon: { label: "Coming soon", desc: "Not accepting cases yet. Leave your contact and we will let you know at launch." },
  },
  path: {
    document: { title: "Document", text: "A complaint, claim, application or lawsuit based on your words and evidence." },
    forum: { title: "Recipient", text: "An authority or organization taken only from a verified registry. We never make them up." },
    deadline: { title: "Deadlines", text: "We track the response deadline and remind you. If the deadline is not in our data, a lawyer will confirm it." },
    escalation: { title: "Escalation", text: "No reply or a refusal? We prepare the next step: a higher authority or court." },
    lawyer: { title: "Lawyer", text: "When needed, we connect a verified lawyer rated by results." },
  },
  emergency: {
    title: "Safety first",
    continue: "I am safe, continue",
    sample: "If there is a threat to life or health right now, call emergency services.",
  },
  home: {
    eyebrow: "Document · filing · deadlines · lawyer",
    title: "Any legal problem, from complaint to resolution",
    sub: "Describe what happened. We will prepare the document, tell you where to file it and keep track of deadlines. If you need a lawyer, we will connect a verified one.",
    promise1: "A document under the laws of your country",
    promise2: "Recipient from a verified registry",
    promise3: "Deadline reminders and the next step",
    promise4: "Verified lawyers when you really need one",
    describe: "Describe what happened",
    cta: "Continue",
    privacy: "Names and document numbers are replaced with labels before AI processing. Documents are filed in your name.",
    situationsEyebrow: "Life situations",
    situationsTitle: "What we help with",
    situationsLead: "You do not need to know which area of law it is. Pick a similar situation or just describe yours.",
    pathEyebrow: "Path map",
    pathTitle: "How your case moves forward",
    pathLead: "At each step you can see how it is verified: by a lawyer, via the universal path, or whether it needs a lawyer.",
    levelsEyebrow: "Honest about coverage",
    levelsTitle: "Three levels: you always know where your case stands",
    levelsLead: "We promise a path, a document, deadline tracking and a lawyer, not the outcome of the case.",
    howLink: "Learn more about how it works",
    coverageTitle: "Kazakhstan is live. CIS and the Middle East are coming soon",
    coverageLead: "Uzbekistan, Kyrgyzstan, Azerbaijan, Turkey, the UAE, Saudi Arabia and other countries are in the launch plan.",
    coverageCta: "Coverage by country",
  },
  situations: {
    cheated: { label: "I was cheated on a purchase", hint: "Goods, services, marketplaces, refunds.", placeholder: "What you bought, from whom, when, for how much and what went wrong" },
    fired: { label: "Fired or not paid wages", hint: "Dismissal, unpaid wages, discrimination.", placeholder: "Where you work, what happened and when, how much you are owed" },
    family: { label: "Divorce and children", hint: "Divorce, child support, who the child lives with, dividing property.", placeholder: "Briefly: what is happening and what you want to achieve" },
    fine: { label: "A fine", hint: "Appealing a fine or a ruling.", placeholder: "What the fine is for, who issued it, when and why you disagree" },
    crime: { label: "A crime against me", hint: "Theft, fraud, assault. Facts only: what, where, when.", placeholder: "What happened, where and when, who saw it, what the damage is" },
    stateBody: { label: "Dispute with a government body", hint: "Refusal, inaction, no reply to your request.", placeholder: "Which body, what you asked for and what they replied" },
    bank: { label: "Bank, loans, debt collectors", hint: "A loan in your name, a dispute with a bank, pressure from collectors.", placeholder: "Which bank or microlender, what happened, what amounts" },
    business: { label: "Business dispute", hint: "A counterparty's debt, breach of contract.", placeholder: "Who the contract is with, what was breached, what amount" },
    inheritance: { label: "Inheritance", hint: "Accepting an inheritance, disputes between heirs.", placeholder: "Who died and when, who the heirs are, what the issue is" },
    housing: { label: "Housing and neighbors", hint: "Rent, utilities, neighbors.", placeholder: "What kind of housing, who the dispute is with, what happened" },
    religious: { label: "Religious dispute resolution", hint: "We will show both the religious and the state path, with their legal status.", placeholder: "Describe the issue. We will show the state path in any case" },
  },
  board: {
    intake: "Request", qualified: "Details collected", action_ready: "Document ready", submitted: "Filed, awaiting reply",
    escalated: "Escalation", handed_to_lawyer: "With a lawyer", resolved: "Resolved",
    empty: "Empty", stepOf: "Step {n} of {total}",
    attention: { hold: "Under review", ack: "Confirmation needed", expired: "Response deadline passed", approval: "Awaiting lawyer review", chooseForum: "Choose a recipient" },
  },
  ack: {
    false_report: { title: "Liability for knowingly false reports", button: "I understand and confirm", text: "Knowingly filing a false report is a criminal offense. Describe only facts you know." },
    special_category: { title: "Consent to process sensitive data", button: "I consent", text: "Your case may include data about health, religion or criminal record. We keep the minimum and use it only for your document." },
  },
  forum: {
    chooseTitle: "Where to file",
    chooseLead: "Choose a recipient. The list comes only from this country's registry of authorities; the differences are shown below.",
    type: { court: "Court", prosecutor: "Prosecutor's office", police: "Police", regulator: "Regulator", ministry: "Ministry",
      ombudsman: "Ombudsman", local_authority: "Local authority", arbitration: "Arbitration", mediation: "Mediation",
      private_org: "Organization", religious: "Religious body" },
    effect: { binding: "Decision is binding", advisory: "Advisory decision", none: "No legal force" },
    verified: "Lawyer-verified", unverified: "A lawyer will confirm the details", deadlineByLawyer: "A lawyer will confirm the deadline",
    channels: "How to file", channel: { portal: "online portal", email: "email", post: "mail", in_person: "in person" },
    choose: "Choose",
  },
  common: { loading: "Loading…", sending: "Sending…" },
  roadmap: {
    title: "Case roadmap",
    best: "Best case",
    worst: "If all steps are needed",
    openEnded: "then work with a lawyer, timing as agreed",
    done: "Done",
    current: "Now",
    upcoming: "Next",
    skipped: "Not needed",
    ifNeeded: "if needed",
    due: "due",
    estimated: "estimated",
    finished: "completed",
    todoNorm: "a lawyer will confirm the deadline",
  },
  trust: {
    title: "How we protect you from fraud and empty promises",
    verifiedTitle: "Only verified lawyers",
    verified: "Advocate or legal consultant status is checked against registries, and identity via digital signature (EDS). No verification, no access to clients.",
    escrowTitle: "Pay per stage, money held in reserve",
    escrow: "You do not pay everything upfront. The amount is held by a payment partner and released to the lawyer only when a stage is done: claim filed, reply received, lawsuit filed.",
    ratingTitle: "Rating based on proven results",
    rating: "The rating is based on real cases on the platform: how many were won, adjusted for difficulty, how much money was recovered, and whether deadlines were met. Reviews only after a deal.",
    roadmapTitle: "You see where your case is",
    roadmap: "A roadmap: what is done, what is happening now, what comes next and when to expect a decision, in the best and worst case.",
    soon: "Safe deals with lawyers are in development",
    more: "Learn more",
    less: "Show less",
    now: "Now",
    verifiedMore: "Advocate: membership in a bar association and a valid license.\nLegal consultant: membership in the chamber of legal consultants.\nIdentity is confirmed with a digital signature (EDS), so no one can work under someone else's name.\nIf a license is revoked or a member is expelled from the chamber, the profile is hidden.",
    verifiedNow: "For now, our team checks lawyer applications manually against documents. Automatic registry checks and EDS sign-in are in development.",
    verifiedLink: "How to become a platform lawyer",
    escrowMore: "The price and stages are fixed in the contract before work starts.\nMoney for a stage is held by the payment partner, not the lawyer.\nThe lawyer gets paid when the stage is confirmed: document filed, reply received.\nIf a stage is not completed, the money for it is returned to you.\nDisputes are reviewed by the platform based on the documents in the case.",
    escrowNow: "In development: we are choosing a payment partner in Kazakhstan. Until launch, do not prepay lawyers for the whole case.",
    ratingMore: "The outcome is recorded when the case is closed on the platform, not based on the lawyer's word.\nResults are compared with the average for the same category, so easy cases do not inflate the rating.\nWeights: success 45%, meeting deadlines 20%, money recovered 20%, reviews 15%.\nNew lawyers' scores are pulled toward the platform average until they have 30+ cases.\nReviews can only be left after a real deal.",
    ratingNow: "For now we show an example with demo profiles: the real rating will appear once lawyers close their first cases on the platform.",
    ratingLink: "See a sample rating",
    roadmapMore: "Every step of the case: claim, waiting for a reply, complaint to a regulator, lawsuit.\nFor each step: the legal deadline and the date it expires.\nTwo forecasts: the best case (resolved after the claim) and if all steps are needed.\nWe remind you of deadlines so you do not miss any.",
    roadmapNow: "Already live: the roadmap opens in every case right after you describe the situation.",
    roadmapLink: "Start a case",
    cta: "See a sample rating",
    joinLawyer: "Are you a lawyer? Join us",
  },
  lawyers: {
    title: "Lawyers and advocates",
    subtitle: "Rated by proven results on the platform, not by advertising.",
    score: "Rating",
    confidence: { low: "few cases", medium: "medium sample", high: "large sample" },
    vsBaseline: "vs. platform average",
    cases: "verified cases",
    recovered: "money recovered",
    onTime: "stages on time",
    reviews: "post-deal reviews",
    from: "from",
    proBono: "free (pro bono)",
    response: "average response time",
    hours: "h",
    years: "years of practice",
    verifiedLicense: "License verified",
    verifiedId: "Identity verified",
    success: "success",
    platform: "average",
    methodTitle: "How the rating works",
    method1: "Only cases handled through the platform: the outcome is recorded when the case closes, not based on the lawyer's word.",
    method2: "Results are compared with the average for the same case category, so picking easy cases does not raise the rating.",
    method3: "Small samples are pulled toward the average: 3 wins out of 3 will not beat 180 out of 220.",
    method4: "Weights: success 45%, meeting stage deadlines 20%, share of money recovered 20%, post-deal reviews 15%.",
    choose: "Choose",
    chooseSoon: "Choosing a lawyer will open together with safe deals",
    pp: "pp",
    mln: "M",
  },
  landing: {
    promise: "Your case, from the first document to the result",
    sub: "Describe the situation in your own words. Konsilier.AI will prepare a claim or complaint under the laws of Kazakhstan, tell you where to file it and keep track of deadlines. If that is not enough, a professional platform lawyer will see the case through.",
    usp1: "Ready documents, without searching for a lawyer or internet templates",
    usp2: "Deadlines under control: we remind you and prepare the next step",
    usp3: "Platform lawyers: verified and rated by real results",
    startWeb: "Start on the website",
    startTelegram: "Open in Telegram",
    scenariosTitle: "What we can do already",
    howTitle: "How it works",
    how1: "Tell us what happened",
    how2: "Answer a few short questions and upload receipts or screenshots",
    how3: "Get the document and filing instructions",
    how4: "We track the response deadline and suggest the next step",
    countryTitle: "Your country",
    countryLive: "Available",
    countrySoon: "Coming soon",
    waitlistTitle: "We do not work in this country yet",
    waitlistText: "Leave your contact and we will let you know when we launch.",
    waitlistContact: "Email or Telegram",
    waitlistProblem: "What problem are you facing? (optional)",
    waitlistSend: "Notify me at launch",
    waitlistDone: "Thank you! We will let you know when we launch.",
    price: "Price",
    disclaimer: "Documents are filed in your name, and you control every step.",
  },
  start: {
    eyebrow: "New case",
    religiousLabel: "Also consider religious dispute resolution",
    religiousHint: "Only if you choose it. We will show the state path in any case.",
    religiousMore: "What this means",
    country: "Country: Kazakhstan.",
    otherCountry: "Another country",
    busy: "Analyzing your situation… This may take up to a minute.",
    title: "What happened?",
    placeholder: "For example: I bought a phone from an online store on 12.08.2026 for 150,000 tenge, it broke a week later and they won't refund me",
    submit: "Continue",
  },
  case: {
    back: "All cases",
    untitled: "New case",
    holdTitle: "Case under manual review",
    draftTitle: "Draft",
    lawyerTitle: "The case is being passed to a lawyer",
    lawyerCta: "Verified lawyers",
    lawyerText: "We saved your description and are passing the case to a verified platform lawyer.",
    uplTitle: "Who we are",
    thinking: "Preparing a reply… On a slow connection this may take up to a minute.",
    working: "Working on it… Please keep this page open.",
    send: "Reply",
    answerPlaceholder: "Your answer",
    more: "Add details",
    morePlaceholder: "What exactly you bought or signed up for, from whom, when, for how much, and what went wrong",
    skip: "Skip",
    upload: "Upload file",
    uploadHint: "Photo or PDF, up to 15 MB",
    found: "Found in the file",
    confirm: "All correct",
    nothingFound: "File saved. We could not read the data automatically.",
    facts: "Case details",
    prepare: "Prepare document",
    handoff: "Pass to a lawyer",
    awaitingApproval: "A lawyer is reviewing the document. We will let you know when it is ready.",
    rejected: "The lawyer sent the document back for changes.",
    download: "Download",
    instructions: "How to file",
    submitted: "I have sent it",
    sendEmail: "Send it by email for me",
    deadline: "Response deadline",
    gotResponse: "I got a reply",
    noResponse: "No reply",
    responsePlaceholder: "Paste the reply text",
    responseSend: "Analyze the reply",
    responseFile: "or upload the reply file",
    close: "Close case",
    closeWon: "Fully recovered",
    closePartial: "Partly",
    closeLost: "Not recovered",
    amountRecovered: "Amount recovered",
    outcome: "Outcome",
    days: "days",
    response: "Reply",
    notifications: "Notifications",
    datePlaceholder: "DD.MM.YYYY",
    classes: { full: "In full", partial: "Partly", refusal: "Refusal", none: "No reply" },
    deadlineStatus: { active: "running", met: "reply received", expired: "expired", cancelled: "cancelled" },
  },
  cases: {
    title: "My cases", empty: "No cases yet.", open: "Open", new: "New case",
    lead: "Each case is a card on the board, from request to resolution. Cases do not disappear; they move through the stages.",
  },
  coverage: {
    eyebrow: "Coverage",
    title: "Where and with what we already help",
    lead: "Honest status by country and area of law: what is lawyer-verified, where the universal path with lawyer review works, and what is coming soon.",
    legend: "What the statuses mean",
    liveLead: "Status of each area of law in this country.",
    plannedTitle: "Coming soon: CIS and the Middle East",
    plannedLead: "We are preparing verified data for these countries with local lawyers. Not accepting cases yet.",
    waitlistTitle: "Notify me at launch",
  },
  how: {
    eyebrow: "How it works",
    title: "Path, document, deadline tracking and a lawyer",
    lead: "Konsilier.AI takes your case to a ready document, filing and the next step. AI helps with the text, while laws, deadlines and recipients come only from verified data.",
    pathTitle: "Path map",
    pathLead: "Document → recipient → deadline → escalation → lawyer.",
    levelsTitle: "Three coverage levels",
    levelsLead: "The level is set automatically and always shown in your case.",
    level: {
      verified: { title: "Verified scenario", when: "For common situations where a lawyer has signed off the laws, deadlines and recipients.", get: { 1: "A document from a verified template", 2: "Legal response deadlines and reminders", 3: "The next step from a known sequence" } },
      universal: { title: "Universal path", when: "When there is no ready scenario, but the area of law is clear and a suitable authority is in the registry.", get: { 1: "A document from a universal template marked \"Draft\"", 2: "Lawyer review before filing, always", 3: "Laws and deadlines only from data; otherwise \"a lawyer will confirm\"" } },
      lawyer: { title: "Handover to a lawyer", when: "Criminal defense, children, large amounts, deadlines about to expire, unclear situations.", get: { 1: "A case file based on your description", 2: "A verified lawyer rated by results", 3: "Defense documents are written only by an advocate" } },
    },
    rolesTitle: "Who does what",
    ai: {
      title: "AI",
      does: { 1: "Understands your story and asks short questions", 2: "Writes the statement of facts and sets out the demands", 3: "Reads the recipient's reply and suggests the next step", 4: "Works only with anonymized data" },
      neverTitle: "AI never",
      never: { 1: "Makes up laws, articles or deadlines", 2: "Chooses the authority to file with", 3: "Determines religion or ethnicity", 4: "Writes defense documents in criminal cases" },
    },
    lawyer: {
      title: "Lawyer",
      does: { 1: "Signs off scenarios: laws, deadlines, recipients", 2: "Reviews every universal-path document before filing", 3: "Handles complex cases and represents you", 4: "Is responsible for the legal accuracy of the registry of authorities" },
    },
    promiseTitle: "What we promise and what we don't do",
    promiseLead: "No big promises: only what depends on us.",
    promise: { title: "We promise", 1: "A clear path for your case", 2: "A ready document and filing instructions", 3: "Deadline tracking and reminders", 4: "A verified lawyer when you need one" },
    dont: { title: "We don't", 1: "Represent you in court ourselves; platform lawyers do that", 2: "File universal-path documents without a lawyer's approval", 3: "Write defense documents in criminal cases", 4: "Make up authorities, laws, deadlines or fees", 5: "Push a religious path" },
    safetyTitle: "Safety",
    safety: {
      emergency: { title: "Emergencies", text: "If there is a threat to life, violence or a child in danger, we first show the country's emergency numbers." },
      falseReport: { title: "False reports", text: "In crime reports we warn about liability and ask you to describe facts, not opinions." },
      abuse: { title: "Abuse protection", text: "Mass complaints against one person, harassment, blackmail and defamation go to manual review." },
    },
  },
  religious: {
    eyebrow: "Religious bodies",
    title: "Religious dispute resolution",
    lead: "Some people want to resolve an issue through an imam, a muftiate, a sharia council or bodies of other faiths. We show this path only if you choose it, alongside the state path and with an honest legal status.",
    status: {
      binding: { title: "State court", text: "In some countries, religious courts for personal status matters are part of the court system, and their decisions are binding." },
      advisory: { title: "Advisory body", text: "Helps reconcile the parties or gives an opinion, but the decision is not enforceable." },
      none: { title: "No legal force", text: "A religious body's decision does not replace a decision of a court or government authority." },
    },
    rules: { title: "Our rules", 1: "We show it only if you chose this path yourself", 2: "We do not determine your religion or ask about it without reason", 3: "The state path for the same issue is always shown alongside", 4: "Religious law comes only from qualified specialists, not from AI", 5: "Any faith, with no preference" },
    family: { title: "Family matters: important", text: "Child support, children, property, divorce and inheritance: if a religious procedure does not protect your legal rights, we will warn you clearly and show the state path." },
    kz: { title: "For example, Kazakhstan", text: "Religious associations are separate from the state: a decision of a spiritual administration does not replace a court decision. That is why in Kazakhstan we show the state path." },
    cta: "Describe your situation",
  },
  ds: {
    title: "Design system", lead: "Konsilier tokens and components: trust, clarity and accessibility on phone and desktop, in five languages.",
    colors: "Colors", type: "Typography", buttons: "Buttons", badges: "Level badges", notices: "Notices",
    noticesLead: "Emergency numbers, false-report warnings, the service's legal status and \"Draft\" are components, not fine print.",
    uplSample: "Konsilier.AI is a document preparation service and a technology intermediary with lawyers.",
    draftSample: "This scenario has not yet been signed off by a lawyer. References to laws and deadlines need to be checked.",
    forms: "Input fields", progress: "Case stages", board: "Case board", icons: "Icons",
  },
  errors: {
    title: "Something went wrong",
    saved: "Your data is saved and the case is not lost. We received an error report. Reload the page to continue.",
    translate: "If your browser's automatic page translation is on, turn it off for this site.",
    reload: "Reload page",
    retry: "Try again",
  },
  admin: {
    title: "Admin",
    tabs: { queue: "Review queue", board: "Board", holds: "Under review", forums: "Registry of authorities", demand: "Demand" },
    forum: "Recipient", hold: "On hold", release: "Release from review",
    forums: {
      registry: "Registry (from package)", registryLead: "The source of truth is YAML in the repository. Changes reach production only through a PR reviewed by a lawyer.",
      newDraft: "New entry (draft)", draftNote: "The draft is validated against the schema but does not affect production until it is exported and accepted in a PR.",
      save: "Save draft", saved: "Draft saved", drafts: "Drafts",
    },
    demand: { title: "Demand on the universal path", lead: "Which situations come in without a ready scenario: candidates for the next verified scenarios.", country: "Country", dispute: "Dispute type", level: "Level", count: "Cases" },
    token: "Admin token",
    save: "Sign in",
    needsReview: "Only needs_review",
    pendingApproval: "Awaiting approval",
    all: "All",
    approve: "Approve",
    reject: "Send back",
    note: "Lawyer's comment",
    preview: "Document text",
    audit: "Log",
    closeCase: "Close case",
    waitlist: "Waitlist",
    tick: "Run reminders",
  },
};

export default en;
