import type { Dict } from "./types";

const tr: Dict = {
  nav: {
    account: "Giriş",
    start: "Başla", cases: "Dosyalarım", admin: "Yönetim", lawyers: "Avukatlar", forLawyers: "Avukatlar için",
    howItWorks: "Nasıl çalışır", coverage: "Hizmetler", menu: "Menü", language: "Dil",
    skip: "İçeriğe geç", main: "Ana menü",
    app: "Uygulama",
  },
  legal: {
    disclaimer: "Konsiliér AI, hukuki sorular için yapay zekâ asistanıdır. Yapay zekânın yanıtları bilgi amaçlıdır, hazırlanan belgeler ise taslaktır: sunmadan önce kontrol edin.",
    terms: "Kullanım Koşulları",
    accept: "Mesaj göndererek şunu kabul etmiş olursunuz:",
    version: "sürüm",
    languageNote: "Koşullar Kazakça ve Rusça hazırlanmıştır; burada İngilizce çevirisi gösterilmektedir.",
  },
  footer: {
    company: "Konsilier AI LLP · BIN 260940036818",
    said: "Konsiliér [kon-sil-YER] — hukuki sorular için yapay zekâ asistanı",
    contacts: "İletişim",
    lawyerCabinet: "Avukat paneli",
    tagline: "Sorununuzu anlatın — Konsiliér AI ülkenizin yasalarına göre gerekli belgeyi hazırlar, nereye başvuracağınızı söyler, süreleri takip eder ve gerektiğinde avukat bulmanıza yardım eder.",
    product: "Ürün", lawyers: "Avukatlara", designSystem: "Tasarım sistemi", support: "Bize yazın",
  },
  level: {
    pending: { label: "Yol belirleniyor", desc: "Durumu inceliyoruz. Ne olduğu netleşince uygun yolu ve ilk adımı göstereceğiz." },
    verified: { label: "Avukat onaylı", desc: "Hazır senaryo: mevzuat, süreler ve muhataplar avukat tarafından onaylandı. Tamamen otomatik süreç." },
    scenario_draft: { label: "Sık görülen durum", desc: "Bu durum için hazır bir senaryo var: sorular, belge ve yapılacaklar. Mevzuat ve süre atıflarını avukat ayrıca kontrol eder." },
    universal: { label: "Size özel belge", desc: "Belgeyi durumunuza göre hazırlarız: metin anlattıklarınıza ve delillerinize göre, muhatap kurum sicilinden. İhtarname, şikâyet veya dilekçeyi adım adım talimatla kendiniz sunarsınız; dava dilekçesini avukat önceden kontrol eder." },
    lawyer: { label: "Avukat gerekli", desc: "Karmaşık veya riskli durum: dosyayı hazırlıyor ve avukat bulmanıza yardım ediyoruz." },
    soon: { label: "Yakında", desc: "Şimdilik dosya kabul etmiyoruz. İletişim bilgilerinizi bırakın, açıldığımızda yazalım." },
  },
  path: {
    document: { title: "Belge", text: "Anlattıklarınıza ve delillerinize göre şikâyet, ihtarname, dilekçe veya dava dilekçesi." },
    forum: { title: "Nereye başvurulur", text: "Kurum veya kuruluş yalnızca doğrulanmış sicilden seçilir, uydurmayız." },
    deadline: { title: "Süreler", text: "Cevap süresini hesaplar ve hatırlatırız. Süre verilerde yoksa avukat netleştirir." },
    escalation: { title: "Ret veya cevapsızlık halinde", text: "Cevap yoksa veya ret geldiyse sonraki adımı hazırlarız: üst kurum, mahkeme." },
    lawyer: { title: "Avukat", text: "Gerektiğinde platform kataloğundan avukat bulmanıza yardım ederiz." },
  },
  emergency: {
    title: "Önce güvenlik",
    continue: "Güvendeyim, devam et",
    sample: "Şu anda hayatınız veya sağlığınız tehlikedeyse acil yardım hatlarını arayın.",
  },
  metrics: {
    claude: { title: "Claude harcaması", lead: "Yalnızca belgeler. Bütçe dolduğunda belgeleri ücretsiz model yazar.", today: "Bugün", month: "Bu ay" },
    lead: "Yalnızca platformdaki gerçek dosyalar",
    users: "Kullanıcılar",
    cases: "Dosyalar",
    documents: "Belgeler",
    submitted: "Sunuldu",
    positive: "Lehine sonuçlandı",
    recovered: "Geri alınan",
    atStake: "Uyuşmazlık tutarı",
    medianDays: "Sonuca kadar medyan gün",
    funnel: "Dosya hunisi",
    table: "Haftalık tablo",
    week: "Hafta",
    topScenarios: "Popüler senaryolar",
    more: "Diğer",
    repeat: "Yeni dosyayla dönenler",
    lawyer: "Avukata devredildi",
    lawyerApps: "Avukat başvuruları",
    waitlist: "Bekleme listesi (diğer ülkeler)",
    countries: "Ülkeler",
    weekly: { cases: "Haftalık yeni dosyalar", users: "Haftalık yeni kullanıcılar", documents: "Haftalık belgeler", submitted: "Haftalık sunulan belgeler" },
    step: { created: "Oluşturuldu", classified: "Sınıflandırıldı", intake_done: "Görüşme tamamlandı", document_ready: "Belge hazır", submitted: "Sunuldu", response: "Yanıt alındı", resolved_positive: "Lehine sonuçlandı" },
  },
  pwa: {
    openSafari: "Safari'de aç",
    openChrome: "Chrome'da aç",
    noHomeScreen: "“Ana Ekrana Ekle” yok mu? Safari'de aç",
    // after the browser's install dialog: where the icon is now
    done: {
      android: "Hazır — Konsiliér AI simgesi ana ekranda ve uygulama listesinde.",
      windows: "Hazır — Konsiliér AI masaüstünde ve Başlat menüsünde. Tarayıcı sorarsa “Masaüstü kısayolu”nu işaretleyin.",
      mac: "Hazır — Konsiliér AI Launchpad'de ve Uygulamalar klasöründe. Dock'ta tutmak için: Dock'taki simgeye sağ tıklayın → Seçenekler → Dock'ta Tut.",
      other: "Hazır — Konsiliér AI yüklendi ve ayrı bir pencerede açılır.",
    },
    install: "Yükle",
    offlineTitle: "İnternet bağlantısı yok",
    offlineText: "Dosyalarınız sunucuda kayıtlı. Bağlantı gelince sayfayı yenileyin — her şey yerinde olacak.",
    bannerTitle: "Konsiliér AI uygulaması",
    bannerText: "Süre bildirimleri ve belgeleriniz telefonunuzda",
    // one line where the browser has no install dialog; {share} is drawn as the Share icon, {site} is the host
    hint: {
      ios: "{share} simgesine dokunun ve “Ana Ekrana Ekle”yi seçin",
      ios26: "“•••”, ardından {share} ve “Ana Ekrana Ekle”ye dokunun",
      iosInApp: "Uygulama burada yüklenemez — siteyi tek dokunuşla Safari'de açın",
      androidInApp: "Uygulama burada yüklenemez — siteyi tek dokunuşla Chrome'da açın",
      macSafari: "Dosya → “Dock'a Ekle”",
      menu: "Tarayıcı menüsü ⋮ → “Uygulamayı yükle”. Zaten yüklüyse adres çubuğundaki “Uygulamada aç”a tıklayın.",
      other: "Yüklemek için {site} adresini Chrome veya Edge'de açın",
    },
  },
  push: {
    title: "Bu cihazdaki bildirimler",
    lead: "Süre hatırlatmaları, ödemeler ve hazır belgeler hemen gelir — site kapalıyken bile.",
    short: "Süreler ve belgeler hakkında bildirim alın",
    enable: "Bildirimleri aç",
    disable: "Kapat",
    on: "Bu cihazda bildirimler açık",
    denied: "Bildirimler tarayıcı ayarlarında engellenmiş. konsilier.com için izin verin ve “Bildirimleri aç” düğmesine yeniden dokunun.",
    ios: "iPhone ve iPad'de bildirimler yalnızca uygulamada çalışır: Safari'de “Paylaş” → “Ana Ekrana Ekle”ye dokunun, Konsiliér AI'ı ana ekrandan açın ve bildirimleri orada açın.",
    iosShort: "iPhone'da bildirimler ana ekrandaki uygulamaya gelir.",
    howTo: "Nasıl yüklenir",
    unsupported: "Bu tarayıcı bildirim gösteremiyor. Siteyi Chrome, Edge, Firefox veya Safari'de açın.",
  },
  share: {
    eyebrow: "Başka bir uygulamadan gelen dosyalar",
    title: "Hangi dosyanıza eklensin?",
    lead: "Bir dosya seçin: paylaştığınız belgeler bu dosyaya eklenir, Konsiliér AI onları okuyup gerekli bilgileri alır.",
    files: "Dosya sayısı: {n}",
    where: "Dosya",
    newCase: "Yeni dosya",
    noCases: "Burada henüz dosyanız yok.",
    signIn: "Dosyalarınızı görmek için giriş yapın",
    startCase: "Yeni dosya başlat",
    attach: "Dosyaya ekle",
    uploading: "Yükleniyor: {n} / {total}…",
    emptyTitle: "Dosya alınamadı",
    emptyText: "Dosyaları yeniden paylaşın: bir fotoğraf, PDF veya Word belgesi seçip “Paylaş” → Konsiliér AI'a dokunun.",
  },
  appPage: {
    title: "Konsiliér AI telefonunuzda",
    lead: "Tek dokunuşla ekranınızda kendi simgesi ve süre bildirimleri.",
    installed: "Uygulama bu cihazda zaten yüklü. Masaüstünden, Dock'tan veya adres çubuğundaki “Uygulamada aç” düğmesiyle açın.",
    qrAlt: "Uygulama sayfasının QR kodu",
    qrTitle: "Telefonunuzda açın",
    qrText: "Kamerayı koda tutun ve “Yükle”ye dokunun.",
  },
  helper: {
    photo: "Fotoğraf çek",
    attach: "Dosya ekle",
    more: "Daha fazla örnek",
    examplesTitle: "Örnekler — kullanmak için dokunun",
    suggestTitle: "Buna mı benziyor?",
    servicesTitle: "Nereye başvurulur — neyi nereye sunacağınızı biz söyleriz",
    eotinish: "Devlet kurumlarına başvuru ve şikâyetler",
    sud: "Mahkemeye dava ve talepler",
    egov: "Belgeler ve kamu hizmetleri",
    step1: "Sorunu anlatın",
    step2: "Soruları yanıtlayın ve belgeleri ekleyin",
    step3: "Belgeyi indirin ve talimata göre başvurun",
    planTitle: "Önerilen çözüm",
    planDoc: "Hazırlayacağımız belge",
    planTo: "Kime",
    planVia: "Nasıl başvurulur",
    planAttach: "Hazırlayın ve ekleyin",
    planSelf: "Kendiniz başvurursunuz — adım adım talimat veririz",
    planLawyer: "Belgeyi başvurudan önce avukat kontrol eder",
    planUpload: "Belge yükle",
    examples: { 1: "Kusurlu ürünün parasını geri almak", 2: "Ödenmeyen maaşı tahsil etmek", 3: "Trafik cezasına itiraz etmek", 4: "Kiralık dairenin depozitosunu geri almak", 5: "Kartımdan izinsiz çekilen parayı geri almak", 6: "Çocuk yardımına nasıl başvurulur", 7: "İşletmeyi büyütmek için hibe nasıl alınır", 8: "Eğitim hibesi veya burs nasıl alınır", 9: "İhale teklifi nasıl hazırlanır", 10: "Nafaka için nasıl başvurulur", 11: "Teslim edilmeyen siparişin parasını geri almak", 12: "İşten ayrılırken son ödemeyi almak" },
    exampleCount: "12",
    doc_download: "İndir",
    doc_print: "Yazdır",
    doc_save: "Kaydet",
    doc_send: "Gönder",
    doc_sign: "E-imza ile imzala",
    doc_signUnavailable: "Sitede e-imza şu anda kullanılamıyor. Belgeyi başvuru sırasında doğrudan portalda (eOtinish, Yargı Kabineti) e-imzayla ya da elle imzalayabilirsiniz.",
    doc_signed: "E-imza ile imzalandı",
    doc_fmtPdf: "PDF — yazdırmak ve sunmak için",
    doc_fmtWord: "Word — düzenlemek için",
    doc_toWhatsapp: "WhatsApp",
    doc_toTelegram: "Telegram",
    doc_toMail: "E-posta",
    doc_toOther: "Başka uygulama",
    doc_fileReady: "Dosya indirildi — açılan pencerede ekleyin.",
    doc_savedTo: "Kaydedildi",
  },
  cta: {
    pickSituation: "Durum seç",
    draftDocument: "Belge hazırla",
    title: "Sorunuzla başlayın.",
    lead: "Durumu kendi sözlerinizle anlatın — yolu gösterip ilk belgeyi hazırlayalım.",
    start: "Durumu anlat",
    lawyer: "Avukat bul",
    more: "Ayrıntılar",
    next: "İleri",
    startCase: "Dosya başlat",
    complain: "Şikâyet et",
    join: "Avukat mısınız? Katılın",
    caseLawyerTitle: "Avukat yardımı mı gerekiyor?",
    caseLawyerText: "Bir avukat belgelerinizi inceleyebilir veya dosyanın tamamını üstlenebilir.",
    lawyersLead: "Durumu anlatın — belgeleri hazırlarız, gerektiğinde bir avukatı dahil ederiz.",
  },
  app: {
    toEnd: "Son mesaja git",
    tabs: { home: "Ana sayfa", chat: "Sohbet", cases: "Dosyalar", documents: "Belgeler", profile: "Profil" },
    signIn: "Giriş yap",
    newQuestion: "Yeni soru",
    toSite: "Siteye dön",
    recent: "Son dosyalar",
    docs: { title: "Belgeler", lead: "Dosyalarınızdaki tüm belge taslakları tek yerde.", empty: "Henüz belge yok", emptyHint: "Durumunuzu sohbette anlatın — Konsiliér AI bilgileri toplayıp bir belge taslağı hazırlar.", create: "Belge hazırla", search: "Başlığa göre ara", draft: "Taslak", ready: "Sunulmaya hazır", submitted: "Sunuldu", open: "Dosyayı aç", count: "Belgeler: {n}" },
    digits: "{n} / {total}",
    back: "Geri",
    more: "Daha fazla",
    close: "Kapat",
    cancel: "İptal",
    roadmap: "Yol haritası",
    facts: "Dosya bilgileri",
    documents: "Belgeler",
    lawyer: "Avukat",
    gov: "eGov belgeleri",
    law: "Kanun hakkında soru",
    about: "Dosya ve hizmet hakkında",
    account: "Hesabım",
    home: "Ana sayfa",
    photo: "Fotoğraf çek",
    file: "Dosya seç",
    today: "Bugün",
    yesterday: "Dün",
    noFacts: "Henüz bilgi yok — sohbetteki soruları yanıtlayın.",
    chat: "Sohbet",
    hint: {
      digits: "Yalnızca rakam: {n} hane.",
      date: "Takvimden tarihi seçin veya “Bugün” / “Dün” düğmesine dokunun.",
      money: "Yalnızca rakam — boşlukları biz ekleriz.",
      number: "Bir sayı girin.",
      phone: "Telefon numarası, ör. +7 700 000 00 00.",
      email: "E-posta adresi.",
      text: "Kısa bir yanıt.",
    },
  },
  chat: {
    more: "Ayrıntılar",
    notice: "Bu sohbette hukuki sorular için yapay zekâ asistanı Konsiliér AI ile yazışıyorsunuz. İsimler ve belge numaraları, yapay zekâ işlemeden önce gizlenir.",
    subtitle: "Hukuki sorular için yapay zekâ asistanı",
    greet: {"morning": "Günaydın!", "day": "İyi günler!", "evening": "İyi akşamlar!", "night": "İyi geceler!"},
    cancel: "Kaydı iptal et",
    stop: "Yanıtı durdur",
    copied: "Kopyalandı",
    copy: "Kopyala",
    share: "Paylaş",
    voiceTitle: "Yanıtları sesli oku",
    placeholderNext: "Mesaj",
    brand: "Konsiliér AI",
    freeShort: "Sohbet ücretsiz",
    eyebrow: "Ücretsiz sohbet",
    title: "Nasıl yardımcı olabilirim?",
    lead: "Yazın ya da sesle anlatın, fotoğraf ve belge ekleyin.",
    placeholder: "Ne olduğunu anlatın…",
    send: "Gönder",
    attach: "Dosya ekle",
    remove: "Dosyayı kaldır",
    mic: "Sesle anlat",
    micStop: "Kaydı durdur",
    listening: "Konuşun — dinliyorum…",
    transcribing: "Konuşma metne çevriliyor…",
    recordingLimit: "Kayıt en fazla 2 dakika, ardından metin kutuya gelir",
    speak: "Sesli oku",
    stopSpeak: "Durdur",
    voiceOn: "Sesli yanıtlar: açık",
    voiceOff: "Sesli yanıtlar: kapalı",
    thinking: "Düşünüyorum…",
    lookingUp: "Kanunun resmî metnine bakıyorum…",
    remaining: "24 saatlik {limit} ücretsiz mesaj hakkınızdan {n} mesaj kaldı",
    interrupted: "Yanıt yarıda kesildi — yukarıda yalnızca başlangıcı gösteriliyor.",
    retry: "Tekrar dene",
    article: "Madde {n}",
    doc: "Belge hazırla",
    docPrice: "1.990 ₸'den itibaren",
    lawyer: "Hukukçu veya avukat",
    lawyerPrice: "ücretli ve ücretsiz",
    free: "Sohbet ücretsizdir. Konsiliér AI bir yapay zekâ asistanıdır, bir avukatın yerini tutmaz.",
    open: "Sohbeti aç",
    errors: {
      agent_unavailable: "Yapay zekâ sohbeti şu anda kullanılamıyor. Daha sonra deneyin veya belgeyi adım adım hazırlayın.",
      agent_failed: "Yapay zekâ asistanı yanıt veremedi. Bir dakika sonra tekrar deneyin.",
      too_many_messages: "Sınıra ulaşıldı: 24 saatte {limit} ücretsiz mesaj. Yenileri, gönderdiklerinizden 24 saat sonra kullanılabilir olur — belgeyi ise şimdi adım adım hazırlayabilirsiniz.",
      busy: "Şu anda yoğunluk var, lütfen bir dakika sonra tekrar deneyin.",
      mic_denied: "Mikrofona erişim yok. Tarayıcı veya telefon ayarlarından izin verip tekrar deneyin.",
      no_mic: "Mikrofon bulunamadı. Bir mikrofon bağlayın ya da yazarak anlatın.",
      no_speech: "Konuşma duyulmadı. Mikrofona daha yakın konuşup tekrar deneyin.",
      mic_failed: "Kayıt başlatılamadı. Tekrar deneyin ya da yazarak anlatın.",
      transcribe_unavailable: "Sesli giriş şu anda kullanılamıyor. Lütfen yazarak anlatın.",
      transcribe_busy: "Şu anda yoğunluk var, konuşma metne çevrilemedi. Bir dakika sonra tekrar deneyin.",
      transcribe_failed: "Kayıt metne çevrilemedi. Tekrar deneyin.",
      transcribe_network: "Kayıt gönderilemedi — internet bağlantınızı kontrol edip tekrar deneyin.",
      too_many_transcriptions: "Bu saat içinde çok fazla sesli kayıt yapıldı. Biraz bekleyin ya da yazarak anlatın.",
      audio_too_large: "Kayıt çok uzun. Tek seferde en fazla 2 dakika konuşun.",
    },
  },
  home: {
    placeholder: "Ne olduğunu anlatın…",
    eyebrow: "Konsiliér AI",
    title: "Hukuki sorular için yapay zekâ asistanı",
    sub: "Haklarınızı yasalara dayanarak açıklarım; ihtarname, şikâyet ya da dava dilekçenizi hazırlarım.",
    promise1: "Resmî yasa metinlerinden ilgili maddeleri bulur",
    promise2: "Yasaya uygun ihtarname, şikâyet veya dilekçe hazırlar",
    promise3: "Belgeyi nereye ve nasıl sunacağınızı gösterir",
    promise4: "Süreleri takip eder, bir sonraki adımı önerir",
    describe: "Ne olduğunu anlatın",
    cta: "Soru sor",
    privacy: "İsimleri ve belge numaralarını yapay zekâ işlemeden önce etiketlerle değiştiriyoruz. Belgeler sizin adınıza sunulur.",
    mySituation: "Benim durumum",
    mySituationText: "Listede yok mu? Kendi sözlerinizle anlatın — ne yapmanız gerektiğini söyleyelim.",
    situationsEyebrow: "Sık karşılaşılan durumlar",
    situationsTitle: "Nereden başlayalım?",
    situationsLead: "Hangi hukuk dalı olduğunu bilmeniz gerekmez. Benzer bir durumu seçin ya da kendinizinkini anlatın.",
    pathEyebrow: "Yol haritası",
    pathTitle: "Dosyanız nasıl ilerler",
    pathLead: "Her adımda kimin kontrol ettiği ve avukatın ne zaman devreye girdiği görünür.",
    levelsEyebrow: "Neler yapabildiğimiz konusunda şeffafız",
    levelsTitle: "Üç seviye: dosyanızın hangisinde olduğunu hep bilirsiniz",
    levelsLead: "Tüm yol boyunca yanınızdayız: belge, başvuru, süre takibi ve gerektiğinde avukat.",
    howLink: "Nasıl çalıştığını öğrenin",
    coverageTitle: "Kazakistan'da hizmet veriyoruz. BDT ve Orta Doğu yakında",
    coverageLead: "Özbekistan, Kırgızistan, Azerbaycan, Türkiye, BAE, Suudi Arabistan ve diğer ülkeler açılış planında.",
    coverageCta: "Tüm hizmetler",
    stepsTitle: "Sorudan bir sonraki adıma",
    steps: {
      share: "Bunun uygun olacağı meslektaşlarınız var mı? Onlara bağlantıyı gönderin.",
      s1t: "Ne olduğunu anlatın",
      s1d: "Yazarak veya sesli. Fiş, sözleşme ve yazışma fotoğrafları ekleyebilirsiniz.",
      s2t: "Yanıtınızı ücretsiz alın",
      s2d: "Haklarınızı ve sonraki adımları, kanunların resmî metinlerine bağlantılarla anlatırız.",
      s3t: "Belgeyi kendiniz sunun",
      s3d: "Yapay zekâ ihtarname, şikâyet veya dava dilekçesini hazırlar, nereye sunacağınızı gösterir ve süreleri hatırlatır. Dosyanız bir avukat gerektiriyorsa Konsiliér AI bunu açıkça söyler.",
    },
    priceTitle: "Ücretler",
    price: {
      people: "Bireyler için",
      business: "İşletmeler için",
      start: "Başla",
      buy: "Abone ol",
      perCase: "dosya başına",
      perMonth: "aylık",
      chatT: "Yapay zekâ sohbeti",
      chatP: "Ücretsiz",
      chatD: "Yapay zekâ sohbeti: haklarınız ve eylem planı, yazarak veya sesli.",
      docT: "Tek belge",
      docP: "1.990 ₸",
      docD: "İhtarname, şikâyet, dilekçe veya dava dilekçesi ve nereye, nasıl sunulacağına dair talimat.",
      caseT: "Anahtar teslim dosya",
      caseP: "9.990 ₸",
      caseD: "Bir dosyada sonuca kadar tüm belgeler: ihtarname, şikâyet, dava dilekçesi. Süre takibi ve ret ya da yanıt gelmemesi hâlinde bir sonraki adım.",
      bizT: "İşletme",
      bizP: "29.990 ₸",
      bizD: "Şahıs şirketleri ve küçük işletmeler için: ayda 20 belgeye kadar — karşı tarafa ihtarnameler, alacaklar, denetimler.",
      bizproT: "İşletme Pro",
      bizproP: "59.990 ₸",
      bizproD: "Şirketler için: ayda 60 belgeye kadar — sürekli uyuşmazlıklar için.",
    },
    trustTitle: "Neden bize güvenebilirsiniz",
    trust: {
      t1: "Yalnızca kanunların resmî metinlerine atıf yaparız (Adilet hukuki bilgi sistemi).",
      t2: "Adlar, kimlik numaraları ve telefonlar yapay zekâ işlemeden önce etiketlerle değiştirilir.",
      t3: "Belgeyi kendi adınıza kendiniz sunarsınız — kararınız olmadan hiçbir şey göndermeyiz.",
    },
    more: "Ayrıntılar",
  },
  training: { title: "Konsiliér AI'ı daha akıllı hâle getirmemize yardım edin", text: "Bu dosyanın Konsiliér AI'ın yapay zekâsını eğitmek için kullanılmasına izin veriyorum — adım, kimlik numaram, telefonum ve adresim olmadan. Bu izni istediğim zaman geri alabilirim." },
  situations: {
    cheated: { label: "Alışverişte mağdur oldum", hint: "Ürün, hizmet, pazaryeri, para iadesi.", placeholder: "Ne aldınız, kimden, ne zaman, kaça ve ne ters gitti" , ex1: "Bir hafta sonra bozulan telefonun parasını geri almak", ex2: "Teslim edilmeyen siparişin parasını geri almak", ex3: "Kalitesiz tamiratı yeniden yaptırmak", ex4: "Kullanılmayan kurs derslerinin parasını geri almak" },
    fired: { label: "İşten çıkarıldım veya maaş ödenmiyor", hint: "İşten çıkarma, maaş alacağı, ayrımcılık.", placeholder: "Nerede çalışıyorsunuz, ne oldu ve ne zaman, ne kadar borçlular" , ex1: "Üç aydır ödenmeyen maaşı tahsil etmek", ex2: "İşten çıkarılınca son ödemeyi almak", ex3: "Baskıyla imzalatılan istifaya itiraz etmek", ex4: "Ayrılırken izin ve fazla mesai ücretini almak" },
    family: { label: "Boşanma ve çocuklar", hint: "Boşanma, nafaka, velayet, mal paylaşımı.", placeholder: "Kısaca: ne oluyor ve ne elde etmek istiyorsunuz" , ex1: "Nafaka için nasıl başvurulur", ex2: "Mahkeme yoluyla boşanma nasıl yapılır", ex3: "Çocukla kişisel ilişki düzeni nasıl belirlenir", ex4: "Evlilikte edinilen mallar nasıl paylaşılır" },
    fine: { label: "Para cezası", hint: "Para cezasına veya karara itiraz.", placeholder: "Ceza ne için, kim yazdı, ne zaman ve neden katılmıyorsunuz" , ex1: "İşlemediğim bir ihlal için verilen cezaya itiraz etmek", ex2: "Aracı başkası kullanırken gelen kamera cezasına itiraz", ex3: "Tabela yokken aracın çekilmesine itiraz etmek", ex4: "Apartman bahçesine park etme cezasına itiraz etmek" },
    crime: { label: "Bana karşı suç işlendi", hint: "Hırsızlık, dolandırıcılık, darp. Yalnızca olgular: ne, nerede, ne zaman.", placeholder: "Ne oldu, nerede ve ne zaman, kim gördü, zarar ne" , ex1: "Polise nasıl şikâyette bulunulur", ex2: "Kartımdan dolandırıcılıkla çekilen para nasıl geri alınır", ex3: "Polis şikâyeti almazsa ne yapmalı", ex4: "İlandaki satıcıya yapılan ön ödeme nasıl geri alınır" },
    stateBody: { label: "Kamu kurumuyla uyuşmazlık", hint: "Ret, işlem yapmama, başvuruya cevap verilmemesi.", placeholder: "Hangi kurum, ne talep ettiniz ve ne cevap verdiler" , ex1: "Kamu kurumundan başvuruma yanıt almak", ex2: "Akimliğin arsa talebini reddetmesine itiraz etmek", ex3: "Yardım başvurusunun reddine itiraz etmek", ex4: "Kamu Hizmet Merkezinin (CON) vermediği belgeyi almak" },
    bank: { label: "Banka, kredi, tahsilat şirketleri", hint: "Adınıza çekilen kredi, bankayla uyuşmazlık, tahsilatçı baskısı.", placeholder: "Hangi banka veya finans şirketi, ne oldu, hangi tutarlar" , ex1: "Haberim olmadan çekilen mikrokrediye itiraz etmek", ex2: "Başkasının borcu için gelen tahsilat aramalarını durdurmak", ex3: "Kartımdan izinsiz çekilen parayı geri almak", ex4: "Kredi ödemesi nasıl ertelenir" },
    business: { label: "Ticari uyuşmazlık", hint: "Karşı tarafın borcu, sözleşme ihlali.", placeholder: "Sözleşme kiminle, ne ihlal edildi, tutar ne" , ex1: "Teslim edilen mal için alacağı tahsil etmek", ex2: "Yerine getirilmeyen tedarik sözleşmesinin parasını geri almak", ex3: "Eksik teslimat için tedarikçiye ihtarname hazırlamak", ex4: "Ticari kira sözleşmesinin erken feshine itiraz etmek" },
    inheritance: { label: "Miras", hint: "Mirasın kabulü, mirasçılar arası uyuşmazlık.", placeholder: "Mirası ve sorunuzu kısaca anlatın" , ex1: "Yasal miras işlemleri nasıl yapılır", ex2: "Mirası kabul süresi kaçırılırsa ne yapılır", ex3: "Miras mirasçılar arasında nasıl paylaşılır", ex4: "Noter veraset belgesi vermezse ne yapmalı" },
    housing: { label: "Konut ve komşular", hint: "Kira, elektrik-su-doğalgaz faturaları, komşular.", placeholder: "Nasıl bir konut, uyuşmazlık kiminle, ne oldu" , ex1: "Ev sahibinden depozitoyu geri almak", ex2: "Komşuların su bastırdığı dairenin zararını tahsil etmek", ex3: "Verilmeyen hizmetler için yönetim faturalarına itiraz", ex4: "Müteahhit teslimi geciktirirse ne yapmalı" },
    benefits: { label: "Yardımlar ve ödemeler", hint: "Çocuk ve engellilik yardımı, sosyal yardım, reddedilen ödeme.", placeholder: "Hangi ödemeye başvurmak istiyorsunuz ya da ne reddedildi, kim tarafından ve ne zaman", ex1: "Doğum yardımına nasıl başvurulur", ex2: "Çocuk bakım ödeneği nasıl alınır", ex3: "Hedefli sosyal yardıma nasıl başvurulur", ex4: "Yardım başvurusunun reddine itiraz etmek" },
    grants: { label: "İşletmeler için hibe ve finansman", hint: "İş fikrine hibe, Damu, devlet desteği: belgeler ve iş planı.", placeholder: "İşiniz veya fikriniz, paranın ne için gerektiği, hangi program", ex1: "Yeni bir iş fikri için devlet hibesine nasıl başvurulur", ex2: "Şahıs işletmem için geri ödemesiz finansman istiyorum, nereden başlamalıyım", ex3: "Devlet hibesi için nasıl bir iş planı gerekir", ex4: "Damu fonu hibesi için hangi belgeler gerekir" },
    study: { label: "Eğitim: hibe ve burs", hint: "UNT puanıyla devlet hibesi, Bolaşak, burslar, üniversiteye giriş.", placeholder: "Nereye başvuruyorsunuz, puanlarınız ve belgeleriniz", ex1: "UNT sonucuyla devlet eğitim hibesi nasıl alınır", ex2: "Eğitim hibesi yarışması için hangi belgeler gerekir", ex3: "Yurt dışında okumak için Bolaşak bursuna nasıl başvurulur", ex4: "Yurt dışında üniversiteye girmek istiyorum, niyet mektubu ve özgeçmiş gerekiyor" },
    tenders: { label: "İhaleler ve kamu alımları", hint: "İhale teklifi, belgeler, sonuçlara itiraz.", placeholder: "Alım numarası, ne alındığı ve teklif mi itiraz mı gerektiği", ex1: "goszakup.gov.kz'de ihale teklifi nasıl hazırlanır", ex2: "Bir şirketin kamu alımlarına katılması için hangi belgeler gerekir", ex3: "İhale nasıl kazanılır: ihale belgelerinde neler kontrol edilmeli", ex4: "İhale teklifimiz reddedildi, sonuçlara itiraz etmek istiyoruz" },
  },
  inbox: { title: "Bildirimler", titleUnread: "Bildirimler, {n} yeni", empty: "Henüz bildirim yok. Süre hatırlatmaları, ödemeler ve hazır belgeler burada görünecek.", readAll: "Tümünü okundu işaretle", markRead: "Okundu", openCase: "Dosyayı aç", openSupport: "Talebi aç", new: "Yeni" },
  board: {
    intake: "Başvuru", qualified: "Bilgiler toplandı", action_ready: "Belge hazır", submitted: "Sunuldu, cevap bekleniyor",
    escalated: "Üst makama itiraz", handed_to_lawyer: "Avukatta", resolved: "Çözüldü",
    empty: "Boş", stepOf: "Aşama {n} / {total}",
    attention: { hold: "İncelemede", ack: "Onay gerekli", expired: "Cevap süresi doldu", approval: "Avukat kontrolü bekleniyor", chooseForum: "Muhatabı seçin" },
    deadline: { left: "{n} gün kaldı", today: "Bugün son gün", expired: "Süre doldu" },
  },
  ack: {
    false_report: { title: "Bilerek gerçeğe aykırı ihbarın sorumluluğu", button: "Anladım ve onaylıyorum", text: "Bilerek gerçeğe aykırı ihbar ve şikâyette bulunmanın cezai sorumluluğu vardır. Yalnızca bildiğiniz olguları anlatın." },
    special_category: { title: "Özel nitelikli verilerin işlenmesine onay", button: "Onay veriyorum", text: "Dosyada sağlık, din veya sabıka bilgileri olabilir. En az veriyi saklar ve yalnızca belgeniz için kullanırız." },
  },
  forum: {
    chooseTitle: "Nereye başvurulur",
    chooseLead: "Muhatabı seçin. Liste yalnızca bu ülkenin kurum sicilinden; farklar aşağıda gösteriliyor.",
    type: { court: "Mahkeme", prosecutor: "Savcılık", police: "Polis", regulator: "Düzenleyici kurum", ministry: "Bakanlık",
      ombudsman: "Ombudsman", local_authority: "Yerel yönetim", arbitration: "Tahkim", mediation: "Arabuluculuk",
      private_org: "Kuruluş" },
    effect: { binding: "Karar bağlayıcı", advisory: "Tavsiye niteliğinde karar", none: "Hukuki etkisi yok" },
    verified: "Avukat onaylı", unverified: "Bilgileri avukat netleştirecek", deadlineByLawyer: "Süreyi avukat netleştirecek",
    channels: "Nasıl başvurulur", channel: { portal: "çevrimiçi portal", email: "e-posta", post: "posta", in_person: "şahsen", whatsapp: "WhatsApp", telegram: "Telegram" },
    choose: "Seç",
  },
  common: { loading: "Yükleniyor…", sending: "Gönderiliyor…" },
  roadmap: {
    title: "Dosyanın yol haritası",
    best: "En iyi durum",
    worst: "Tüm adımlar gerekirse",
    openEnded: "ardından avukatla çalışma, süreler anlaşmaya göre",
    done: "Tamamlandı",
    current: "Şimdi",
    upcoming: "Sonra",
    skipped: "Gerek kalmadı",
    ifNeeded: "gerekirse",
    due: "süre",
    estimated: "tahmini",
    finished: "tamamlandı",
    todoNorm: "süreyi avukat netleştiriyor",
  },
  trust: {
    title: "Dolandırıcılığa ve boş vaatlere karşı nasıl koruyoruz",
    verifiedTitle: "Avukatları nasıl kontrol ediyoruz",
    verified: "Avukat veya hukuk danışmanı statüsü sicillerden kontrol edilir, kimlik e-imza ile doğrulanır. Doğrulama yoksa müvekkillere erişim de yok.",
    escrowTitle: "Aşamalı ödeme, para güvencede",
    escrow: "Her şeyi peşin ödemezsiniz. Tutar ödeme ortağında bloke edilir ve avukata ancak aşama tamamlanınca aktarılır: ihtarname gönderildi, cevap alındı, dava açıldı.",
    ratingTitle: "Kanıtlanmış sonuçlara dayalı puan",
    rating: "Puan platformdaki gerçek dosyalara göre hesaplanır: zorluğa göre düzeltilmiş kazanılan dosyalar, geri alınan para, sürelere uyum. Yorumlar yalnızca anlaşmadan sonra.",
    roadmapTitle: "Dosyanızın nerede olduğunu görürsünüz",
    roadmap: "Yol haritası: ne yapıldı, şimdi ne var, sonraki adımlar ne ve karar ne zaman beklenir; en iyi ve en kötü durum.",
    soon: "Avukatla güvenli işlem geliştiriliyor",
    more: "Ayrıntılar",
    less: "Daha az göster",
    now: "Şimdi",
    verifiedMore: "Avukat: baroya kayıt ve geçerli ruhsat.\nHukuk danışmanı: hukuk danışmanları odasına üyelik.\nKimlik e-imza ile doğrulanır; başkasının adıyla çalışılamaz.\nRuhsat iptal edilirse veya odadan çıkarılırsa profil gizlenir.",
    verifiedNow: "Avukat başvurularını şu an ekip belgelere göre elle kontrol ediyor. Sicillerle otomatik kontrol ve e-imza ile giriş geliştiriliyor.",
    verifiedLink: "Platform avukatı nasıl olunur",
    escrowMore: "Ücret ve aşamalar iş başlamadan sözleşmede belirlenir.\nAşama ücreti avukatta değil, ödeme ortağında bloke edilir.\nAvukat, aşama onaylanınca ödemeyi alır: belge sunuldu, cevap alındı.\nAşama yapılmazsa o aşamanın parası size iade edilir.\nAnlaşmazlıkları platform dosyadaki belgelere göre inceler.",
    escrowNow: "Özellik geliştiriliyor: Kazakistan'da ödeme ortağı seçiyoruz. Açılışa kadar avukatlara dosyanın tamamı için peşin ödeme yapmayın.",
    ratingMore: "Sonuç, avukatın beyanıyla değil, dosya platformda kapatılırken kaydedilir.\nSonuç aynı kategorinin ortalamasıyla karşılaştırılır; kolay dosyalar puanı şişirmez.\nBileşim: başarı %45, sürelere uyum %20, geri alınan para %20, yorumlar %15.\nYeni avukatların puanı 30+ dosyaya ulaşana kadar platform ortalamasına çekilir.\nYorum yalnızca gerçek bir anlaşmadan sonra bırakılabilir.",
    ratingNow: "Şimdilik demo profillerle örnek gösteriliyor: gerçek puan, avukatlar platformda ilk dosyaları kapattığında görünecek.",
    ratingLink: "Örnek puanı gör",
    roadmapMore: "Dosyanın her adımı: ihtarname, cevap bekleme, düzenleyici kuruma şikâyet, dava.\nHer adım için yasal süre ve bitiş tarihi.\nİki tahmin: en iyi (ihtarnameden sonra çözüldü) ve tüm adımlar gerekirse.\nHiçbir süreyi kaçırmamanız için hatırlatırız.",
    roadmapNow: "Şu an çalışıyor: yol haritası her dosyada durumu anlattıktan hemen sonra açılır.",
    roadmapLink: "Dosya başlat",
    cta: "Örnek puanı gör",
    joinLawyer: "Avukat mısınız? Katılın",
  },
  request: {
    back: "Avukatlar ve hukukçular",
    title: "Avukata başvuru",
    lead: "Durumu anlatın ve iletişim bilgilerinizi bırakın. Dosyayı kaydeder, belgelerle birlikte bir avukata aktarırız.",
    story: "Ne oldu",
    contacts: "İletişim bilgileriniz",
    name: "Ad soyad",
    phone: "Telefon",
    email: "E-posta (isteğe bağlı)",
    consent: "Konsiliér AI'ın dosyayı bir avukata aktarabilmesi için kişisel verilerimin işlenmesine onay veriyor ve şunu kabul ediyorum:",
    submit: "Başvuruyu gönder",
    note: "Belirli bir avukattan randevu alma özelliği, ödeme ortağı üzerinden ödemeyle birlikte açılacak. Şimdilik katalogdan ilgili alanda bir avukat seçer, size haber veririz.",
    doneTitle: "Başvuru kaydedildi",
    doneText: "Dosya oluşturuldu, iletişim bilgileriniz kaydedildi. Dosya bir avukata aktarıldığında sizinle iletişime geçeceğiz.",
    proceed: "Dosyayı tamamla",
    continueHint: "Birkaç soruyu yanıtlayın ve belgeleri ekleyin — avukat eksiksiz bir dosya alır ve hemen ücret söyleyebilir.",
  },
  lawyers: {
    filter: "Göster",
    all: "Tüm avukatlar",
    freeOnly: "Ücretsiz",
    freeNote: "İnsan hakları kuruluşları ve pro bono avukatlar ücretsiz yardım eder. Bazı konularda (nafaka, emeklilik ve yardımlar vb.) devlet güvenceli ücretsiz hukuki yardım barolar ve hukuk danışmanları odaları aracılığıyla da verilir.",
    freeNone: "Dizinde henüz ücretsiz avukat yok.",
    title: "Avukatlar ve hukukçular",
    subtitle: "Puan reklama değil, platformdaki kanıtlanmış sonuçlara dayanır.",
    score: "Puan",
    confidence: { low: "az dosya", medium: "orta örneklem", high: "geniş örneklem" },
    vsBaseline: "platform ortalamasına göre",
    cases: "platformdaki dosya",
    recovered: "geri alınan para",
    onTime: "zamanında aşama",
    reviews: "anlaşma sonrası yorumlar",
    from: "başlangıç",
    proBono: "ücretsiz (pro bono)",
    response: "ortalama yanıt süresi",
    hours: "sa",
    years: "yıl deneyim",
    verifiedLicense: "Ruhsat doğrulandı",
    verifiedId: "Kimlik doğrulandı",
    success: "başarı",
    platform: "ortalama",
    methodTitle: "Puan nasıl hesaplanır",
    method1: "Yalnızca platformdan geçen dosyalar: sonuç avukatın beyanıyla değil, dosya kapatılırken kaydedilir.",
    method2: "Sonuç aynı kategorideki dosyaların ortalamasıyla karşılaştırılır; kolay dosya seçmek puanı yükseltmez.",
    method3: "Küçük örneklem ortalamaya çekilir: 3'te 3 galibiyet, 220'de 180'i geçemez.",
    method4: "Ağırlık: başarı %45, aşama sürelerine uyum %20, geri alınan para oranı %20, anlaşma sonrası yorumlar %15.",
    choose: "Başvur",
    chooseSoon: "Avukata doğrudan başvuru henüz mümkün değil: bir dosya başlatın, toplanan belgelerle birlikte avukata aktaralım.",
    pp: "yüzde puan",
    mln: "mn",
    details: "Sonuçlar hakkında ayrıntılar",
    sample: "Örnek",
    newProfile: "Platformun yeni ortağı: puan, ilk tamamlanan dosyalardan sonra görünecek.",
  },
  landing: {
    promise: "Dosyanız: ilk belgeden sonuca kadar",
    sub: "Durumu kendi sözlerinizle anlatın. Konsiliér AI, Kazakistan yasalarına göre ihtarname veya şikâyet hazırlar, nereye başvuracağınızı söyler ve süreleri takip eder. Bu yetmezse platformun profesyonel avukatı dosyayı sonuna kadar götürür.",
    usp1: "Hazır belgeler: avukat aramadan, internetten şablon bulmadan",
    usp2: "Süreler kontrol altında: hatırlatır, sonraki adımı hazırlarız",
    usp3: "Bir insanın yardımı gerektiğinde platform kataloğundan avukat",
    startWeb: "Sitede başla",
    startTelegram: "Telegram'da aç",
    scenariosTitle: "Şu an neler yapabiliyoruz",
    howTitle: "Nasıl çalışır",
    how1: "Ne olduğunu anlatın",
    how2: "Kısa soruları yanıtlayın, fiş veya ekran görüntülerini yükleyin",
    how3: "Belgeyi ve başvuru talimatını alın",
    how4: "Cevap süresini takip eder, sonraki adımı öneririz",
    countryTitle: "Ülkeniz",
    countryLive: "Mevcut",
    countrySoon: "Yakında",
    waitlistTitle: "Bu ülkede henüz hizmet vermiyoruz",
    waitlistText: "İletişim bilgilerinizi bırakın, açıldığımızda yazalım.",
    waitlistContact: "E-posta veya Telegram",
    waitlistProblem: "Hangi sorunla karşılaştınız? (isteğe bağlı)",
    waitlistSend: "Açılışta haber ver",
    waitlistDone: "Teşekkürler! Açıldığımızda yazacağız.",
    price: "Ücret",
    disclaimer: "Belgeler sizin adınıza sunulur; her adımı siz kontrol edersiniz.",
  },
  start: {
    eyebrow: "Yeni dosya",
    country: "Ülke: Kazakistan.",
    otherCountry: "Başka ülke",
    busy: "Durumu inceliyoruz… Bu bir dakika sürebilir.",
    title: "Ne oldu?",
    placeholder: "Örneğin: 12.08.2026'da internet mağazasından 150 000 tengeye telefon aldım, bir hafta sonra bozuldu, parayı iade etmiyorlar",
    submit: "Devam et",
  },
  case: {
    back: "Tüm dosyalar",
    untitled: "Yeni dosya",
    holdTitle: "Dosya elle incelemede",
    draftTitle: "Önemli",
    lawyerTitle: "Dosya avukata iletiliyor",
    lawyerCta: "Katalogdaki avukatlar",
    lawyerText: "Açıklamanızı kaydettik ve dosyayı platform kataloğundaki bir avukata iletiyoruz.",
    uplTitle: "Biz kimiz",
    thinking: "Yanıt hazırlanıyor… Yavaş bağlantıda bir dakika sürebilir.",
    working: "İşleniyor… Sayfayı kapatmayın.",
    send: "Yanıtla",
    answerPlaceholder: "Yanıtınız",
    more: "Açıklamayı tamamla",
    morePlaceholder: "Tam olarak ne aldınız veya yaptırdınız, kimden, ne zaman, hangi tutara ve ne ters gitti",
    skip: "Atla",
    doneUploading: "Devam et",
    upload: "Dosya yükle",
    uploadHint: "Fotoğraf veya PDF, en fazla 15 MB",
    found: "Dosyada bulduklarımız",
    confirm: "Bilgiler doğru",
    nothingFound: "Dosya kaydedildi. Veriler otomatik okunamadı.",
    facts: "Dosya bilgileri",
    prepare: "Belgeyi hazırla",
    handoff: "Avukata ilet",
    awaitingApproval: "Belge kontrol ediliyor, genellikle 24 saat içinde. Hazır olur olmaz size bildirim göndereceğiz.",
    rejected: "Avukat belgeyi düzeltme için geri gönderdi.",
    download: "İndir",
    instructions: "Nasıl başvurulur",
    submitted: "Belge sunuldu",
    sendEmail: "Muhataba e-postayla gönder",
    deadline: "Cevap süresi",
    gotResponse: "Yanıt alındı",
    noResponse: "Yanıt gelmedi",
    responsePlaceholder: "Cevap metnini yapıştırın",
    responseSend: "Yanıtı incele",
    responseFile: "veya cevap dosyasını yükleyin",
    close: "Dosyayı sonuçlandır",
    closeWon: "Tamamen çözüldü",
    closePartial: "Kısmen çözüldü",
    closeLost: "Çözülmedi",
    amountRecovered: "Alınan tutar",
    outcome: "Sonuç",
    days: "gün",
    response: "Cevap",
    notifications: "Bildirimler",
    datePlaceholder: "GG.AA.YYYY",
    classes: { full: "Talep karşılandı", partial: "Kısmen karşılandı", refusal: "Ret", none: "Yanıt yok" },
    deadlineStatus: { active: "işliyor", met: "cevap alındı", expired: "doldu", cancelled: "iptal edildi" },
    submittedHint: "Belgeyi muhataba kendiniz teslim ettiğinizde veya gönderdiğinizde dokunun. O günden itibaren yanıt süresini sayar ve hatırlatırız.",
  },
  cases: {
    title: "Dosyalarım", empty: "Henüz dosyanız yok", open: "Aç", new: "Yeni dosya",
    lead: "Sorular, belgeler ve sonraki adımlar bir arada.",
    emptyHint: "Ne olduğunu anlatın — ücretsizdir.",
  },
  coverage: {
    eyebrow: "Hizmetler",
    title: "Nerede ve hangi konularda yardım ediyoruz",
    lead: "Ülkelere ve hukuk dallarına göre neler çalışıyor: hazır senaryolar nerede, belgeyi nerede size özel hazırlarız ve neler yakında geliyor.",
    legend: "Durumlar ne anlama gelir",
    liveLead: "Bu ülkedeki her hukuk dalının durumu.",
    plannedTitle: "Yakında: BDT ve Orta Doğu",
    plannedLead: "Bu ülkeler için yerel avukatlarla doğrulanmış veriler hazırlıyoruz. Şimdilik dosya kabul etmiyoruz.",
    waitlistTitle: "Açılışta bana haber ver",
    otherCountries: "Diğer ülkeler — yakında ({n})",
    sourcesTitle: "Resmî hukuk kaynakları",
    sourcesLead: "Yalnızca resmî devlet veri tabanlarına bağlantı veriyor ve onlardan alıntı yapıyoruz. Bağlantılar yeni sekmede açılır.",
    sourceKind: { legislation: "Mevzuat", case_law: "İçtihat", gazette: "Resmî gazete", registry: "Sicil" },
  },
  how: {
    eyebrow: "Nasıl çalışır",
    title: "Konsiliér AI — hukuki sorular için yapay zekâ asistanı",
    lead: "Sorununuzu anlatın — Konsiliér AI ülkenizin yasalarına göre gerekli belgeyi hazırlar, nereye başvuracağınızı söyler, süreleri takip eder ve gerektiğinde avukat bulmanıza yardım eder.",
    pathTitle: "Dosyanız nasıl ilerler",
    pathLead: "Belge → nereye başvurulur → cevap süresi → sonraki adım → avukat.",
    levelsTitle: "Üç yardım seviyesi",
    levelsLead: "Seviye otomatik belirlenir ve dosyada her zaman gösterilir.",
    level: {
      verified: { title: "Doğrulanmış senaryo", when: "Avukatın mevzuatı, süreleri ve muhatapları onayladığı sık durumlar için.", get: { 1: "Doğrulanmış şablona göre belge", 2: "Yasadan cevap süreleri ve hatırlatmalar", 3: "Önceden bilinen zincire göre sonraki adım" } },
      universal: { title: "Size özel belge", when: "Hazır senaryo yoksa, ama hukuk dalı belliyse ve sicilde uygun bir kurum varsa.", get: { 1: "Anlattıklarınıza ve delillerinize göre hazırlanan belge", 2: "Adım adım talimat: nereye, nasıl ve ne eklenecek; dava dilekçesi avukat kontrolünden sonra", 3: "Mevzuat ve süreler yalnızca verilerden; yoksa “avukat netleştirecek”" } },
      lawyer: { title: "Avukata devir", when: "Ceza davasında savunma tarafı, çocuklar, yüksek tutarlar, dolmak üzere olan süreler, belirsiz durum.", get: { 1: "Anlatımınıza göre dosya özeti", 2: "Platform kataloğundan bir avukat", 3: "Savunma belgelerini yalnızca avukat yazar" } },
    },
    rolesTitle: "Kim ne yapar",
    ai: {
      title: "Yapay zekâ",
      does: { 1: "Anlattıklarınızı anlar ve kısa sorular sorar", 2: "Olayların özetini yazar ve talepleri formüle eder", 3: "Muhatabın cevabını okur ve sonraki adımı önerir", 4: "Yalnızca anonimleştirilmiş verilerle çalışır" },
      neverTitle: "Yapay zekâ asla",
      never: { 1: "Mevzuat, madde ve süre uydurmaz", 2: "Başvurulacak kurumu seçmez", 3: "Din veya etnik köken belirlemez", 4: "Ceza davalarında savunma belgesi yazmaz" },
    },
    lawyer: {
      title: "Avukat",
      does: { 1: "Senaryoları onaylar: mevzuat, süreler, muhataplar", 2: "Mahkemeye verilecek dava ve şikâyet dilekçelerini sunulmadan önce kontrol eder", 3: "Karmaşık dosyaları yürütür ve sizi temsil eder", 4: "Kurum sicilinin hukuki doğruluğundan sorumludur" },
    },
    promiseTitle: "Ne vaat ediyoruz, ne yapmıyoruz",
    promiseLead: "Büyük vaatler yok: yalnızca bize bağlı olanlar.",
    promise: { title: "Vaat ediyoruz", 1: "Dosyanız için anlaşılır bir yol", 2: "Hazır belge ve başvuru talimatı", 3: "Süre takibi ve hatırlatmalar", 4: "Gerektiğinde avukat bulmada yardım" },
    dont: { title: "Yapmıyoruz", 1: "Mahkemede sizi kendimiz temsil etmiyoruz; bunu platform avukatları yapar", 2: "Avukat kontrolü olmadan mahkemeye dava açmıyoruz", 3: "Ceza davalarında savunma belgesi yazmıyoruz", 4: "Kurum, mevzuat, süre ve harç uydurmuyoruz" },
    safetyTitle: "Güvenlik",
    safety: {
      emergency: { title: "Acil durumlar", text: "Hayati tehlike, şiddet varsa veya bir çocuk tehlikedeyse önce ülkenin acil numaralarını gösteririz." },
      falseReport: { title: "Gerçeğe aykırı ihbar", text: "Suç ihbarlarında sorumluluk konusunda uyarır, yorum değil olguları anlatmanızı isteriz." },
      abuse: { title: "Kötüye kullanıma karşı koruma", text: "Tek bir kişiye yönelik toplu şikâyetler, taciz, şantaj ve iftira elle incelemeye gider." },
    },
  },
  ds: {
    title: "Tasarım sistemi", lead: "Konsiliér AI token'ları ve bileşenleri: telefonda ve bilgisayarda, beş dilde güven, açıklık ve erişilebilirlik.",
    colors: "Renkler", type: "Tipografi", buttons: "Düğmeler", badges: "Seviye rozetleri", notices: "Bildirimler",
    noticesLead: "Acil numaralar, gerçeğe aykırı ihbar, hizmetin hukuki statüsü ve “Önemli” küçük yazı değil, bileşendir.",
    uplSample: "Konsiliér AI, bir belge hazırlama hizmeti ve avukatlarla bağlantı kuran teknolojik bir aracıdır.",
    draftSample: "Bu belge, Konsiliér AI BT hizmeti tarafından verdiğiniz bilgilere göre hazırlanmıştır. Başvurmadan önce bilgileri kontrol edin.",
    forms: "Giriş alanları", progress: "Dosya aşamaları", board: "Dosya panosu", icons: "İkonlar",
  },
  errors: {
    title: "Bir şeyler ters gitti",
    saved: "Verileriniz kaydedildi, dosya kaybolmadı. Hata raporunu aldık. Devam etmek için sayfayı yenileyin.",
    translate: "Tarayıcıda otomatik sayfa çevirisi açıksa bu site için kapatın.",
    reload: "Sayfayı yenile",
    retry: "Tekrar dene",
  },
  admin: {
    lawyers: {
      lead: "Yalnızca e-imzayla yapılan ve lisans numarası kamu siciliyle karşılaştırılmış başvuruları onaylayın.",
      ecp: "E-imza",
      noEcp: "E-imza yok",
      license: "Lisans",
      nameDiffers: "Başvuruda başka bir ad var: {name}",
      verify: "Onayla",
      assign: "Avukata ilet",
      assignButton: "İlet",
      assigned: "{name} adlı avukata iletildi. İmzalanacak belgeler oluşturuldu.",
    },
    title: "Yönetim",
    tabs: { metrics: "Metrikler", lawyers: "Avukatlar", queue: "İnceleme kuyruğu", board: "Pano", holds: "İncelemede", forums: "Kurum sicili", demand: "Talep", errors: "Tarayıcı hataları" },
    forum: "Muhatap", hold: "Bekletildi", release: "İncelemeden çıkar",
    forums: {
      registry: "Sicil (paketten)", registryLead: "Doğruluk kaynağı depodaki YAML'dır. Değişiklikler canlıya yalnızca avukat kontrollü PR ile girer.",
      newDraft: "Yeni kayıt (taslak)", draftNote: "Taslak şemaya göre kontrol edilir, ancak dışa aktarılıp PR'da kabul edilene kadar canlıyı etkilemez.",
      save: "Taslağı kaydet", saved: "Taslak kaydedildi", drafts: "Taslaklar",
    },
    demand: { title: "Talep: hazır senaryosu olmayan durumlar", lead: "Hangi durumlar hazır senaryo olmadan geliyor: sonraki doğrulanmış senaryolar için adaylar.", country: "Ülke", dispute: "Uyuşmazlık türü", level: "Seviye", count: "Dosya" },
    token: "Yönetici token'ı",
    save: "Giriş yap",
    needsReview: "Yalnızca needs_review",
    pendingApproval: "Onay bekleyenler",
    all: "Tümü",
    approve: "Onayla",
    reject: "Geri gönder",
    note: "Avukat yorumu",
    preview: "Belge metni",
    audit: "Günlük",
    closeCase: "Dosyayı kapat",
    waitlist: "Bekleme listesi",
    tick: "Hatırlatmaları çalıştır",
  },
  account: {
    moreWaysTitle: "Diğer giriş yolları",
    otherWays: "Diğer yollar: e-imza, eGov",
    withEmail: "E-posta ile devam et",
    signInLead: "Tek adım: dosyalarınız ve belgeleriniz her cihazda.",
    signInOrUp: "Giriş yap veya kaydol",
    resendIn: "{n} sn sonra kodu tekrar gönder",
    resend: "Kodu tekrar gönder",
    bonus: "Arkadaş davetleriyle kazandığınız ücretsiz belge hakkı: {n}. Bu belgeler herhangi bir dosyanızda ödeme yapmadan hazırlanır.",
    eyebrow: "Hesap",
    title: "Profil",
    lead: "Dosyalarınız ve belgeleriniz her cihazda olsun diye giriş yapın.",
    verifiedTitle: "Doğrulandı",
    waysTitle: "Giriş yöntemleri",
    soon: "Yakında",
    done: "Tamam: giriş yaptınız. Dosyalarınız artık hesabınıza bağlı.",
    privacy: "Kimlik numaranızın kendisini değil, şifrelenmiş bir özetini saklıyor ve yalnızca son hanelerini gösteriyoruz. Kodlar 10 dakika geçerlidir.",
    kind: {
      email: "E-posta",
      phone: "Telefon",
      iin: "Kimlik no",
      google: "Google",
      apple: "Apple ID",
    },
    email: {
      title: "E-posta ile",
      hint: "E-postanıza altı haneli bir kod göndeririz.",
      label: "E-posta adresi",
      sent: "{target} adresine kod gönderdik. “Spam” klasörünü de kontrol edin.",
    },
    phone: {
      title: "Telefon numarası ile",
      hint: "Kodu SMS ile göndeririz.",
      label: "Telefon numarası",
      sent: "{target} numarasına SMS ile kod gönderdik.",
    },
    ecp: {
      title: "E-imza (NCALayer)",
      hint: "Bilgisayarınızdaki e-imza anahtarı: dosya veya kimlik kartı. Kimliğinizi teyit eder.",
      step1: "NCALayer'ı kurun ve çalıştırın:",
      step2: "Düğmeye basın ve kimlik doğrulama anahtarını seçin (AUTH_RSA veya AUTH_GOST).",
      step3: "NCALayer penceresinde anahtar şifresini girin.",
      button: "E-imzayla giriş yap",
      waiting: "NCALayer'da imza bekleniyor…",
      not_running: "NCALayer çalışmıyor. Başlatıp tekrar deneyin.",
      cancelled: "İmzalama iptal edildi.",
      failed: "NCALayer imzalayamadı. Tekrar deneyin.",
    },
    egov: {
      title: "eGov Mobile",
      hint: "Girişi eGov Mobile veya eGov Business uygulamasında QR kodla onaylayın.",
      button: "QR kodu göster",
      scan: "eGov Mobile'da “Сканер QR” (QR tarayıcı) bölümünü açın ve kamerayı koda tutun.",
      onPhone: "Telefondaysanız uygulamayı düğmeyle açın:",
      waiting: "Uygulamada onay bekleniyor…",
      expired: "Süre doldu. Yeni kod oluşturun.",
      qrAlt: "eGov Mobile ile giriş için QR kod",
    },
    google: {
      button: "Google ile giriş yap",
      failed: "Google ile giriş açılamadı. İnternet bağlantınızı kontrol edin veya daha sonra deneyin.",
    },
    apple: {
      button: "Apple ile giriş yap",
      failed: "Apple ile giriş yapılamadı. Lütfen tekrar deneyin.",
    },
    sendCode: "Kod al",
    codeLabel: "Mesajdaki kod",
    confirm: "Onayla",
    changeTarget: "Adresi değiştir",
    errors: {
      too_soon: "Kod az önce gönderildi. Bir dakika sonra tekrar isteyebilirsiniz.",
      rate_limited: "Çok fazla deneme. Bir saat sonra deneyin.",
      wrong_code: "Kod yanlış.",
      code_expired: "Kodun süresi doldu. Yenisini isteyin.",
      too_many_attempts: "Çok fazla hatalı deneme. Yeni kod isteyin.",
      invalid_email: "E-posta adresini kontrol edin.",
      invalid_phone: "Telefon numarasını kontrol edin, ör. +7 701 123 45 67.",
      method_unavailable: "Bu yöntem henüz kullanılamıyor.",
      send_failed: "Kod gönderilemedi. Daha sonra deneyin.",
      invalid_signature: "İmza doğrulanamadı.",
      certificate_invalid: "E-imza sertifikası geçersiz veya iptal edilmiş.",
      wrong_data: "Başka veriler imzalandı. Tekrar deneyin.",
      challenge_expired: "İmzalama süresi doldu. Tekrar deneyin.",
      verifier_unavailable: "İmza doğrulama geçici olarak kullanılamıyor. Daha sonra deneyin.",
      no_iin: "Sertifikada kimlik numarası yok.",
      invalid_token: "Giriş doğrulanamadı. Lütfen tekrar deneyin.",
      token_expired: "Giriş süresi doldu. Lütfen tekrar deneyin.",
      wrong_nonce: "Bu giriş geçerliliğini yitirdi. Sayfayı yenileyip tekrar deneyin.",
      email_not_verified: "Bu Google hesabının e-postası doğrulanmamış. Google'da doğrulayın veya başka bir yolla giriş yapın.",
      provider_unavailable: "Giriş hizmeti geçici olarak kullanılamıyor. Lütfen daha sonra deneyin.",
      foreign_challenge: "Giriş başka bir cihazda başlatıldı. Sayfayı yenileyip tekrar deneyin.",
    },
  },
  sign: {
    signedByLawyer: "Avukat e-imzayla imzaladı: {name} ({id})",
    lead: "Belgeyi e-imzanızla imzalayın — imzalı belgeye itiraz etmek daha zordur. İmzalı dosya e-postayla birlikte gider.",
    ncalayer: "E-imza ile imzala (NCALayer)",
    egov: "eGov Mobile'da imzala",
    signedBy: "E-imzayla imzalandı: {name} ({id})",
    download: "İmzalı dosyayı indir (.cms)",
    verifyHint: "İmza ezSigner'da veya sigex.kz'de doğrulanabilir.",
    errors: {
      use_sign_key: "Giriş anahtarını (AUTH) değil, imza anahtarını (RSA veya GOST) seçin.",
      signer_mismatch: "Belgeyi başvuru sahibi imzalamalı: anahtardaki kimlik numarası dosyadakiyle eşleşmiyor.",
      document_changed: "Belge değişti. İmzalamayı yeniden başlatın.",
      wrong_data: "Başka bir dosya imzalandı. Tekrar deneyin.",
      awaiting_approval: "Belge hâlâ avukat incelemesinde.",
    },
  },
  agreements: {
    yourLawyer: "Avukatınız",
    unreviewed: "Bunlar platform şablonlarıdır ve platform avukatı henüz incelemedi. Şartları işi üstlenen avukat kontrol eder ve imzasıyla onaylar.",
    leadCustomer: "E-imzanızla imzalayın, ardından avukat imzalar.",
    leadLawyer: "Müvekkil imzaladı. Şartları kontrol edin ve kayıtlı e-imzanızla imzalayın.",
    waitCustomer: "Müvekkilin imzası bekleniyor.",
    waitLawyer: "Avukatın imzası bekleniyor.",
    status: {
      awaiting_customer: "Müvekkil imzası bekleniyor",
      awaiting_lawyer: "Avukat imzası bekleniyor",
      signed: "İki taraf da imzaladı",
    },
    kind: {
      advocate: "Avukat",
      legal_consultant: "Hukuk danışmanı",
      human_rights: "İnsan hakları savunucusu",
      other: "Hukukçu",
    },
  },
  invite: {
    offer: "Bir arkadaşınızı davet edin: o bir belgenin ücretini ödediğinde ikiniz de bir belgeyi ücretsiz alırsınız",
    title: "İhtiyacı olanları davet edin",
    lead: "Bağlantınızı benzer bir sorunu olan arkadaşlarınıza ve yakınlarınıza gönderin. Sohbet onlar için ücretsiz.",
    share: "Bağlantıyı paylaş",
    copied: "Bağlantı kopyalandı",
    invited: "Bağlantınızla gelenler: {n}",
    shareText: "Konsiliér AI — hukuki sorular için ücretsiz yapay zekâ asistanı. Durumunuzu anlatın, ne yapmanız gerektiğini söylesin:",
  },
  submit: {
    courtName: "Yargı Kabineti",
    title: "{portal} üzerinden çevrimiçi başvurun",
    lead: { eotinish: "eOtinish, devlet kurumlarına başvuru için resmî portaldır. Kendi adınıza başvurursunuz; giriş ve imza e-imza veya eGov Mobile ile yapılır.", court: "Yargı Kabineti, Kazakistan mahkemelerine belge sunmak için resmî portaldır. Giriş ve imza e-imza veya eGov Mobile ile yapılır.", site: "Belge, alıcının resmî sitesinde sizin adınıza sunulur." },
    s1: "Belgeyi indirin ve başvuru metnini kopyalayın",
    download: "Belgeyi indir",
    copy: "Metni kopyala",
    copied: "Metin kopyalandı",
    s2: "{portal} sitesini açın ve gönderin",
    open: "{portal} sitesini aç",
    how: { eotinish: "E-imza veya eGov Mobile ile giriş yapın, bir başvuru oluşturun, alıcı listesinde “{to}” seçeneğini işaretleyin, kopyaladığınız metni yapıştırın, dosyayı ekleyip gönderin. Başvuru numarası bildirimle gelir.", court: "E-imza veya eGov Mobile ile giriş yapın, mahkemeye belge sunmayı seçin, mahkeme listesinde “{to}” seçeneğini işaretleyin, dosyayı ekleyip imzalayın.", site: "Alıcının sitesindeki formu doldurun ve dosyayı ekleyin." },
    s3: "Belgenin sunulduğunu işaretleyin",
    s3hint: "Ekranın altındaki “{btn}” düğmesine basın — yanıt süresini saymaya başlar, sonraki adımı hatırlatırız.",
    cover: "Ekteki “{title}” belgesinin incelenmesini rica ederim. Tam metin ve bilgiler ektedir.",
  },
  support: {
    title: "Bize yazın",
    lead: "Hizmetle ilgili bir soru sorun, bir sorunu bildirin veya bir iyileştirme önerin. Yanıt e-posta adresinize gelir ve bu sayfada görünür.",
    sentTitle: "{n} numaralı talebiniz alındı",
    sentText: "Yanıt e-postanıza gelir ve aşağıda “Taleplerim” bölümünde görünür.",
    kind: "Konu",
    kinds: { question: "Soru", complaint: "Şikâyet", suggestion: "Öneri", data: "Verilerim", plan: "Paket talebi" },
    textLabel: { question: "Sorunuz", complaint: "Ne ters gitti", suggestion: "Neyi iyileştirebiliriz", data: "Hangi veriler ve onlarla ne yapmamızı istiyorsunuz", plan: "İhtiyacınızı anlatın" },
    planTitle: "“{plan}” paketi için talep",
    planText: "“{plan}” paketine abone olmak istiyorum.",
    case: "Talep hangi dosyayla ilgili",
    noCase: "Bir dosyayla ilgili değil",
    contacts: "Yanıtı nereye gönderelim",
    contactHint: "E-posta veya telefon numarası girin — en az birini.",
    phoneOnly: "Yanıtı e-postayla göndeririz. E-posta olmadan yanıt yalnızca bu sayfada görünür — kaçırmamak için e-posta ekleyin.",
    send: "Gönder",
    mine: "Taleplerim",
    status: { new: "Alındı", in_progress: "İnceleniyor", done: "Çözüldü" },
    team: "Konsiliér AI",
    you: "Siz",
    replyPlaceholder: "Yanıtla",
  },
  lawyer: {
    casesTitle: "Dosyalarınız",
    requests: {
      title: "Müvekkil talepleri",
      empty: "Henüz yeni talep yok.",
      status: {
        new: "Yeni",
        accepted: "Kabul ettiniz",
        declined: "Reddettiniz",
        paid: "Ödendi",
        closed: "Kapandı",
      },
      category: "Kategori",
      city: "Şehir",
      amount: "Uyuşmazlık tutarı",
      price: "Ücretiniz",
      payout: "Size ödenecek tutar (platform komisyonu %{pct})",
      accept: "Kabul et",
      decline: "Reddet",
      waitPayment: "Müvekkilin ödemesi bekleniyor. Ödemeden sonra dosya özeti ve müvekkilin iletişim bilgileri açılır.",
      client: "Müvekkilin iletişim bilgileri",
    },
    dossier: {
      open: "Dosya özetini aç",
      hide: "Dosya özetini gizle",
      story: "Müvekkilin anlatımı",
      narrative: "Belgeler için özet",
      facts: "Olgular",
      evidence: "Deliller",
      deadlines: "Süreler",
      documents: "Belgeler",
      none: "Henüz yok.",
      download: "İndir",
    },
    steps: {
      title: "Avukat olarak katılım",
      applied: "Başvuru gönderildi",
      appliedHint: "Kısa formu doldurun: statü, kuruluş, uzmanlık alanları.",
      ecp: "Kimliğinizi e-imzayla doğrulayın",
      ecpHint: "Zorunludur: başvurunun gerçekten size ait olduğunu gösterir; müvekkillerle belgeleri yalnızca bu e-imzayla imzalarsınız.",
      ecpDo: "E-imzayla doğrula",
      check: "Ekip tarafından statü kontrolü",
      checkHint: "Avukat veya hukuk danışmanı statünüzü sicilden kontrol eder, verdiğiniz iletişim bilgisiyle size ulaşırız. Genellikle 1–2 iş günü.",
      access: "Dosyalara erişim",
      accessHint: "Panel otomatik açılır: dosyalar, belgeler ve müvekkillerle sözleşme imzalama.",
      doneLead: "Tek adım kaldı: kimliğinizi e-imzayla doğrulayın, ardından başvuru statü kontrolüne gider.",
    },
    eyebrow: "Avukatlar için",
    title: "Avukat paneli",
    lead: "Platformun size ilettiği dosyalar ve müvekkille e-imzayla imzalanan belgeler.",
    ecpNeeded: "E-imzayla giriş yapın: kimliğinizi böyle doğrularız ve müvekkillerle belgeleri yalnızca bu e-imzayla imzalayabilirsiniz.",
    ecpSignIn: "E-imzayla giriş yap",
    ecpOk: "Kimlik e-imzayla doğrulandı",
    cabinetLink: "Avukat panelini aç",
    noApplication: "Henüz katılım başvurusu yapmadınız.",
    apply: "Başvur",
    noCases: "Size iletilmiş dosya henüz yok.",
    aboutProgram: "Ortaklık programı hakkında",
    status: {
      new: "Başvurunuz sicile göre kontrol ediliyor. Genellikle 1–2 iş günü sürer.",
      rejected: "Başvurunuz reddedildi. Hata olduğunu düşünüyorsanız bize yazın.",
      rejectedReason: "Gerekçe: {reason}",
    },
  },
  pilot: {
    inviteChecking: "Bağlantı kontrol ediliyor…",
    inviteInvalid: "Bu davet bağlantısı geçersiz veya süresi dolmuş. Lütfen Konsiliér AI ekibinden yenisini isteyin: info@konsilier.com.",
    title: "Tek dokunuşla avukat",
    lead: "Avukat, dosyanızın hazır özetini alır: yaşadıklarınız, olgular, deliller ve belgeler. Önce avukat talebinizi kabul eder, ardından siz ücretini ödersiniz.",
    empty: "Avukatlar yakında burada görünecek.",
    choose: "Talep gönder",
    contactsHint: "Avukat, iletişim bilgilerinizi ve dosya belgelerini yalnızca ödemeden sonra görür.",
    consent: "Kişisel verilerimin işlenmesini ve ödemeden sonra dosya belgelerinin seçtiğim avukata iletilmesini kabul ediyorum.",
    send: "Talebi gönder",
    cancel: "Vazgeç",
    formError: "Adınızı ve telefon numaranızı kontrol edin, onay kutusunu işaretleyin.",
    waitingTitle: "Talep gönderildi",
    waiting: "{name} talebinizi aldı. Yanıt verdiğinde size haber vereceğiz.",
    accepted: "{name} talebinizi kabul etti. Dosya belgelerini alabilmesi için ödemeyi yapın.",
    pay: "{price} öde",
    payLater: "Platform üzerinden ödeme yakında açılacak. Avukat, verdiğiniz telefon numarasından sizinle iletişime geçecek.",
    payTo: "Alıcı: {name}",
    payLink: "Kaspi ile öde",
    payAccount: "Havale için banka bilgileri",
    payCode: "Ödeme kodu: ödeme açıklamasına yazın",
    companyNote: "Ödeme kişisel hesaplara değil, Konsilier AI şirketinin hesabına yapılır.",
    paidBtn: "Ödedim",
    checking: "Ödemeyi kontrol ediyoruz. Onaylanır onaylanmaz avukat dosya belgelerini alacak.",
    notFound: "{code} kodlu ödeme bulunamadı. Tutarı ve açıklamayı kontrol edip «Ödedim» düğmesine yeniden basın.",
    paid: "Ödendi. {name} dosya belgelerini aldı.",
    declined: "{name} bu dosyayı alamıyor. Lütfen başka bir avukat seçin.",
  },
  formErrors: {
    required: "Bu alanı doldurun",
    invalid: "Değeri kontrol edin",
    too_long: "Değer çok uzun",
    name_length: "2 ile 100 karakter arası",
    name_chars: "Yalnızca harf, boşluk, kısa çizgi ve kesme işareti — rakam, nokta veya başka işaret olmadan",
    name_words: "Soyadınızı ve adınızı eksiksiz yazın — en az iki kelime",
    phone_format: "Kazakistan telefon numarası: +7 ve 10 rakam, ör. +7 701 123 45 67",
    phone_operator: "+7'den sonra numara 7 ile başlamalı (701, 747, 777…). Kazakistan numarası girin",
    email_format: "E-postayı kontrol edin, ör. name@mail.kz",
    city_format: "Şehri harflerle yazın",
    license_format: "Yalnızca harf, rakam, “№”, “/” ve kısa çizgi; en az bir rakam",
    kind_required: "Statünüzü seçin",
    license_number_required: "Avukat ve hukuk danışmanı için ruhsat veya belge numarası zorunludur",
    consent_required: "Veri işleme onayı olmadan başvuruyu kabul edemeyiz",
    phone_duplicate: "Bu numarayla bir başvuru zaten var — tekrar başvurmanıza gerek yok. Durumu avukat panelinde.",
    ecp_duplicate: "Bu e-imzayla bir başvuru zaten var. Durumu avukat panelinde.",
    too_many: "Bu adresten çok fazla başvuru yapıldı. Bir saat sonra tekrar deneyin.",
    fix: "Kırmızıyla işaretlenen alanları kontrol edin.",
  },
  gov: {
    ecpOnly: "E-imza gerekir",
    title: "egov.kz belgeleri",
    lead: "Bu belgeler dosyanızı güçlendirebilir. Onları egov.kz'den kendiniz alın — e-imzanızla veya eGov Mobile ile — ve buraya yükleyin: delillere eklenir.",
    needsEcp: "egov.kz girişi: e-imza veya SMS kodu",
    open: "Girişsiz",
    get: "egov.kz'den al",
    upload: "Belgeyi yükle",
    uploaded: "Yüklendi",
    disclaimer: "egov.kz'ye sizin adınıza girmiyoruz ve oradaki verilerinizi göremiyoruz — belgeyi kendiniz alırsınız.",
  },
  reports: {
    title: "Dosya raporları e-postayla",
    lead: "Dosyanız ilerlediğinde rapor göndeririz: nerede olduğu, ne yapıldığı ve ayrıntılı talimatlarla bir sonraki adım. Dosya durursa 3 günde bir hatırlatırız.",
    toggle: "{email} adresine gönder",
    needEmail: "Rapor almak için aşağıda e-postanızı doğrulayın (“E-posta ile”).",
    hint: "Dosya raporlarını ve sonraki adım hatırlatmalarını e-postayla alın.",
    hintCta: "E-postayı doğrula",
  },
  payment: {
    contact: {
      phone: "Telefonunuz — belgeyi göndeririz ve süreyi hatırlatırız",
      email: "E-postanız — belgeyi göndeririz ve süreyi hatırlatırız",
      lead: "Kodla doğrulayın — tarayıcı veya cihaz değiştirseniz de dosya sizde kalır.",
    },
    title: "Belge ödemesi",
    lead: "Sohbet ücretsizdir; belge hazırlama ücretlidir. Tutarı aşağıdaki bilgilerle Kaspi üzerinden gönderin — belge, ödeme onaylandıktan sonra erişilebilir olur.",
    recipient: "Alıcı",
    kaspi: "Havale için Kaspi numarası",
    code: "Ödeme kodu — havale açıklamasına yazın",
    copy: "Kopyala",
    copied: "Kopyalandı",
    steps: "Kaspi → Transferler → telefon numarasıyla: numarayı ve tutarı girin, açıklamaya ödeme kodunu yazın. Havaleden sonra “Öde” düğmesine dokunun.",
    paid: "Öde",
    waiting: "Havaleyi kontrol ediyoruz. Ödeme onaylanır onaylanmaz belge otomatik olarak hazırlanır — bu pencereyi kapatabilirsiniz.",
    checking: "Ödeme kontrol ediliyor…",
    refresh: "Ödeme durumunu kontrol et",
    notFound: "Bu koda sahip bir havale henüz bulunamadı. Tutarı ve havale açıklamasını kontrol edip “Öde” düğmesine tekrar dokunun veya destekle iletişime geçin.",
    unavailable: "Ödeme geçici olarak kullanılamıyor, bu nedenle belge şu anda verilemiyor. Lütfen daha sonra tekrar deneyin veya destekle iletişime geçin.",
    price: "Belge hazırlama ücreti: {price}. Ödeme havaleyle yapılır; belge, ödeme onaylandıktan sonra erişilebilir olur.",
    titleCase: "Anahtar teslim dosya ödemesi",
    choose: "Bu dosyanın belgeleri için ödeme şekli:",
    option: { document: "Tek belge — {price}", case: "Anahtar teslim dosya — {price}" },
    caseHint: "Anahtar teslim dosya: sonuca kadar bu dosyanın tüm belgeleri — ihtarname, şikâyet, dava dilekçesi.",
  },
  plans: {
    title: "İşletmeler için paketler",
    lead: "Belge limitli 30 günlük abonelik. Kaspi havalesiyle ödenir; paket, ödeme onaylandıktan sonra başlar.",
    active: "“{plan}” paketi {date} tarihine kadar etkin. Kalan belge: {n}.",
    documents: "{days} günde tüm dosyalarınız için {n} belgeye kadar.",
    buy: "Abone ol",
    signIn: "Paket almak için hesabınıza giriş yapın; ödeme size bağlanır.",
    signInCta: "Giriş yap",
    payTitle: "“{plan}” paketi ödemesi",
    forPeople: "Tek bir belgeye veya tek bir dosyada yardıma mı ihtiyacınız var?",
    forPeopleCta: "Durumunuzu anlatın",
  },
  filing: {
    title: "Nasıl başvurulur",
    to: "Nereye",
    fileBy: "Son başvuru tarihi",
    respond: "Yanıt süresi: {term}",
    within: {
      calendar: { one: "{n} takvim günü içinde", other: "{n} takvim günü içinde" },
      business: { one: "{n} iş günü içinde", other: "{n} iş günü içinde" },
    },
    norm: "Dayanak: {ref}",
    lawyer: "avukat netleştirecek",
    overdue: "Bu tarih geçti — ne yapılacağını bir avukatla görüşün",
    ways: "Başvuru yolları",
    signature: "İmza",
    phone: "Telefondan",
    desktop: "Bilgisayardan",
    open: "{portal} sitesini aç",
    stepByStep: "Adım adım",
  },
  law: {
    title: "Kanun hakkında soru",
    lead: "Dosyanız hakkında sorun. Yapay zekâ resmî Adilet portalında (adilet.zan.kz) normları bulur, maddeleri açar ve bağlantılarla yanıtlar — her alıntı resmî metinle karşılaştırılır.",
    placeholder: "Örneğin: işten çıkarıldıktan sonra işveren ödemeyi ne kadar sürede yapmalı?",
    ask: "Sor",
    busy: "Yasalarda arıyoruz…",
    busyHint: "Genellikle 20–60 saniye: yapay zekâ adilet.zan.kz'de maddeleri açar.",
    verified: "Normlar resmî metinle karşılaştırıldı",
    needsLawyer: "Avukat teyit edecek: tüm sonuçlar resmî metinle doğrulanmadı veya soru avukat gerektiriyor.",
    norms: "Yanıtın dayanağı",
    article: "Madde {n}",
    source: "adilet.zan.kz'de aç",
    dropped: "Doğrulanmayan atıflar çıkarıldı: {n}",
    disclaimer: "Bu, yasaların resmî metinlerine dayanan bir bilgidir, hukuki görüş değildir. Karmaşık durumlarda bir avukatı dahil ederiz.",
    errors: {
      agent_unavailable: "Bu soruyu ücretsiz yapay zekâ sohbetine sorun.",
      agent_failed: "Şu anda yanıtlanamadı. Biraz sonra tekrar deneyin.",
      too_many_questions: "Bugün bu dosyada çok soru soruldu. Yarın deneyin.",
    },
  },
};

export default tr;
