import type { Dict } from "./types";

const tr: Dict = {
  nav: {
    start: "Başla", cases: "Dosyalarım", admin: "Yönetim", lawyers: "Avukatlar", forLawyers: "Avukatlar için",
    howItWorks: "Nasıl çalışır", coverage: "Kapsam", menu: "Menü", language: "Dil",
    skip: "İçeriğe geç", main: "Ana menü",
  },
  footer: {
    tagline: "Şikâyetten sonuca giden yol: belge, başvuru, süreler ve doğrulanmış avukatlar.",
    product: "Ürün", lawyers: "Avukatlara", designSystem: "Tasarım sistemi",
  },
  level: {
    pending: { label: "Yol belirleniyor", desc: "Durumu inceliyoruz. Ne olduğu netleşince uygun yolu ve ilk adımı göstereceğiz." },
    verified: { label: "Avukat onaylı", desc: "Hazır senaryo: mevzuat, süreler ve muhataplar avukat tarafından onaylandı. Tamamen otomatik süreç." },
    scenario_draft: { label: "Senaryo, onay bekliyor", desc: "Hazır senaryo çalışıyor, ancak avukat mevzuatı ve süreleri henüz onaylamadı: belgeler «Taslak» olarak işaretli." },
    universal: { label: "Genel yol", desc: "Hazır senaryo yok. Belgeyi genel şablonla hazırlıyoruz, muhatap kurum sicilinden seçiliyor, avukat belgeyi başvurudan önce kontrol ediyor." },
    lawyer: { label: "Avukat gerekli", desc: "Karmaşık veya riskli durum: dosyayı hazırlayıp doğrulanmış bir avukata iletiyoruz." },
    soon: { label: "Yakında", desc: "Şimdilik dosya kabul etmiyoruz. İletişim bilgilerinizi bırakın, açıldığımızda yazalım." },
  },
  path: {
    document: { title: "Belge", text: "Anlattıklarınıza ve delillerinize göre şikâyet, ihtarname, dilekçe veya dava dilekçesi." },
    forum: { title: "Muhatap", text: "Kurum veya kuruluş yalnızca doğrulanmış sicilden seçilir, uydurmayız." },
    deadline: { title: "Süreler", text: "Cevap süresini hesaplar ve hatırlatırız. Süre verilerde yoksa avukat netleştirir." },
    escalation: { title: "Üst başvuru", text: "Cevap yoksa veya ret geldiyse sonraki adımı hazırlarız: üst kurum, mahkeme." },
    lawyer: { title: "Avukat", text: "Gerektiğinde sonuçlara dayalı puanı olan doğrulanmış bir avukatı dahil ederiz." },
  },
  emergency: {
    title: "Önce güvenlik",
    continue: "Güvendeyim, devam et",
    sample: "Şu anda hayatınız veya sağlığınız tehlikedeyse acil servisleri arayın.",
  },
  cta: {
    title: "Başlamaya hazır mısınız?",
    lead: "Durumu kendi sözlerinizle anlatın — yolu gösterip ilk belgeyi hazırlayalım.",
    start: "Durumu anlat",
    lawyer: "Avukat bul",
    more: "Daha fazla",
    next: "İleri",
    startCase: "Dava başlat",
    complain: "Şikâyet et",
    join: "Avukat mısınız? Katılın",
    caseLawyerTitle: "Avukat yardımı mı gerekiyor?",
    caseLawyerText: "Bir avukat belgelerinizi inceleyebilir veya davanın tamamını üstlenebilir.",
    lawyersLead: "Durumu anlatın — belgeleri hazırlarız, gerektiğinde bir avukatı dahil ederiz.",
  },
  home: {
    eyebrow: "Belge · başvuru · süreler · avukat",
    title: "Her hukuki sorun: şikâyetten sonuca kadar",
    sub: "Ne olduğunu anlatın. Belgeyi hazırlarız, nereye başvuracağınızı söyleriz, süreleri takip ederiz. Avukat gerekirse doğrulanmış birini dahil ederiz.",
    promise1: "Ülkenizin yasalarına göre belge",
    promise2: "Doğrulanmış sicilden muhatap",
    promise3: "Süre hatırlatmaları ve sonraki adım",
    promise4: "Gerektiğinde doğrulanmış avukatlar",
    describe: "Ne olduğunu anlatın",
    cta: "Devam et",
    privacy: "İsimleri ve belge numaralarını yapay zekâ işlemeden önce etiketlerle değiştiriyoruz. Belgeler sizin adınıza sunulur.",
    situationsEyebrow: "Hayattan durumlar",
    situationsTitle: "Neyde yardımcı oluyoruz",
    situationsLead: "Hangi hukuk dalı olduğunu bilmeniz gerekmez. Benzer bir durumu seçin ya da kendinizinkini anlatın.",
    pathEyebrow: "Yol haritası",
    pathTitle: "Dosyanız nasıl ilerler",
    pathLead: "Her adımda ne kadar doğrulandığı görünür: avukat onaylı, genel yol ya da avukat gerekli.",
    levelsEyebrow: "Kapsam hakkında açıkça",
    levelsTitle: "Üç seviye: dosyanızın hangisinde olduğunu hep bilirsiniz",
    levelsLead: "Yol, belge, süre takibi ve avukat vaat ediyoruz; dosyanın sonucunu değil.",
    howLink: "Nasıl çalıştığı hakkında daha fazla",
    coverageTitle: "Kazakistan'da çalışıyoruz. BDT ve Orta Doğu yakında",
    coverageLead: "Özbekistan, Kırgızistan, Azerbaycan, Türkiye, BAE, Suudi Arabistan ve diğer ülkeler açılış planında.",
    coverageCta: "Ülkelere göre kapsam",
  },
  situations: {
    cheated: { label: "Alışverişte dolandırıldım", hint: "Ürün, hizmet, pazaryeri, para iadesi.", placeholder: "Ne aldınız, kimden, ne zaman, kaça ve ne ters gitti" },
    fired: { label: "İşten çıkarıldım veya maaş ödenmiyor", hint: "İşten çıkarma, maaş alacağı, ayrımcılık.", placeholder: "Nerede çalışıyorsunuz, ne oldu ve ne zaman, ne kadar borçlular" },
    family: { label: "Boşanma ve çocuklar", hint: "Boşanma, nafaka, velayet, mal paylaşımı.", placeholder: "Kısaca: ne oluyor ve ne elde etmek istiyorsunuz" },
    fine: { label: "Para cezası", hint: "Para cezasına veya karara itiraz.", placeholder: "Ceza ne için, kim yazdı, ne zaman ve neden katılmıyorsunuz" },
    crime: { label: "Bana karşı suç işlendi", hint: "Hırsızlık, dolandırıcılık, darp. Yalnızca olgular: ne, nerede, ne zaman.", placeholder: "Ne oldu, nerede ve ne zaman, kim gördü, zarar ne" },
    stateBody: { label: "Kamu kurumuyla uyuşmazlık", hint: "Ret, işlem yapmama, başvuruya cevap verilmemesi.", placeholder: "Hangi kurum, ne talep ettiniz ve ne cevap verdiler" },
    bank: { label: "Banka, kredi, tahsilat şirketleri", hint: "Adınıza çekilen kredi, bankayla uyuşmazlık, tahsilatçı baskısı.", placeholder: "Hangi banka veya finans şirketi, ne oldu, hangi tutarlar" },
    business: { label: "Ticari uyuşmazlık", hint: "Karşı tarafın borcu, sözleşme ihlali.", placeholder: "Sözleşme kiminle, ne ihlal edildi, tutar ne" },
    inheritance: { label: "Miras", hint: "Mirasın kabulü, mirasçılar arası uyuşmazlık.", placeholder: "Kim ve ne zaman vefat etti, mirasçılar kim, sorun ne" },
    housing: { label: "Konut ve komşular", hint: "Kira, faturalar ve aidatlar, komşular.", placeholder: "Nasıl bir konut, uyuşmazlık kiminle, ne oldu" },
  },
  board: {
    intake: "Başvuru", qualified: "Bilgiler toplandı", action_ready: "Belge hazır", submitted: "Sunuldu, cevap bekleniyor",
    escalated: "Üst başvuru", handed_to_lawyer: "Avukatta", resolved: "Çözüldü",
    empty: "Boş", stepOf: "Aşama {n} / {total}",
    attention: { hold: "İncelemede", ack: "Onay gerekli", expired: "Cevap süresi doldu", approval: "Avukat kontrolü bekleniyor", chooseForum: "Muhatabı seçin" },
  },
  ack: {
    false_report: { title: "Suç uydurma ve iftiranın sorumluluğu", button: "Anladım ve onaylıyorum", text: "Bilerek gerçeğe aykırı ihbar ve şikâyette bulunmanın cezai sorumluluğu vardır. Yalnızca bildiğiniz olguları anlatın." },
    special_category: { title: "Özel nitelikli verilerin işlenmesine onay", button: "Onay veriyorum", text: "Dosyada sağlık, din veya sabıka bilgileri olabilir. En az veriyi saklar ve yalnızca belgeniz için kullanırız." },
  },
  forum: {
    chooseTitle: "Nereye başvurulur",
    chooseLead: "Muhatabı seçin. Liste yalnızca bu ülkenin kurum sicilinden; farklar aşağıda gösteriliyor.",
    type: { court: "Mahkeme", prosecutor: "Savcılık", police: "Polis", regulator: "Düzenleyici kurum", ministry: "Bakanlık",
      ombudsman: "Ombudsman", local_authority: "Yerel yönetim", arbitration: "Tahkim", mediation: "Arabuluculuk",
      private_org: "Kuruluş" },
    effect: { binding: "Karar bağlayıcı", advisory: "Tavsiye niteliğinde karar", none: "Hukuki etkisi yok" },
    verified: "Avukat onaylı", unverified: "Bilgileri avukat netleştirecek", deadlineByLawyer: "Süreyi avukat netleştirecek",
    channels: "Nasıl başvurulur", channel: { portal: "çevrimiçi portal", email: "e-posta", post: "posta", in_person: "şahsen" },
    choose: "Seç",
  },
  common: { loading: "Yükleniyor…", sending: "Gönderiliyor…" },
  roadmap: {
    title: "Dosyanın yol haritası",
    best: "En iyi durum",
    worst: "Tüm adımlar gerekirse",
    openEnded: "ardından avukatla çalışma, süreler anlaşmaya göre",
    done: "Tamamlandı",
    current: "Şimdi",
    upcoming: "Sonra",
    skipped: "Gerek kalmadı",
    ifNeeded: "gerekirse",
    due: "süre",
    estimated: "tahmini",
    finished: "tamamlandı",
    todoNorm: "süreyi avukat netleştiriyor",
  },
  trust: {
    title: "Dolandırıcılığa ve boş vaatlere karşı nasıl koruyoruz",
    verifiedTitle: "Yalnızca doğrulanmış avukatlar",
    verified: "Avukat veya hukuk danışmanı statüsü sicillerden kontrol edilir, kimlik e-imza ile doğrulanır. Doğrulama yoksa müvekkillere erişim de yok.",
    escrowTitle: "Aşamalı ödeme, para güvencede",
    escrow: "Her şeyi peşin ödemezsiniz. Tutar ödeme ortağında bloke edilir ve avukata ancak aşama tamamlanınca aktarılır: ihtarname gönderildi, cevap alındı, dava açıldı.",
    ratingTitle: "Kanıtlanmış sonuçlara dayalı puan",
    rating: "Puan platformdaki gerçek dosyalara göre hesaplanır: zorluğa göre düzeltilmiş kazanılan dosyalar, geri alınan para, sürelere uyum. Yorumlar yalnızca anlaşmadan sonra.",
    roadmapTitle: "Dosyanızın nerede olduğunu görürsünüz",
    roadmap: "Yol haritası: ne yapıldı, şimdi ne var, sonraki adımlar ne ve karar ne zaman beklenir; en iyi ve en kötü durum.",
    soon: "Avukatla güvenli işlem geliştiriliyor",
    more: "Ayrıntılar",
    less: "Kapat",
    now: "Şimdi",
    verifiedMore: "Avukat: baroya kayıt ve geçerli ruhsat.\nHukuk danışmanı: hukuk danışmanları odasına üyelik.\nKimlik e-imza ile doğrulanır; başkasının adıyla çalışılamaz.\nRuhsat iptal edilirse veya odadan çıkarılırsa profil gizlenir.",
    verifiedNow: "Avukat başvurularını şu an ekip belgelere göre elle kontrol ediyor. Sicillerle otomatik kontrol ve e-imza ile giriş geliştiriliyor.",
    verifiedLink: "Platform avukatı nasıl olunur",
    escrowMore: "Ücret ve aşamalar iş başlamadan sözleşmede belirlenir.\nAşama ücreti avukatta değil, ödeme ortağında bloke edilir.\nAvukat, aşama onaylanınca ödemeyi alır: belge sunuldu, cevap alındı.\nAşama yapılmazsa o aşamanın parası size iade edilir.\nAnlaşmazlıkları platform dosyadaki belgelere göre inceler.",
    escrowNow: "Özellik geliştiriliyor: Kazakistan'da ödeme ortağı seçiyoruz. Açılışa kadar avukatlara dosyanın tamamı için peşin ödeme yapmayın.",
    ratingMore: "Sonuç, avukatın beyanıyla değil, dosya platformda kapatılırken kaydedilir.\nSonuç aynı kategorinin ortalamasıyla karşılaştırılır; kolay dosyalar puanı şişirmez.\nBileşim: başarı %45, sürelere uyum %20, geri alınan para %20, yorumlar %15.\nYeni avukatların puanı 30+ dosyaya ulaşana kadar platform ortalamasına çekilir.\nYorum yalnızca gerçek bir anlaşmadan sonra bırakılabilir.",
    ratingNow: "Şimdilik demo profillerle örnek gösteriliyor: gerçek puan, avukatlar platformda ilk dosyaları kapattığında görünecek.",
    ratingLink: "Örnek puanı gör",
    roadmapMore: "Dosyanın her adımı: ihtarname, cevap bekleme, düzenleyici kuruma şikâyet, dava.\nHer adım için yasal süre ve bitiş tarihi.\nİki tahmin: en iyi (ihtarnameden sonra çözüldü) ve tüm adımlar gerekirse.\nHiçbir süreyi kaçırmamanız için hatırlatırız.",
    roadmapNow: "Şu an çalışıyor: yol haritası her dosyada durumu anlattıktan hemen sonra açılır.",
    roadmapLink: "Dosya başlat",
    cta: "Örnek puanı gör",
    joinLawyer: "Avukat mısınız? Katılın",
  },
  lawyers: {
    title: "Avukatlar ve hukukçular",
    subtitle: "Puan reklama değil, platformdaki kanıtlanmış sonuçlara dayanır.",
    score: "Puan",
    confidence: { low: "az dosya", medium: "orta örneklem", high: "geniş örneklem" },
    vsBaseline: "platform ortalamasına göre",
    cases: "doğrulanmış dosya",
    recovered: "geri alınan para",
    onTime: "zamanında aşama",
    reviews: "anlaşma sonrası yorumlar",
    from: "başlangıç",
    proBono: "ücretsiz (pro bono)",
    response: "ortalama yanıt süresi",
    hours: "sa",
    years: "yıl deneyim",
    verifiedLicense: "Ruhsat doğrulandı",
    verifiedId: "Kimlik doğrulandı",
    success: "başarı",
    platform: "ortalama",
    methodTitle: "Puan nasıl hesaplanır",
    method1: "Yalnızca platformdan geçen dosyalar: sonuç avukatın beyanıyla değil, dosya kapatılırken kaydedilir.",
    method2: "Sonuç aynı kategorideki dosyaların ortalamasıyla karşılaştırılır; kolay dosya seçmek puanı yükseltmez.",
    method3: "Küçük örneklem ortalamaya çekilir: 3'te 3 galibiyet, 220'de 180'i geçemez.",
    method4: "Ağırlık: başarı %45, aşama sürelerine uyum %20, geri alınan para oranı %20, anlaşma sonrası yorumlar %15.",
    choose: "Seç",
    chooseSoon: "Avukat seçimi güvenli işlemle birlikte açılacak",
    pp: "puan",
    mln: "mn",
  },
  landing: {
    promise: "Dosyanız: ilk belgeden sonuca kadar",
    sub: "Durumu kendi sözlerinizle anlatın. Konsilier.AI, Kazakistan yasalarına göre ihtarname veya şikâyet hazırlar, nereye başvuracağınızı söyler ve süreleri takip eder. Bu yetmezse platformun profesyonel avukatı dosyayı sonuna kadar götürür.",
    usp1: "Hazır belgeler: avukat aramadan, internetten şablon bulmadan",
    usp2: "Süreler kontrol altında: hatırlatır, sonraki adımı hazırlarız",
    usp3: "Platform avukatları: doğrulanmış, gerçek sonuçlara dayalı puanlı",
    startWeb: "Sitede başla",
    startTelegram: "Telegram'da aç",
    scenariosTitle: "Şu an neler yapabiliyoruz",
    howTitle: "Nasıl çalışır",
    how1: "Ne olduğunu anlatın",
    how2: "Kısa soruları yanıtlayın, fiş veya ekran görüntülerini yükleyin",
    how3: "Belgeyi ve başvuru talimatını alın",
    how4: "Cevap süresini takip eder, sonraki adımı öneririz",
    countryTitle: "Ülkeniz",
    countryLive: "Mevcut",
    countrySoon: "Yakında",
    waitlistTitle: "Bu ülkede henüz hizmet vermiyoruz",
    waitlistText: "İletişim bilgilerinizi bırakın, açıldığımızda yazalım.",
    waitlistContact: "E-posta veya Telegram",
    waitlistProblem: "Hangi sorunla karşılaştınız? (isteğe bağlı)",
    waitlistSend: "Açılışta haber ver",
    waitlistDone: "Teşekkürler! Açıldığımızda yazacağız.",
    price: "Ücret",
    disclaimer: "Belgeler sizin adınıza sunulur; her adımı siz kontrol edersiniz.",
  },
  start: {
    eyebrow: "Yeni dosya",
    country: "Ülke: Kazakistan.",
    otherCountry: "Başka ülke",
    busy: "Durumu inceliyoruz… Bu bir dakika sürebilir.",
    title: "Ne oldu?",
    placeholder: "Örneğin: 12.08.2026'da internet mağazasından 150 000 tenge'ye telefon aldım, bir hafta sonra bozuldu, parayı iade etmiyorlar",
    submit: "Devam et",
  },
  case: {
    back: "Tüm dosyalar",
    untitled: "Yeni dosya",
    holdTitle: "Dosya elle incelemede",
    draftTitle: "Taslak",
    lawyerTitle: "Dosya avukata iletiliyor",
    lawyerCta: "Doğrulanmış avukatlar",
    lawyerText: "Açıklamanızı kaydettik ve dosyayı platformun doğrulanmış bir avukatına iletiyoruz.",
    uplTitle: "Biz kimiz",
    thinking: "Yanıt hazırlanıyor… Yavaş bağlantıda bir dakika sürebilir.",
    working: "İşleniyor… Sayfayı kapatmayın.",
    send: "Yanıtla",
    answerPlaceholder: "Yanıtınız",
    more: "Açıklamayı tamamla",
    morePlaceholder: "Tam olarak ne aldınız veya yaptırdınız, kimden, ne zaman, hangi tutara ve ne ters gitti",
    skip: "Atla",
    upload: "Dosya yükle",
    uploadHint: "Fotoğraf veya PDF, en fazla 15 MB",
    found: "Dosyada bulduklarımız",
    confirm: "Hepsi doğru",
    nothingFound: "Dosya kaydedildi. Veriler otomatik okunamadı.",
    facts: "Dosya bilgileri",
    prepare: "Belgeyi hazırla",
    handoff: "Avukata ilet",
    awaitingApproval: "Belge avukat kontrolünde. Hazır olduğunda haber vereceğiz.",
    rejected: "Avukat belgeyi düzeltme için geri gönderdi.",
    download: "İndir",
    instructions: "Nasıl başvurulur",
    submitted: "Gönderdim",
    sendEmail: "Benim yerime e-postayla gönder",
    deadline: "Cevap süresi",
    gotResponse: "Cevap geldi",
    noResponse: "Cevap yok",
    responsePlaceholder: "Cevap metnini yapıştırın",
    responseSend: "Cevabı analiz et",
    responseFile: "veya cevap dosyasını yükleyin",
    close: "Dosyayı kapat",
    closeWon: "Tamamı iade edildi",
    closePartial: "Kısmen",
    closeLost: "İade edilmedi",
    amountRecovered: "İade edilen tutar",
    outcome: "Sonuç",
    days: "gün",
    response: "Cevap",
    notifications: "Bildirimler",
    datePlaceholder: "GG.AA.YYYY",
    classes: { full: "Tamamen", partial: "Kısmen", refusal: "Ret", none: "Cevap yok" },
    deadlineStatus: { active: "işliyor", met: "cevap alındı", expired: "doldu", cancelled: "iptal edildi" },
  },
  cases: {
    title: "Dosyalarım", empty: "Henüz dosya yok.", open: "Aç", new: "Yeni dosya",
    lead: "Her dosya panoda bir karttır: başvurudan karara kadar. Dosyalar kaybolmaz, aşamalar arasında ilerler.",
  },
  coverage: {
    eyebrow: "Kapsam",
    title: "Nerede ve hangi konularda yardım ediyoruz",
    lead: "Ülkelere ve hukuk dallarına göre dürüst durumlar: ne avukat onaylı, nerede avukat kontrollü genel yol çalışıyor, ne yakında.",
    legend: "Durumlar ne anlama gelir",
    liveLead: "Bu ülkedeki her hukuk dalının durumu.",
    plannedTitle: "Yakında: BDT ve Orta Doğu",
    plannedLead: "Bu ülkeler için yerel avukatlarla doğrulanmış veriler hazırlıyoruz. Şimdilik dosya kabul etmiyoruz.",
    waitlistTitle: "Açılışta bana haber ver",
  },
  how: {
    eyebrow: "Nasıl çalışır",
    title: "Yol, belge, süre takibi ve avukat",
    lead: "Konsilier.AI dosyayı hazır belgeye, başvuruya ve sonraki adıma kadar götürür. Yapay zekâ metinde yardım eder; mevzuat, süreler ve muhataplar yalnızca doğrulanmış verilerden alınır.",
    pathTitle: "Yol haritası",
    pathLead: "Belge → muhatap → süre → üst başvuru → avukat.",
    levelsTitle: "Üç kapsam seviyesi",
    levelsLead: "Seviye otomatik belirlenir ve dosyada her zaman gösterilir.",
    level: {
      verified: { title: "Doğrulanmış senaryo", when: "Avukatın mevzuatı, süreleri ve muhatapları onayladığı sık durumlar için.", get: { 1: "Doğrulanmış şablona göre belge", 2: "Yasadan cevap süreleri ve hatırlatmalar", 3: "Önceden bilinen zincire göre sonraki adım" } },
      universal: { title: "Genel yol", when: "Hazır senaryo yoksa, ama hukuk dalı belliyse ve sicilde uygun bir kurum varsa.", get: { 1: "«Taslak» işaretli genel şablonlu belge", 2: "Başvurudan önce avukat kontrolü: her zaman", 3: "Mevzuat ve süreler yalnızca verilerden; yoksa «avukat netleştirecek»" } },
      lawyer: { title: "Avukata devir", when: "Ceza davasında savunma tarafı, çocuklar, yüksek tutarlar, dolmak üzere olan süreler, belirsiz durum.", get: { 1: "Anlatımınıza göre dosya özeti", 2: "Sonuçlara dayalı puanı olan doğrulanmış avukat", 3: "Savunma belgelerini yalnızca avukat yazar" } },
    },
    rolesTitle: "Kim ne yapar",
    ai: {
      title: "Yapay zekâ",
      does: { 1: "Anlattıklarınızı anlar ve kısa sorular sorar", 2: "Olayların özetini yazar ve talepleri formüle eder", 3: "Muhatabın cevabını okur ve sonraki adımı önerir", 4: "Yalnızca anonimleştirilmiş verilerle çalışır" },
      neverTitle: "Yapay zekâ asla",
      never: { 1: "Mevzuat, madde ve süre uydurmaz", 2: "Başvurulacak kurumu seçmez", 3: "Din veya etnik köken belirlemez", 4: "Ceza davalarında savunma belgesi yazmaz" },
    },
    lawyer: {
      title: "Avukat",
      does: { 1: "Senaryoları onaylar: mevzuat, süreler, muhataplar", 2: "Genel yoldaki her belgeyi başvurudan önce kontrol eder", 3: "Karmaşık dosyaları yürütür ve sizi temsil eder", 4: "Kurum sicilinin hukuki doğruluğundan sorumludur" },
    },
    promiseTitle: "Ne vaat ediyoruz, ne yapmıyoruz",
    promiseLead: "Büyük vaatler yok: yalnızca bize bağlı olanlar.",
    promise: { title: "Vaat ediyoruz", 1: "Dosyanız için anlaşılır bir yol", 2: "Hazır belge ve başvuru talimatı", 3: "Süre takibi ve hatırlatmalar", 4: "Gerektiğinde doğrulanmış avukat" },
    dont: { title: "Yapmıyoruz", 1: "Mahkemede sizi kendimiz temsil etmiyoruz; bunu platform avukatları yapar", 2: "Genel yol belgelerini avukat onayı olmadan sunmuyoruz", 3: "Ceza davalarında savunma belgesi yazmıyoruz", 4: "Kurum, mevzuat, süre ve harç uydurmuyoruz" },
    safetyTitle: "Güvenlik",
    safety: {
      emergency: { title: "Acil durumlar", text: "Hayati tehlike, şiddet varsa veya bir çocuk tehlikedeyse önce ülkenin acil numaralarını gösteririz." },
      falseReport: { title: "Gerçeğe aykırı ihbar", text: "Suç ihbarlarında sorumluluk konusunda uyarır, yorum değil olguları anlatmanızı isteriz." },
      abuse: { title: "Kötüye kullanıma karşı koruma", text: "Tek bir kişiye yönelik toplu şikâyetler, taciz, şantaj ve iftira elle incelemeye gider." },
    },
  },
  ds: {
    title: "Tasarım sistemi", lead: "Konsilier token'ları ve bileşenleri: telefonda ve bilgisayarda, beş dilde güven, açıklık ve erişilebilirlik.",
    colors: "Renkler", type: "Tipografi", buttons: "Butonlar", badges: "Seviye rozetleri", notices: "Bildirimler",
    noticesLead: "Acil numaralar, gerçeğe aykırı ihbar, hizmetin hukuki statüsü ve «Taslak» küçük yazı değil, bileşendir.",
    uplSample: "Konsilier.AI bir belge hazırlama hizmeti ve avukatlarla teknolojik aracıdır.",
    draftSample: "Senaryo henüz avukat tarafından onaylanmadı. Mevzuat ve süre atıfları kontrol edilmelidir.",
    forms: "Giriş alanları", progress: "Dosya aşamaları", board: "Dosya panosu", icons: "İkonlar",
  },
  errors: {
    title: "Bir şeyler ters gitti",
    saved: "Verileriniz kaydedildi, dosya kaybolmadı. Hata raporunu aldık. Devam etmek için sayfayı yenileyin.",
    translate: "Tarayıcıda otomatik sayfa çevirisi açıksa bu site için kapatın.",
    reload: "Sayfayı yenile",
    retry: "Tekrar dene",
  },
  admin: {
    title: "Yönetim",
    tabs: { queue: "İnceleme kuyruğu", board: "Pano", holds: "İncelemede", forums: "Kurum sicili", demand: "Talep", errors: "Tarayıcı hataları" },
    forum: "Muhatap", hold: "Bekletildi", release: "İncelemeden çıkar",
    forums: {
      registry: "Sicil (paketten)", registryLead: "Doğruluk kaynağı depodaki YAML'dır. Değişiklikler canlıya yalnızca avukat kontrollü PR ile girer.",
      newDraft: "Yeni kayıt (taslak)", draftNote: "Taslak şemaya göre kontrol edilir, ancak dışa aktarılıp PR'da kabul edilene kadar canlıyı etkilemez.",
      save: "Taslağı kaydet", saved: "Taslak kaydedildi", drafts: "Taslaklar",
    },
    demand: { title: "Genel yolda talep", lead: "Hangi durumlar hazır senaryo olmadan geliyor: sonraki doğrulanmış senaryolar için adaylar.", country: "Ülke", dispute: "Uyuşmazlık türü", level: "Seviye", count: "Dosya" },
    token: "Yönetici token'ı",
    save: "Giriş",
    needsReview: "Yalnızca needs_review",
    pendingApproval: "Onay bekleyenler",
    all: "Tümü",
    approve: "Onayla",
    reject: "Geri gönder",
    note: "Avukat yorumu",
    preview: "Belge metni",
    audit: "Günlük",
    closeCase: "Dosyayı kapat",
    waitlist: "Bekleme listesi",
    tick: "Hatırlatmaları çalıştır",
  },
};

export default tr;
