import type { Dict } from "./types";

const tr: Dict = {
  nav: {
    account: "Giriş",
    start: "Başla", cases: "Dosyalarım", admin: "Yönetim", lawyers: "Avukatlar", forLawyers: "Avukatlar için",
    howItWorks: "Nasıl çalışır", coverage: "Kapsam", menu: "Menü", language: "Dil",
    skip: "İçeriğe geç", main: "Ana menü",
  },
  legal: {
    disclaimer: "Konsiliér AI bir BT hizmetidir, hukuki yardım değildir: avukat veya hukuk danışmanı değiliz. Yapay zekâ yanıtları bilgi amaçlıdır, belgeler taslaktır; kararları siz verir, belgeleri kendiniz sunarsınız.",
    terms: "Kullanım Koşulları",
    accept: "Mesaj göndererek hizmet koşullarını kabul etmiş ve Konsiliér AI'nin hukuki yardım değil, bir BT hizmeti olduğunu anlamış olursunuz.",
    version: "sürüm",
    languageNote: "Koşullar Kazakça ve Rusça hazırlanmıştır; burada İngilizce çevirisi gösterilmektedir.",
  },
  footer: {
    said: "Konsiliér [kon-sil-YER] — hukuki konularda yapay zekâ asistanı",
    contacts: "İletişim",
    lawyerCabinet: "Avukat paneli",
    tagline: "Sorununuzu anlatın — Konsiliér AI ülkenizin yasalarına göre belgeyi hazırlar, nereye başvuracağınızı söyler, süreleri takip eder ve gerektiğinde doğrulanmış bir avukatı dahil eder.",
    product: "Ürün", lawyers: "Avukatlara", designSystem: "Tasarım sistemi", support: "Bize yazın",
  },
  level: {
    pending: { label: "Yol belirleniyor", desc: "Durumu inceliyoruz. Ne olduğu netleşince uygun yolu ve ilk adımı göstereceğiz." },
    verified: { label: "Avukat onaylı", desc: "Hazır senaryo: mevzuat, süreler ve muhataplar avukat tarafından onaylandı. Tamamen otomatik süreç." },
    scenario_draft: { label: "Sık görülen durum", desc: "Bu durum için hazır bir senaryo var: sorular, belge ve yapılacaklar. Mevzuat ve süre atıflarını avukat ayrıca kontrol eder." },
    universal: { label: "Size özel belge", desc: "Belgeyi durumunuza göre hazırlarız: metin anlattıklarınıza ve delillerinize göre, muhatap kurum sicilinden. İhtarname, şikâyet veya dilekçeyi adım adım talimatla kendiniz sunarsınız; dava dilekçesini avukat önceden kontrol eder." },
    lawyer: { label: "Avukat gerekli", desc: "Karmaşık veya riskli durum: dosyayı hazırlayıp doğrulanmış bir avukata iletiyoruz." },
    soon: { label: "Yakında", desc: "Şimdilik dosya kabul etmiyoruz. İletişim bilgilerinizi bırakın, açıldığımızda yazalım." },
  },
  path: {
    document: { title: "Belge", text: "Anlattıklarınıza ve delillerinize göre şikâyet, ihtarname, dilekçe veya dava dilekçesi." },
    forum: { title: "Nereye başvurulur", text: "Kurum veya kuruluş yalnızca doğrulanmış sicilden seçilir, uydurmayız." },
    deadline: { title: "Süreler", text: "Cevap süresini hesaplar ve hatırlatırız. Süre verilerde yoksa avukat netleştirir." },
    escalation: { title: "Ret veya cevapsızlık halinde", text: "Cevap yoksa veya ret geldiyse sonraki adımı hazırlarız: üst kurum, mahkeme." },
    lawyer: { title: "Avukat", text: "Gerektiğinde sonuçlara dayalı puanı olan doğrulanmış bir avukatı dahil ederiz." },
  },
  emergency: {
    title: "Önce güvenlik",
    continue: "Güvendeyim, devam et",
    sample: "Şu anda hayatınız veya sağlığınız tehlikedeyse acil servisleri arayın.",
  },
  metrics: {
    lead: "Yalnızca platformdaki gerçek dosyalar",
    users: "Kullanıcılar",
    cases: "Dosyalar",
    documents: "Belgeler",
    submitted: "Sunuldu",
    positive: "Lehine sonuçlandı",
    recovered: "Geri alınan",
    atStake: "Uyuşmazlık tutarı",
    medianDays: "Sonuca kadar medyan gün",
    funnel: "Dosya hunisi",
    table: "Haftalık tablo",
    week: "Hafta",
    topScenarios: "Popüler senaryolar",
    more: "Diğer",
    repeat: "Yeni dosyayla dönenler",
    lawyer: "Avukata devredildi",
    lawyerApps: "Avukat başvuruları",
    waitlist: "Bekleme listesi (diğer ülkeler)",
    countries: "Ülkeler",
    weekly: { cases: "Haftalık yeni dosyalar", users: "Haftalık yeni kullanıcılar", documents: "Haftalık belgeler", submitted: "Haftalık sunulan belgeler" },
    step: { created: "Oluşturuldu", classified: "Sınıflandırıldı", intake_done: "Görüşme tamam", document_ready: "Belge hazır", submitted: "Sunuldu", response: "Yanıt alındı", resolved_positive: "Lehine sonuçlandı" },
  },
  pwa: {
    install: "Uygulamayı yükle",
    iosSteps: "Safari'nin altındaki «Paylaş» (oklu kare) düğmesine, ardından «Ana Ekrana Ekle»ye dokunun — Konsiliér AI uygulamalarınız arasında görünür.",
    macSteps: "Safari'de «Dosya» → «Dock'a Ekle» menüsünü açın — Konsiliér AI ayrı bir pencerede açılır.",
    offlineTitle: "İnternet bağlantısı yok",
    offlineText: "Dosyalarınız sunucuda kayıtlı. Bağlantı gelince sayfayı yenileyin — her şey yerinde olacak.",
  },
  helper: {
    photo: "Fotoğraf çek",
    attach: "Dosya ekle",
    more: "Daha fazla örnek",
    examplesTitle: "Örnekler — kullanmak için dokunun",
    suggestTitle: "Buna mı benziyor?",
    servicesTitle: "Nereye başvurulur — neyin nereye gideceğini söyleriz",
    eotinish: "Devlet kurumlarına başvuru ve şikâyetler",
    sud: "Mahkemeye dava ve talepler",
    egov: "Belgeler ve kamu hizmetleri",
    step1: "Sorunu anlatın",
    step2: "Soruları yanıtlayın ve belgeleri ekleyin",
    step3: "Belgeyi indirin ve talimata göre başvurun",
    planTitle: "Önerilen çözüm",
    planDoc: "Hazırlayacağımız belge",
    planTo: "Kime",
    planVia: "Nasıl başvurulur",
    planAttach: "Hazırlayın ve ekleyin",
    planSelf: "Kendiniz başvurursunuz — adım adım talimat veririz",
    planLawyer: "Belgeyi başvurudan önce avukat kontrol eder",
    planUpload: "Belge yükle",
    examples: { 1: "Kaspi'den telefon aldım, bir hafta sonra bozuldu, satıcı parayı iade etmiyor", 2: "İşverenim üç aydır maaşımı ödemiyor", 3: "Haber vermeden işten çıkarıldım, tazminatım ödenmedi", 4: "Haberim olmadan adıma mikrokredi çekilmiş", 5: "Tahsilat şirketi başkasının borcu için arayıp tehdit ediyor", 6: "Pazaryeri siparişim gelmedi, para iade edilmiyor", 7: "Ev sahibi depozitoyu geri vermiyor", 8: "İşlemediğim bir ihlal için ceza yazıldı" },
    exampleCount: "8",
    doc_download: "İndir",
    doc_print: "Yazdır",
    doc_save: "Kaydet",
    doc_send: "Gönder",
    doc_sign: "E-imza ile imzala",
    doc_signUnavailable: "Sitede e-imza şu anda kullanılamıyor. Belgeyi başvuru sırasında doğrudan portalda (eOtinish, Sud Kabineti) e-imzayla ya da elle imzalayabilirsiniz.",
    doc_signed: "E-imza ile imzalandı",
    doc_fmtPdf: "PDF — yazdırmak ve sunmak için",
    doc_fmtWord: "Word — düzenlemek için",
    doc_toWhatsapp: "WhatsApp",
    doc_toTelegram: "Telegram",
    doc_toMail: "E-posta",
    doc_toOther: "Başka uygulama",
    doc_fileReady: "Dosya indirildi — açılan pencerede ekleyin.",
    doc_savedTo: "Kaydedildi",
  },
  cta: {
    pickSituation: "Durum seç",
    draftDocument: "Belge hazırla",
    title: "Sorunuzla başlayın.",
    lead: "Durumu kendi sözlerinizle anlatın — yolu gösterip ilk belgeyi hazırlayalım.",
    start: "Durumu anlat",
    lawyer: "Avukat bul",
    more: "Daha fazla",
    next: "İleri",
    startCase: "Dosya başlat",
    complain: "Şikâyet et",
    join: "Avukat mısınız? Katılın",
    caseLawyerTitle: "Avukat yardımı mı gerekiyor?",
    caseLawyerText: "Bir avukat belgelerinizi inceleyebilir veya dosyanın tamamını üstlenebilir.",
    lawyersLead: "Durumu anlatın — belgeleri hazırlarız, gerektiğinde bir avukatı dahil ederiz.",
  },
  app: {
    tabs: { home: "Ana sayfa", chat: "Sohbet", cases: "Dosyalar", documents: "Belgeler", profile: "Profil" },
    newQuestion: "Yeni soru",
    toSite: "Siteye dön",
    recent: "Son dosyalar",
    docs: { title: "Belgeler", lead: "Dosyalarınızdaki tüm belge taslakları tek yerde.", empty: "Henüz belge yok", emptyHint: "Durumunuzu sohbette anlatın — Konsiliér AI bilgileri toplayıp bir belge taslağı hazırlar.", create: "Belge hazırla", search: "Başlığa göre ara", draft: "Taslak", ready: "Sunulmaya hazır", submitted: "Sunuldu", open: "Dosyayı aç", count: "Belgeler: {n}" },
    digits: "{n} / {total}",
    back: "Geri",
    more: "Daha fazla",
    close: "Kapat",
    cancel: "İptal",
    roadmap: "Yol haritası",
    facts: "Dosya bilgileri",
    documents: "Belgeler",
    lawyer: "Avukat",
    gov: "eGov belgeleri",
    law: "Kanun hakkında soru",
    about: "Dosya ve hizmet hakkında",
    account: "Hesabım",
    home: "Ana sayfa",
    photo: "Fotoğraf çek",
    file: "Dosya seç",
    today: "Bugün",
    yesterday: "Dün",
    noFacts: "Henüz bilgi yok — sohbetteki soruları yanıtlayın.",
    chat: "Danışmanlık",
    hint: {
      digits: "Yalnızca rakam: {n} hane.",
      date: "Takvimden tarihi seçin veya «Bugün» / «Dün» düğmesine dokunun.",
      money: "Yalnızca rakam — boşlukları biz ekleriz.",
      number: "Bir sayı girin.",
      phone: "Telefon numarası, ör. +7 700 000 00 00.",
      email: "E-posta adresi.",
      text: "Kısa bir yanıt.",
    },
  },
  chat: {
    freeShort: "Danışmanlık ücretsiz",
    provider: {
      gemini: "Yanıtları ücretsiz Google Gemini yapay zekâsı hazırlar. Adları, kimlik numaralarını ve telefonları göndermeden önce etiketlerle değiştiririz; Google yazışmayı modellerini geliştirmek için kullanabilir — gereksiz kişisel bilgi yazmayın.",
      anthropic: "Yanıtları Anthropic Claude yapay zekâsı hazırlar. Adları, kimlik numaralarını ve telefonları göndermeden önce etiketlerle değiştiririz.",
    },
    eyebrow: "Ücretsiz danışmanlık",
    title: "Ne olduğunu anlatın",
    lead: "Yazın ya da sesli söyleyin, fotoğraf ve belge ekleyin. Danışmanlık ücretsiz: haklarınızı ve sonraki adımları anlatırız.",
    placeholder: "Durumu anlatın veya bir soru sorun",
    send: "Gönder",
    attach: "Dosya ekle",
    remove: "Dosyayı kaldır",
    mic: "Sesli söyle",
    micStop: "Kaydı durdur",
    listening: "Konuşun — dinliyorum…",
    micNote: "Sesi tarayıcınız tanır; Chrome'da kayıt Google hizmetinde işlenir.",
    speak: "Sesli oku",
    stopSpeak: "Durdur",
    voiceOn: "Sesli yanıtlar: açık",
    voiceOff: "Sesli yanıtlar: kapalı",
    thinking: "Düşünüyorum…",
    lookingUp: "Kanunun resmî metnine bakıyorum…",
    article: "Madde {n}",
    doc: "Belge hazırla",
    docPrice: "1.990 ₸'den itibaren",
    lawyer: "Hukukçu veya avukat",
    lawyerPrice: "ücretli ve ücretsiz",
    free: "Danışmanlık ücretsizdir. Konsiliér AI bir yapay zekâ asistanıdır, avukatın yerini tutmaz.",
    open: "Sohbette danışmanlık",
    errors: {
      agent_unavailable: "Sohbet danışmanı şu anda kullanılamıyor. Daha sonra deneyin veya belgeyi adım adım hazırlayın.",
      agent_failed: "Danışman yanıt veremedi. Bir dakika sonra tekrar deneyin.",
      too_many_messages: "Bugünkü ücretsiz mesaj hakkı doldu. Yarın devam edelim — veya belgeyi adım adım hazırlayın.",
      busy: "Şu anda yoğunluk var, lütfen bir dakika sonra tekrar deneyin.",
    },
  },
  home: {
    eyebrow: "Konsiliér [kon-sil-YER] — hukuki konularda yapay zekâ asistanı",
    title: "Hukuki sorular. Anlaşılır yanıtlar.",
    sub: "Ne olduğunu anlatın. Belgeyi hazırlarız, nereye başvuracağınızı söyleriz, süreleri takip ederiz. Avukat gerekirse doğrulanmış birini dahil ederiz.",
    promise1: "Şikâyetinizi veya dilekçenizi yasaya uygun olarak sizin için yazarız",
    promise2: "Tam olarak nereye göndereceğinizi söyleriz",
    promise3: "Süreleri hatırlatır, sonra ne yapacağınızı söyleriz",
    promise4: "Dosyanız karmaşıksa bir avukatı dahil ederiz",
    describe: "Ne olduğunu anlatın",
    cta: "Ücretsiz danışmanlık al",
    privacy: "İsimleri ve belge numaralarını yapay zekâ işlemeden önce etiketlerle değiştiriyoruz. Belgeler sizin adınıza sunulur.",
    mySituation: "Benim durumum",
    mySituationText: "Listede yok mu? Kendi sözlerinizle anlatın — ne yapmanız gerektiğini söyleyelim.",
    situationsEyebrow: "Hayattan durumlar",
    situationsTitle: "Nereden başlayalım?",
    situationsLead: "Hangi hukuk dalı olduğunu bilmeniz gerekmez. Benzer bir durumu seçin ya da kendinizinkini anlatın.",
    pathEyebrow: "Yol haritası",
    pathTitle: "Dosyanız nasıl ilerler",
    pathLead: "Her adımda kimin kontrol ettiği ve avukatın ne zaman devreye girdiği görünür.",
    levelsEyebrow: "Kapsam konusunda şeffafız",
    levelsTitle: "Üç seviye: dosyanızın hangisinde olduğunu hep bilirsiniz",
    levelsLead: "Tüm yol boyunca yanınızdayız: belge, başvuru, süre takibi ve gerektiğinde avukat.",
    howLink: "Nasıl çalıştığı hakkında daha fazla",
    coverageTitle: "Kazakistan'da çalışıyoruz. BDT ve Orta Doğu yakında",
    coverageLead: "Özbekistan, Kırgızistan, Azerbaycan, Türkiye, BAE, Suudi Arabistan ve diğer ülkeler açılış planında.",
    coverageCta: "Ülkelere göre kapsam",
    stepsTitle: "Sorudan bir sonraki adıma",
    steps: {
      share: "Bunun uygun olacağı meslektaşlarınız var mı? Onlara bağlantıyı gönderin.",
      s1t: "Ne olduğunu anlatın",
      s1d: "Yazarak veya sesli. Fiş, sözleşme ve yazışma fotoğrafları ekleyebilirsiniz.",
      s2t: "Ücretsiz danışmanlık alın",
      s2d: "Haklarınızı ve sonraki adımları, kanunların resmî metinlerine bağlantılarla anlatırız.",
      s3t: "Belgeyi sunun veya bir avukata başvurun",
      s3d: "İhtarname, şikâyet veya dava dilekçesini hazırlar, süreleri hatırlatırız. Karmaşık dosyaları doğrulanmış bir avukata aktarırız.",
    },
    priceTitle: "Ücretler",
    price: {
      chatT: "Danışmanlık",
      chatP: "Ücretsiz",
      chatD: "Sohbette sorular ve yanıtlar, yazarak veya sesli.",
      docT: "Belge",
      docP: "1.990 ₸'den itibaren",
      docD: "İhtarname, şikâyet, dilekçe veya dava dilekçesi ve nereye, nasıl sunulacağına dair talimat.",
      lawyerT: "Hukukçu veya avukat",
      lawyerP: "Ücreti avukat belirler",
      lawyerD: "İnsan hakları kuruluşları ücretsiz yardım eder.",
    },
    trustTitle: "Neden bize güvenebilirsiniz",
    trust: {
      t1: "Yalnızca kanunların resmî metinlerine atıf yaparız («Adilet» hukuki bilgi sistemi).",
      t2: "Adlar, kimlik numaraları ve telefonlar yapay zekâ işlemeden önce etiketlerle değiştirilir.",
      t3: "Belgeyi kendi adınıza kendiniz sunarsınız — kararınız olmadan hiçbir şey göndermeyiz.",
    },
    more: "Daha fazla",
  },
  situations: {
    cheated: { label: "Alışverişte mağdur oldum", hint: "Ürün, hizmet, pazaryeri, para iadesi.", placeholder: "Ne aldınız, kimden, ne zaman, kaça ve ne ters gitti" },
    fired: { label: "İşten çıkarıldım veya maaş ödenmiyor", hint: "İşten çıkarma, maaş alacağı, ayrımcılık.", placeholder: "Nerede çalışıyorsunuz, ne oldu ve ne zaman, ne kadar borçlular" },
    family: { label: "Boşanma ve çocuklar", hint: "Boşanma, nafaka, velayet, mal paylaşımı.", placeholder: "Kısaca: ne oluyor ve ne elde etmek istiyorsunuz" },
    fine: { label: "Para cezası", hint: "Para cezasına veya karara itiraz.", placeholder: "Ceza ne için, kim yazdı, ne zaman ve neden katılmıyorsunuz" },
    crime: { label: "Bana karşı suç işlendi", hint: "Hırsızlık, dolandırıcılık, darp. Yalnızca olgular: ne, nerede, ne zaman.", placeholder: "Ne oldu, nerede ve ne zaman, kim gördü, zarar ne" },
    stateBody: { label: "Kamu kurumuyla uyuşmazlık", hint: "Ret, işlem yapmama, başvuruya cevap verilmemesi.", placeholder: "Hangi kurum, ne talep ettiniz ve ne cevap verdiler" },
    bank: { label: "Banka, kredi, tahsilat şirketleri", hint: "Adınıza çekilen kredi, bankayla uyuşmazlık, tahsilatçı baskısı.", placeholder: "Hangi banka veya finans şirketi, ne oldu, hangi tutarlar" },
    business: { label: "Ticari uyuşmazlık", hint: "Karşı tarafın borcu, sözleşme ihlali.", placeholder: "Sözleşme kiminle, ne ihlal edildi, tutar ne" },
    inheritance: { label: "Miras", hint: "Mirasın kabulü, mirasçılar arası uyuşmazlık.", placeholder: "Kim ve ne zaman vefat etti, mirasçılar kim, sorun ne" },
    housing: { label: "Konut ve komşular", hint: "Kira, elektrik-su-doğalgaz faturaları, komşular.", placeholder: "Nasıl bir konut, uyuşmazlık kiminle, ne oldu" },
  },
  board: {
    intake: "Başvuru", qualified: "Bilgiler toplandı", action_ready: "Belge hazır", submitted: "Sunuldu, cevap bekleniyor",
    escalated: "Üst başvuru", handed_to_lawyer: "Avukatta", resolved: "Çözüldü",
    empty: "Boş", stepOf: "Aşama {n} / {total}",
    attention: { hold: "İncelemede", ack: "Onay gerekli", expired: "Cevap süresi doldu", approval: "Avukat kontrolü bekleniyor", chooseForum: "Muhatabı seçin" },
  },
  ack: {
    false_report: { title: "Bilerek gerçeğe aykırı ihbarın sorumluluğu", button: "Anladım ve onaylıyorum", text: "Bilerek gerçeğe aykırı ihbar ve şikâyette bulunmanın cezai sorumluluğu vardır. Yalnızca bildiğiniz olguları anlatın." },
    special_category: { title: "Özel nitelikli verilerin işlenmesine onay", button: "Onay veriyorum", text: "Dosyada sağlık, din veya sabıka bilgileri olabilir. En az veriyi saklar ve yalnızca belgeniz için kullanırız." },
  },
  forum: {
    chooseTitle: "Nereye başvurulur",
    chooseLead: "Muhatabı seçin. Liste yalnızca bu ülkenin kurum sicilinden; farklar aşağıda gösteriliyor.",
    type: { court: "Mahkeme", prosecutor: "Savcılık", police: "Polis", regulator: "Düzenleyici kurum", ministry: "Bakanlık",
      ombudsman: "Ombudsman", local_authority: "Yerel yönetim", arbitration: "Tahkim", mediation: "Arabuluculuk",
      private_org: "Kuruluş" },
    effect: { binding: "Karar bağlayıcı", advisory: "Tavsiye niteliğinde karar", none: "Hukuki etkisi yok" },
    verified: "Avukat onaylı", unverified: "Bilgileri avukat netleştirecek", deadlineByLawyer: "Süreyi avukat netleştirecek",
    channels: "Nasıl başvurulur", channel: { portal: "çevrimiçi portal", email: "e-posta", post: "posta", in_person: "şahsen", whatsapp: "WhatsApp", telegram: "Telegram" },
    choose: "Seç",
  },
  common: { loading: "Yükleniyor…", sending: "Gönderiliyor…" },
  roadmap: {
    title: "Dosyanın yol haritası",
    best: "En iyi durum",
    worst: "Tüm adımlar gerekirse",
    openEnded: "ardından avukatla çalışma, süreler anlaşmaya göre",
    done: "Tamamlandı",
    current: "Şimdi",
    upcoming: "Sonra",
    skipped: "Gerek kalmadı",
    ifNeeded: "gerekirse",
    due: "süre",
    estimated: "tahmini",
    finished: "tamamlandı",
    todoNorm: "süreyi avukat netleştiriyor",
  },
  trust: {
    title: "Dolandırıcılığa ve boş vaatlere karşı nasıl koruyoruz",
    verifiedTitle: "Yalnızca doğrulanmış avukatlar",
    verified: "Avukat veya hukuk danışmanı statüsü sicillerden kontrol edilir, kimlik e-imza ile doğrulanır. Doğrulama yoksa müvekkillere erişim de yok.",
    escrowTitle: "Aşamalı ödeme, para güvencede",
    escrow: "Her şeyi peşin ödemezsiniz. Tutar ödeme ortağında bloke edilir ve avukata ancak aşama tamamlanınca aktarılır: ihtarname gönderildi, cevap alındı, dava açıldı.",
    ratingTitle: "Kanıtlanmış sonuçlara dayalı puan",
    rating: "Puan platformdaki gerçek dosyalara göre hesaplanır: zorluğa göre düzeltilmiş kazanılan dosyalar, geri alınan para, sürelere uyum. Yorumlar yalnızca anlaşmadan sonra.",
    roadmapTitle: "Dosyanızın nerede olduğunu görürsünüz",
    roadmap: "Yol haritası: ne yapıldı, şimdi ne var, sonraki adımlar ne ve karar ne zaman beklenir; en iyi ve en kötü durum.",
    soon: "Avukatla güvenli işlem geliştiriliyor",
    more: "Ayrıntılar",
    less: "Daha az göster",
    now: "Şimdi",
    verifiedMore: "Avukat: baroya kayıt ve geçerli ruhsat.\nHukuk danışmanı: hukuk danışmanları odasına üyelik.\nKimlik e-imza ile doğrulanır; başkasının adıyla çalışılamaz.\nRuhsat iptal edilirse veya odadan çıkarılırsa profil gizlenir.",
    verifiedNow: "Avukat başvurularını şu an ekip belgelere göre elle kontrol ediyor. Sicillerle otomatik kontrol ve e-imza ile giriş geliştiriliyor.",
    verifiedLink: "Platform avukatı nasıl olunur",
    escrowMore: "Ücret ve aşamalar iş başlamadan sözleşmede belirlenir.\nAşama ücreti avukatta değil, ödeme ortağında bloke edilir.\nAvukat, aşama onaylanınca ödemeyi alır: belge sunuldu, cevap alındı.\nAşama yapılmazsa o aşamanın parası size iade edilir.\nAnlaşmazlıkları platform dosyadaki belgelere göre inceler.",
    escrowNow: "Özellik geliştiriliyor: Kazakistan'da ödeme ortağı seçiyoruz. Açılışa kadar avukatlara dosyanın tamamı için peşin ödeme yapmayın.",
    ratingMore: "Sonuç, avukatın beyanıyla değil, dosya platformda kapatılırken kaydedilir.\nSonuç aynı kategorinin ortalamasıyla karşılaştırılır; kolay dosyalar puanı şişirmez.\nBileşim: başarı %45, sürelere uyum %20, geri alınan para %20, yorumlar %15.\nYeni avukatların puanı 30+ dosyaya ulaşana kadar platform ortalamasına çekilir.\nYorum yalnızca gerçek bir anlaşmadan sonra bırakılabilir.",
    ratingNow: "Şimdilik demo profillerle örnek gösteriliyor: gerçek puan, avukatlar platformda ilk dosyaları kapattığında görünecek.",
    ratingLink: "Örnek puanı gör",
    roadmapMore: "Dosyanın her adımı: ihtarname, cevap bekleme, düzenleyici kuruma şikâyet, dava.\nHer adım için yasal süre ve bitiş tarihi.\nİki tahmin: en iyi (ihtarnameden sonra çözüldü) ve tüm adımlar gerekirse.\nHiçbir süreyi kaçırmamanız için hatırlatırız.",
    roadmapNow: "Şu an çalışıyor: yol haritası her dosyada durumu anlattıktan hemen sonra açılır.",
    roadmapLink: "Dosya başlat",
    cta: "Örnek puanı gör",
    joinLawyer: "Avukat mısınız? Katılın",
  },
  request: {
    back: "Avukatlar ve hukukçular",
    title: "Avukata başvuru",
    lead: "Durumu anlatın ve iletişim bilgilerinizi bırakın. Dosyayı kaydeder, belgelerle birlikte bir avukata aktarırız.",
    story: "Ne oldu",
    contacts: "İletişim bilgileriniz",
    name: "Ad soyad",
    phone: "Telefon",
    email: "E-posta (isteğe bağlı)",
    consent: "Konsiliér AI'nin dosyayı bir avukata aktarabilmesi için kişisel verilerimin işlenmesine onay veriyor ve şunu kabul ediyorum:",
    submit: "Başvuruyu gönder",
    note: "Belirli bir avukattan randevu, ödeme ortağı üzerinden ödemeyle birlikte açılacak. Şimdilik dosyayı ilgili alanda doğrulanmış bir avukata aktarır, size haber veririz.",
    doneTitle: "Başvuru kaydedildi",
    doneText: "Dosya oluşturuldu, iletişim bilgileriniz kaydedildi. Dosya bir avukata aktarıldığında sizinle iletişime geçeceğiz.",
    proceed: "Dosyayı tamamla",
    continueHint: "Birkaç soruyu yanıtlayın ve belgeleri ekleyin — avukat eksiksiz bir dosya alır ve hemen ücret söyleyebilir.",
  },
  lawyers: {
    filter: "Göster",
    all: "Tüm avukatlar",
    freeOnly: "Ücretsiz",
    freeNote: "İnsan hakları kuruluşları ve pro bono avukatlar ücretsiz yardım eder. Bazı konularda (nafaka, emeklilik ve yardımlar vb.) devlet güvenceli ücretsiz hukuki yardım barolar ve hukuk danışmanları odaları aracılığıyla da verilir.",
    freeNone: "Dizinde henüz ücretsiz avukat yok.",
    title: "Avukatlar ve hukukçular",
    subtitle: "Puan reklama değil, platformdaki kanıtlanmış sonuçlara dayanır.",
    score: "Puan",
    confidence: { low: "az dosya", medium: "orta örneklem", high: "geniş örneklem" },
    vsBaseline: "platform ortalamasına göre",
    cases: "platformdaki dosya",
    recovered: "geri alınan para",
    onTime: "zamanında aşama",
    reviews: "anlaşma sonrası yorumlar",
    from: "başlangıç",
    proBono: "ücretsiz (pro bono)",
    response: "ortalama yanıt süresi",
    hours: "sa",
    years: "yıl deneyim",
    verifiedLicense: "Ruhsat doğrulandı",
    verifiedId: "Kimlik doğrulandı",
    success: "başarı",
    platform: "ortalama",
    methodTitle: "Puan nasıl hesaplanır",
    method1: "Yalnızca platformdan geçen dosyalar: sonuç avukatın beyanıyla değil, dosya kapatılırken kaydedilir.",
    method2: "Sonuç aynı kategorideki dosyaların ortalamasıyla karşılaştırılır; kolay dosya seçmek puanı yükseltmez.",
    method3: "Küçük örneklem ortalamaya çekilir: 3'te 3 galibiyet, 220'de 180'i geçemez.",
    method4: "Ağırlık: başarı %45, aşama sürelerine uyum %20, geri alınan para oranı %20, anlaşma sonrası yorumlar %15.",
    choose: "Başvur",
    chooseSoon: "Avukata doğrudan başvuru henüz mümkün değil: bir dosya başlatın, toplanan belgelerle birlikte avukata aktaralım.",
    pp: "puan",
    mln: "mn",
    details: "Sonuçlar hakkında daha fazla",
    sample: "Örnek",
    newProfile: "Platformun yeni ortağı: puan, ilk tamamlanan dosyalardan sonra görünecek.",
  },
  landing: {
    promise: "Dosyanız: ilk belgeden sonuca kadar",
    sub: "Durumu kendi sözlerinizle anlatın. Konsiliér AI, Kazakistan yasalarına göre ihtarname veya şikâyet hazırlar, nereye başvuracağınızı söyler ve süreleri takip eder. Bu yetmezse platformun profesyonel avukatı dosyayı sonuna kadar götürür.",
    usp1: "Hazır belgeler: avukat aramadan, internetten şablon bulmadan",
    usp2: "Süreler kontrol altında: hatırlatır, sonraki adımı hazırlarız",
    usp3: "Platform avukatları: doğrulanmış, gerçek sonuçlara dayalı puanlı",
    startWeb: "Sitede başla",
    startTelegram: "Telegram'da aç",
    scenariosTitle: "Şu an neler yapabiliyoruz",
    howTitle: "Nasıl çalışır",
    how1: "Ne olduğunu anlatın",
    how2: "Kısa soruları yanıtlayın, fiş veya ekran görüntülerini yükleyin",
    how3: "Belgeyi ve başvuru talimatını alın",
    how4: "Cevap süresini takip eder, sonraki adımı öneririz",
    countryTitle: "Ülkeniz",
    countryLive: "Mevcut",
    countrySoon: "Yakında",
    waitlistTitle: "Bu ülkede henüz hizmet vermiyoruz",
    waitlistText: "İletişim bilgilerinizi bırakın, açıldığımızda yazalım.",
    waitlistContact: "E-posta veya Telegram",
    waitlistProblem: "Hangi sorunla karşılaştınız? (isteğe bağlı)",
    waitlistSend: "Açılışta haber ver",
    waitlistDone: "Teşekkürler! Açıldığımızda yazacağız.",
    price: "Ücret",
    disclaimer: "Belgeler sizin adınıza sunulur; her adımı siz kontrol edersiniz.",
  },
  start: {
    eyebrow: "Yeni dosya",
    country: "Ülke: Kazakistan.",
    otherCountry: "Başka ülke",
    busy: "Durumu inceliyoruz… Bu bir dakika sürebilir.",
    title: "Ne oldu?",
    placeholder: "Örneğin: 12.08.2026'da internet mağazasından 150 000 tengeye telefon aldım, bir hafta sonra bozuldu, parayı iade etmiyorlar",
    submit: "Devam et",
  },
  case: {
    back: "Tüm dosyalar",
    untitled: "Yeni dosya",
    holdTitle: "Dosya elle incelemede",
    draftTitle: "Taslak",
    lawyerTitle: "Dosya avukata iletiliyor",
    lawyerCta: "Doğrulanmış avukatlar",
    lawyerText: "Açıklamanızı kaydettik ve dosyayı platformun doğrulanmış bir avukatına iletiyoruz.",
    uplTitle: "Biz kimiz",
    thinking: "Yanıt hazırlanıyor… Yavaş bağlantıda bir dakika sürebilir.",
    working: "İşleniyor… Sayfayı kapatmayın.",
    send: "Yanıtla",
    answerPlaceholder: "Yanıtınız",
    more: "Açıklamayı tamamla",
    morePlaceholder: "Tam olarak ne aldınız veya yaptırdınız, kimden, ne zaman, hangi tutara ve ne ters gitti",
    skip: "Atla",
    doneUploading: "Devam et",
    upload: "Dosya yükle",
    uploadHint: "Fotoğraf veya PDF, en fazla 15 MB",
    found: "Dosyada bulduklarımız",
    confirm: "Bilgiler doğru",
    nothingFound: "Dosya kaydedildi. Veriler otomatik okunamadı.",
    facts: "Dosya bilgileri",
    prepare: "Belgeyi hazırla",
    handoff: "Avukata ilet",
    awaitingApproval: "Belge avukat kontrolünde. Hazır olduğunda haber vereceğiz.",
    rejected: "Avukat belgeyi düzeltme için geri gönderdi.",
    download: "İndir",
    instructions: "Nasıl başvurulur",
    submitted: "Belge sunuldu",
    sendEmail: "Muhataba e-postayla gönder",
    deadline: "Cevap süresi",
    gotResponse: "Yanıt alındı",
    noResponse: "Yanıt gelmedi",
    responsePlaceholder: "Cevap metnini yapıştırın",
    responseSend: "Yanıtı incele",
    responseFile: "veya cevap dosyasını yükleyin",
    close: "Dosyayı sonuçlandır",
    closeWon: "Tamamen çözüldü",
    closePartial: "Kısmen çözüldü",
    closeLost: "Çözülmedi",
    amountRecovered: "Alınan tutar",
    outcome: "Sonuç",
    days: "gün",
    response: "Cevap",
    notifications: "Bildirimler",
    datePlaceholder: "GG.AA.YYYY",
    classes: { full: "Talep karşılandı", partial: "Kısmen karşılandı", refusal: "Ret", none: "Yanıt yok" },
    deadlineStatus: { active: "işliyor", met: "cevap alındı", expired: "doldu", cancelled: "iptal edildi" },
    submittedHint: "Belgeyi muhataba kendiniz teslim ettiğinizde veya gönderdiğinizde dokunun. O günden itibaren yanıt süresini sayar ve hatırlatırız.",
  },
  cases: {
    title: "Dosyalarım", empty: "Henüz dosyanız yok", open: "Aç", new: "Yeni dosya",
    lead: "Sorular, belgeler ve sonraki adımlar bir arada.",
    emptyHint: "Ne olduğunu anlatın — danışmanlık ücretsiz.",
  },
  coverage: {
    eyebrow: "Kapsam",
    title: "Nerede ve hangi konularda yardım ediyoruz",
    lead: "Ülkelere ve hukuk dallarına göre neler çalışıyor: hazır senaryolar nerede, belgeyi nerede size özel hazırlarız ve neler yakında geliyor.",
    legend: "Durumlar ne anlama gelir",
    liveLead: "Bu ülkedeki her hukuk dalının durumu.",
    plannedTitle: "Yakında: BDT ve Orta Doğu",
    plannedLead: "Bu ülkeler için yerel avukatlarla doğrulanmış veriler hazırlıyoruz. Şimdilik dosya kabul etmiyoruz.",
    waitlistTitle: "Açılışta bana haber ver",
    sourcesTitle: "Resmî hukuk kaynakları",
    sourcesLead: "Yalnızca resmî devlet veri tabanlarına bağlantı veriyor ve onlardan alıntı yapıyoruz. Bağlantılar yeni sekmede açılır.",
    sourceKind: { legislation: "Mevzuat", case_law: "İçtihat", gazette: "Resmî gazete", registry: "Sicil" },
  },
  how: {
    eyebrow: "Nasıl çalışır",
    title: "Konsiliér AI — hukuki konularda yapay zekâ asistanı",
    lead: "Sorununuzu anlatın — Konsiliér AI ülkenizin yasalarına göre belgeyi hazırlar, nereye başvuracağınızı söyler, süreleri takip eder ve gerektiğinde doğrulanmış bir avukatı dahil eder.",
    pathTitle: "Dosyanız nasıl ilerler",
    pathLead: "Belge → nereye başvurulur → cevap süresi → sonraki adım → avukat.",
    levelsTitle: "Üç kapsam seviyesi",
    levelsLead: "Seviye otomatik belirlenir ve dosyada her zaman gösterilir.",
    level: {
      verified: { title: "Doğrulanmış senaryo", when: "Avukatın mevzuatı, süreleri ve muhatapları onayladığı sık durumlar için.", get: { 1: "Doğrulanmış şablona göre belge", 2: "Yasadan cevap süreleri ve hatırlatmalar", 3: "Önceden bilinen zincire göre sonraki adım" } },
      universal: { title: "Size özel belge", when: "Hazır senaryo yoksa, ama hukuk dalı belliyse ve sicilde uygun bir kurum varsa.", get: { 1: "Anlattıklarınıza ve delillerinize göre hazırlanan belge", 2: "Adım adım talimat: nereye, nasıl ve ne eklenecek; dava dilekçesi avukat kontrolünden sonra", 3: "Mevzuat ve süreler yalnızca verilerden; yoksa «avukat netleştirecek»" } },
      lawyer: { title: "Avukata devir", when: "Ceza davasında savunma tarafı, çocuklar, yüksek tutarlar, dolmak üzere olan süreler, belirsiz durum.", get: { 1: "Anlatımınıza göre dosya özeti", 2: "Sonuçlara dayalı puanı olan doğrulanmış avukat", 3: "Savunma belgelerini yalnızca avukat yazar" } },
    },
    rolesTitle: "Kim ne yapar",
    ai: {
      title: "Yapay zekâ",
      does: { 1: "Anlattıklarınızı anlar ve kısa sorular sorar", 2: "Olayların özetini yazar ve talepleri formüle eder", 3: "Muhatabın cevabını okur ve sonraki adımı önerir", 4: "Yalnızca anonimleştirilmiş verilerle çalışır" },
      neverTitle: "Yapay zekâ asla",
      never: { 1: "Mevzuat, madde ve süre uydurmaz", 2: "Başvurulacak kurumu seçmez", 3: "Din veya etnik köken belirlemez", 4: "Ceza davalarında savunma belgesi yazmaz" },
    },
    lawyer: {
      title: "Avukat",
      does: { 1: "Senaryoları onaylar: mevzuat, süreler, muhataplar", 2: "Mahkemeye verilecek dava ve şikâyet dilekçelerini sunulmadan önce kontrol eder", 3: "Karmaşık dosyaları yürütür ve sizi temsil eder", 4: "Kurum sicilinin hukuki doğruluğundan sorumludur" },
    },
    promiseTitle: "Ne vaat ediyoruz, ne yapmıyoruz",
    promiseLead: "Büyük vaatler yok: yalnızca bize bağlı olanlar.",
    promise: { title: "Vaat ediyoruz", 1: "Dosyanız için anlaşılır bir yol", 2: "Hazır belge ve başvuru talimatı", 3: "Süre takibi ve hatırlatmalar", 4: "Gerektiğinde doğrulanmış avukat" },
    dont: { title: "Yapmıyoruz", 1: "Mahkemede sizi kendimiz temsil etmiyoruz; bunu platform avukatları yapar", 2: "Avukat kontrolü olmadan mahkemeye dava açmıyoruz", 3: "Ceza davalarında savunma belgesi yazmıyoruz", 4: "Kurum, mevzuat, süre ve harç uydurmuyoruz" },
    safetyTitle: "Güvenlik",
    safety: {
      emergency: { title: "Acil durumlar", text: "Hayati tehlike, şiddet varsa veya bir çocuk tehlikedeyse önce ülkenin acil numaralarını gösteririz." },
      falseReport: { title: "Gerçeğe aykırı ihbar", text: "Suç ihbarlarında sorumluluk konusunda uyarır, yorum değil olguları anlatmanızı isteriz." },
      abuse: { title: "Kötüye kullanıma karşı koruma", text: "Tek bir kişiye yönelik toplu şikâyetler, taciz, şantaj ve iftira elle incelemeye gider." },
    },
  },
  ds: {
    title: "Tasarım sistemi", lead: "Konsiliér AI token'ları ve bileşenleri: telefonda ve bilgisayarda, beş dilde güven, açıklık ve erişilebilirlik.",
    colors: "Renkler", type: "Tipografi", buttons: "Düğmeler", badges: "Seviye rozetleri", notices: "Bildirimler",
    noticesLead: "Acil numaralar, gerçeğe aykırı ihbar, hizmetin hukuki statüsü ve «Taslak» küçük yazı değil, bileşendir.",
    uplSample: "Konsiliér AI, bir belge hazırlama hizmeti ve avukatlarla bağlantı kuran teknolojik bir aracıdır.",
    draftSample: "Senaryo henüz avukat tarafından onaylanmadı. Mevzuat ve süre atıfları kontrol edilmelidir.",
    forms: "Giriş alanları", progress: "Dosya aşamaları", board: "Dosya panosu", icons: "İkonlar",
  },
  errors: {
    title: "Bir şeyler ters gitti",
    saved: "Verileriniz kaydedildi, dosya kaybolmadı. Hata raporunu aldık. Devam etmek için sayfayı yenileyin.",
    translate: "Tarayıcıda otomatik sayfa çevirisi açıksa bu site için kapatın.",
    reload: "Sayfayı yenile",
    retry: "Tekrar dene",
  },
  admin: {
    lawyers: {
      lead: "Yalnızca e-imzayla yapılan ve lisans numarası kamu siciliyle karşılaştırılmış başvuruları onaylayın.",
      ecp: "E-imza",
      noEcp: "E-imza yok",
      license: "Lisans",
      nameDiffers: "Başvuruda başka bir ad var: {name}",
      verify: "Onayla",
      assign: "Avukata ilet",
      assignButton: "İlet",
      assigned: "{name} adlı avukata iletildi. İmzalanacak belgeler oluşturuldu.",
    },
    title: "Yönetim",
    tabs: { metrics: "Metrikler", lawyers: "Avukatlar", queue: "İnceleme kuyruğu", board: "Pano", holds: "İncelemede", forums: "Kurum sicili", demand: "Talep", errors: "Tarayıcı hataları" },
    forum: "Muhatap", hold: "Bekletildi", release: "İncelemeden çıkar",
    forums: {
      registry: "Sicil (paketten)", registryLead: "Doğruluk kaynağı depodaki YAML'dır. Değişiklikler canlıya yalnızca avukat kontrollü PR ile girer.",
      newDraft: "Yeni kayıt (taslak)", draftNote: "Taslak şemaya göre kontrol edilir, ancak dışa aktarılıp PR'da kabul edilene kadar canlıyı etkilemez.",
      save: "Taslağı kaydet", saved: "Taslak kaydedildi", drafts: "Taslaklar",
    },
    demand: { title: "Talep: hazır senaryosu olmayan durumlar", lead: "Hangi durumlar hazır senaryo olmadan geliyor: sonraki doğrulanmış senaryolar için adaylar.", country: "Ülke", dispute: "Uyuşmazlık türü", level: "Seviye", count: "Dosya" },
    token: "Yönetici token'ı",
    save: "Giriş yap",
    needsReview: "Yalnızca needs_review",
    pendingApproval: "Onay bekleyenler",
    all: "Tümü",
    approve: "Onayla",
    reject: "Geri gönder",
    note: "Avukat yorumu",
    preview: "Belge metni",
    audit: "Günlük",
    closeCase: "Dosyayı kapat",
    waitlist: "Bekleme listesi",
    tick: "Hatırlatmaları çalıştır",
  },
  account: {
    eyebrow: "Hesap",
    title: "Giriş ve kimlik doğrulama",
    lead: "Dosyalarınızı her cihazdan görmek için giriş yapın. E-imza (ЭЦП) veya eGov Mobile ile doğrulama kimliğinizi de teyit eder.",
    verifiedTitle: "Doğrulandı",
    waysTitle: "Giriş yöntemleri",
    soon: "Yakında",
    done: "Tamam: giriş yaptınız. Dosyalarınız artık hesabınıza bağlı.",
    privacy: "Kimlik numaranızın kendisini değil, şifrelenmiş bir özetini saklıyor ve yalnızca son hanelerini gösteriyoruz. Kodlar 10 dakika geçerlidir.",
    kind: {
      email: "E-posta",
      phone: "Telefon",
      iin: "Kimlik no",
    },
    email: {
      title: "E-posta ile",
      hint: "E-postanıza altı haneli bir kod göndeririz.",
      label: "E-posta adresi",
      sent: "{target} adresine kod gönderdik. «Spam» klasörünü de kontrol edin.",
    },
    phone: {
      title: "Telefon numarası ile",
      hint: "Kodu SMS ile göndeririz.",
      label: "Telefon numarası",
      sent: "{target} numarasına SMS ile kod gönderdik.",
    },
    ecp: {
      title: "E-imza (NCALayer)",
      hint: "Bilgisayarınızdaki e-imza anahtarı: dosya veya kimlik kartı. Kimliğinizi teyit eder.",
      step1: "NCALayer'ı kurun ve çalıştırın:",
      step2: "Düğmeye basın ve kimlik doğrulama anahtarını seçin (AUTH_RSA veya AUTH_GOST).",
      step3: "NCALayer penceresinde anahtar şifresini girin.",
      button: "E-imzayla giriş yap",
      waiting: "NCALayer'da imza bekleniyor…",
      not_running: "NCALayer çalışmıyor. Başlatıp tekrar deneyin.",
      cancelled: "İmzalama iptal edildi.",
      failed: "NCALayer imzalayamadı. Tekrar deneyin.",
    },
    egov: {
      title: "eGov Mobile",
      hint: "Girişi eGov Mobile veya eGov Business uygulamasında QR kodla onaylayın.",
      button: "QR kodu göster",
      scan: "eGov Mobile'da «Сканер QR» (QR tarayıcı) bölümünü açın ve kamerayı koda tutun.",
      onPhone: "Telefondaysanız uygulamayı düğmeyle açın:",
      waiting: "Uygulamada onay bekleniyor…",
      expired: "Süre doldu. Yeni kod oluşturun.",
      qrAlt: "eGov Mobile ile giriş için QR kod",
    },
    sendCode: "Kod al",
    codeLabel: "Mesajdaki kod",
    confirm: "Onayla",
    changeTarget: "Adresi değiştir",
    errors: {
      too_soon: "Kod az önce gönderildi. Bir dakika sonra tekrar isteyebilirsiniz.",
      rate_limited: "Çok fazla deneme. Bir saat sonra deneyin.",
      wrong_code: "Kod yanlış.",
      code_expired: "Kodun süresi doldu. Yenisini isteyin.",
      too_many_attempts: "Çok fazla hatalı deneme. Yeni kod isteyin.",
      invalid_email: "E-posta adresini kontrol edin.",
      invalid_phone: "Telefon numarasını kontrol edin, ör. +7 701 123 45 67.",
      method_unavailable: "Bu yöntem henüz kullanılamıyor.",
      send_failed: "Kod gönderilemedi. Daha sonra deneyin.",
      invalid_signature: "İmza doğrulanamadı.",
      certificate_invalid: "E-imza sertifikası geçersiz veya iptal edilmiş.",
      wrong_data: "Başka veriler imzalandı. Tekrar deneyin.",
      challenge_expired: "İmzalama süresi doldu. Tekrar deneyin.",
      verifier_unavailable: "İmza doğrulama geçici olarak kullanılamıyor. Daha sonra deneyin.",
      no_iin: "Sertifikada kimlik numarası yok.",
    },
  },
  sign: {
    signedByLawyer: "Avukat e-imzayla imzaladı: {name} ({id})",
    lead: "Belgeyi e-imzanızla imzalayın — imzalı belgeye itiraz etmek daha zordur. İmzalı dosya e-postayla birlikte gider.",
    ncalayer: "E-imza ile imzala (NCALayer)",
    egov: "eGov Mobile'da imzala",
    signedBy: "E-imzayla imzalandı: {name} ({id})",
    download: "İmzalı dosyayı indir (.cms)",
    verifyHint: "İmza ezSigner'da veya sigex.kz'de doğrulanabilir.",
    errors: {
      use_sign_key: "Giriş anahtarını (AUTH) değil, imza anahtarını (RSA veya GOST) seçin.",
      signer_mismatch: "Belgeyi başvuru sahibi imzalamalı: anahtardaki kimlik numarası dosyadakiyle eşleşmiyor.",
      document_changed: "Belge değişti. İmzalamayı yeniden başlatın.",
      wrong_data: "Başka bir dosya imzalandı. Tekrar deneyin.",
      awaiting_approval: "Belge hâlâ avukat incelemesinde.",
    },
  },
  agreements: {
    yourLawyer: "Avukatınız",
    unreviewed: "Bunlar platform şablonlarıdır ve platform avukatı henüz incelemedi. Şartları işi üstlenen avukat kontrol eder ve imzasıyla onaylar.",
    leadCustomer: "E-imzanızla imzalayın, ardından avukat imzalar.",
    leadLawyer: "Müvekkil imzaladı. Şartları kontrol edin ve kayıtlı e-imzanızla imzalayın.",
    waitCustomer: "Müvekkilin imzası bekleniyor.",
    waitLawyer: "Avukatın imzası bekleniyor.",
    status: {
      awaiting_customer: "Müvekkil imzası bekleniyor",
      awaiting_lawyer: "Avukat imzası bekleniyor",
      signed: "İki taraf da imzaladı",
    },
    kind: {
      advocate: "Avukat",
      legal_consultant: "Hukuk danışmanı",
      human_rights: "İnsan hakları savunucusu",
      other: "Hukukçu",
    },
  },
  invite: {
    title: "İhtiyacı olanları davet edin",
    lead: "Bağlantınızı benzer bir sorunu olan arkadaşlarınıza ve yakınlarınıza gönderin. Danışmanlık onlar için ücretsiz.",
    share: "Bağlantıyı paylaş",
    copied: "Bağlantı kopyalandı",
    invited: "Bağlantınızla gelenler: {n}",
    chatAsk: "İşinize yaradı mı? Bağlantıyı benzer durumdaki birine gönderin.",
    shareText: "Konsiliér AI — hukuki konularda ücretsiz yapay zekâ danışmanlığı. Durumunuzu anlatın, ne yapmanız gerektiğini söylesin:",
  },
  support: {
    title: "Bize yazın",
    lead: "Hizmetle ilgili bir soru sorun, bir sorunu bildirin veya bir iyileştirme önerin. Yanıt e-posta adresinize gelir ve bu sayfada görünür.",
    sentTitle: "{n} numaralı talebiniz alındı",
    sentText: "Bir iş günü içinde yanıt vereceğiz. Yanıt e-postanıza gelir ve aşağıda «Taleplerim» bölümünde görünür.",
    kind: "Konu",
    kinds: { question: "Soru", complaint: "Şikâyet", suggestion: "Öneri" },
    textLabel: { question: "Sorunuz", complaint: "Ne ters gitti", suggestion: "Neyi iyileştirebiliriz" },
    case: "Talep hangi dosyayla ilgili",
    noCase: "Bir dosyayla ilgili değil",
    contacts: "Yanıtı nereye gönderelim",
    contactHint: "E-posta veya telefon numarası girin — en az birini.",
    send: "Gönder",
    mine: "Taleplerim",
    status: { new: "Alındı", in_progress: "İnceleniyor", done: "Çözüldü" },
    team: "Konsiliér AI",
    you: "Siz",
    replyPlaceholder: "Yanıtla",
  },
  lawyer: {
    steps: {
      title: "Avukat olarak katılım",
      applied: "Başvuru gönderildi",
      appliedHint: "Kısa formu doldurun: statü, kuruluş, uzmanlık alanları.",
      ecp: "Kimliğinizi e-imzayla doğrulayın",
      ecpHint: "Zorunludur: başvurunun gerçekten size ait olduğunu gösterir; müvekkillerle belgeleri yalnızca bu e-imzayla imzalarsınız.",
      ecpDo: "E-imzayla doğrula",
      check: "Ekip tarafından statü kontrolü",
      checkHint: "Avukat veya hukuk danışmanı statünüzü sicilden kontrol eder, verdiğiniz iletişim bilgisiyle size ulaşırız. Genellikle 1–2 iş günü.",
      access: "Dosyalara erişim",
      accessHint: "Panel otomatik açılır: dosyalar, belgeler ve müvekkillerle sözleşme imzalama.",
      doneLead: "Tek adım kaldı: kimliğinizi e-imzayla doğrulayın, ardından başvuru statü kontrolüne gider.",
    },
    eyebrow: "Avukatlar için",
    title: "Avukat paneli",
    lead: "Platformun size ilettiği dosyalar ve müvekkille e-imzayla imzalanan belgeler.",
    ecpNeeded: "E-imzayla giriş yapın: kimliğinizi böyle doğrularız ve müvekkillerle belgeleri yalnızca bu e-imzayla imzalayabilirsiniz.",
    ecpSignIn: "E-imzayla giriş yap",
    ecpOk: "Kimlik e-imzayla doğrulandı",
    cabinetLink: "Avukat panelini aç",
    noApplication: "Henüz katılım başvurusu yapmadınız.",
    apply: "Başvur",
    noCases: "Size iletilmiş dosya henüz yok.",
    aboutProgram: "Ortaklık programı hakkında",
    status: {
      new: "Başvurunuz sicile göre kontrol ediliyor. Genellikle 1–2 iş günü sürer.",
      rejected: "Başvurunuz reddedildi. Hata olduğunu düşünüyorsanız bize yazın.",
      rejectedReason: "Gerekçe: {reason}",
    },
  },
  formErrors: {
    required: "Bu alanı doldurun",
    invalid: "Değeri kontrol edin",
    too_long: "Değer çok uzun",
    name_length: "2 ile 100 karakter arası",
    name_chars: "Yalnızca harf, boşluk, kısa çizgi ve kesme işareti — rakam, nokta veya başka işaret olmadan",
    name_words: "Soyadınızı ve adınızı eksiksiz yazın — en az iki kelime",
    phone_format: "Kazakistan telefon numarası: +7 ve 10 rakam, ör. +7 701 123 45 67",
    phone_operator: "+7'den sonra numara 7 ile başlamalı (701, 747, 777…). Kazakistan numarası girin",
    email_format: "E-postayı kontrol edin, ör. name@mail.kz",
    city_format: "Şehri harflerle yazın",
    license_format: "Yalnızca harf, rakam, «№», «/» ve kısa çizgi; en az bir rakam",
    kind_required: "Statünüzü seçin",
    license_number_required: "Avukat ve hukuk danışmanı için ruhsat veya belge numarası zorunludur",
    consent_required: "Veri işleme onayı olmadan başvuruyu kabul edemeyiz",
    phone_duplicate: "Bu numarayla bir başvuru zaten var — tekrar başvurmanıza gerek yok. Durumu avukat panelinde.",
    ecp_duplicate: "Bu e-imzayla bir başvuru zaten var. Durumu avukat panelinde.",
    too_many: "Bu adresten çok fazla başvuru yapıldı. Bir saat sonra tekrar deneyin.",
    fix: "Kırmızıyla işaretlenen alanları kontrol edin.",
  },
  gov: {
    ecpOnly: "E-imza gerekir",
    title: "egov.kz belgeleri",
    lead: "Bu belgeler dosyanızı güçlendirebilir. Onları egov.kz'den kendiniz alın — e-imzanızla veya eGov Mobile ile — ve buraya yükleyin: delillere eklenir.",
    needsEcp: "egov.kz girişi: e-imza veya SMS kodu",
    open: "Girişsiz",
    get: "egov.kz'den al",
    upload: "Belgeyi yükle",
    uploaded: "Yüklendi",
    disclaimer: "egov.kz'ye sizin adınıza girmiyoruz ve oradaki verilerinizi göremiyoruz — belgeyi kendiniz alırsınız.",
  },
  reports: {
    title: "Dosya raporları e-postayla",
    lead: "Dosyanız ilerlediğinde rapor göndeririz: nerede olduğu, ne yapıldığı ve ayrıntılı talimatlarla bir sonraki adım. Dosya durursa 3 günde bir hatırlatırız.",
    toggle: "{email} adresine gönder",
    needEmail: "Rapor almak için aşağıda e-postanızı doğrulayın («E-posta ile»).",
    hint: "Dosya raporlarını ve sonraki adım hatırlatmalarını e-postayla alın.",
    hintCta: "E-postayı doğrula",
  },
  law: {
    title: "Kanun hakkında soru",
    lead: "Dosyanız hakkında sorun. Yapay zekâ resmî «Әділет» portalında (adilet.zan.kz) normları bulur, maddeleri açar ve bağlantılarla yanıtlar — her alıntı resmî metinle karşılaştırılır.",
    placeholder: "Örneğin: işten çıkarıldıktan sonra işveren ödemeyi ne kadar sürede yapmalı?",
    ask: "Sor",
    busy: "Yasalarda arıyoruz…",
    busyHint: "Genellikle 20–60 saniye: yapay zekâ adilet.zan.kz'de maddeleri açar.",
    verified: "Normlar resmî metinle karşılaştırıldı",
    needsLawyer: "Avukat teyit edecek: tüm sonuçlar resmî metinle doğrulanmadı veya soru avukat gerektiriyor.",
    norms: "Yanıtın dayanağı",
    article: "Madde {n}",
    source: "adilet.zan.kz'de aç",
    dropped: "Doğrulanmayan atıflar çıkarıldı: {n}",
    disclaimer: "Bu, yasaların resmî metinlerine dayanan bir bilgidir, hukuki görüş değildir. Karmaşık durumlarda bir avukatı dahil ederiz.",
    errors: {
      agent_unavailable: "Kanunla ilgili yanıtlar henüz kullanılamıyor.",
      agent_failed: "Şu anda yanıtlanamadı. Biraz sonra tekrar deneyin.",
      too_many_questions: "Bugün bu dosyada çok soru soruldu. Yarın deneyin.",
    },
  },
};

export default tr;
