import type { LawyerText } from "./ru";

// Texts of /for-lawyers (English).
const en: LawyerText = {
    proPrice: "15,000–25,000 ₸/mo",
    pains: [
      ["Clients come with \"I was cheated\" and a pile of screenshots", "You get a ready case file: facts, dates, amounts, evidence, correspondence and a timeline, collected and checked by AI before it reaches you."],
      ["Ads are expensive, word of mouth is unpredictable", "Cases in your specialty and city come to you. You choose which ones to respond to and set your own price."],
      ["The client vanished after the first stage and didn't pay", "Stage-by-stage payment through escrow: the client pays in advance, and you get the money as soon as the stage is done."],
    ],
    benefits: [
      ["briefcase", "Ready cases", "A case file instead of an initial consultation: 1–2 hours saved on every client.", false],
      ["coin", "0% of your fee", "Your price, your money. The client pays the service fee for the secure deal (escrow).", false],
      ["lock", "Guaranteed payment", "The client's money is held in escrow until the stage is done. No more \"I'll transfer it tomorrow\".", true],
      ["document", "AI assistant", "Preparation of lawsuits and complaints, case summaries, procedural deadline tracking with reminders.", false],
      ["chart", "A reputation that can't be bought", "A rating based on proven results: cases won and money recovered, not reviews from friends.", false],
      ["users", "Your clients stay yours", "Manage your own clients on the platform too: CRM, deadlines, documents. No commission on clients you bring.", true],
    ] as [string, string, string, boolean][],
    faq: [
      ["How much does the platform charge lawyers?", "0% of your fee. The subscription for lawyers is paid from day one. Pro (unlimited responses, priority, AI tools, CRM) is 15,000–25,000 ₸/mo. We will announce the Basic plan price when payments go live and let you know in advance."],
      ["Who can join?", "Advocates, legal consultants who are chamber members, and human rights organizations. We check status against registries and identity via digital signature (EDS)."],
      ["What about attorney-client privilege and ethics?", "The client's personal data is hidden until a contract is signed: you see an anonymized case card. You sign the contract directly with the client; the platform is a technology intermediary."],
      ["Do human rights defenders pay too?", "No. For NGOs and pro bono work it is free forever, with reports on assistance for donors and grant makers."],
    ],
    calc: {
      title: "Do the math for yourself",
      cases: "New cases per month via the platform",
      fee: "Average fee per case",
      income: "extra income per month, no commission on your fee",
      hoursUnit: "h",
      hours: "saved on initial review (≈1.5 h per case)",
      note: "An illustrative estimate based on your inputs.",
    },
    dossier: {
      chip: "New case · Consumer protection",
      example: "example",
      title: "Refund of 180,000 ₸ for an undelivered sofa (marketplace)",
      rows: [["City", "Almaty"], ["Amount claimed", "180,000 ₸"], ["Payment date", "15.08.2026"], ["Evidence", "receipt, order screenshot, correspondence"], ["Already done", "claim sent to the seller on 01.09"], ["Seller's reply", "refusal (deadline passed)"]],
      hidden: "The client's name and contacts will be revealed after the contract is signed.",
      respond: "Respond: my price",
      ask: "Ask the client a question",
    },
    card: {
      sample: "sample card",
      partner: "platform partner",
      spec: "Consumer protection · Almaty",
      score: "rating based on proven results",
      cases: "cases",
      recovered: "recovered",
      mln: "M",
      pending: "Konsiliér AI partner. A rating based on proven results will appear after the first completed cases.",
      footer: "konsilier.com · book a lawyer",
    },
    form: {
      title: "Become a Konsiliér AI partner",
      invited: "Invited by a colleague",
      name: "Full name",
      kind: "Who you are",
      kinds: [["advocate", "Advocate"], ["legal_consultant", "Legal consultant"], ["human_rights", "Human rights organization / NGO"], ["other", "Other"]],
      org: "Bar association / chamber / organization",
      license: "License / certificate number",
      city: "City",
      contact: "Phone, Telegram or email",
      specs: [["consumer", "Consumer protection"], ["credit_fraud", "Fraudulent loans"], ["debt_collectors", "Debt collectors and debts"], ["labor", "Employment disputes"], ["family", "Family matters"], ["business", "Business and receivables"]],
      expert: "I want to be a scenario expert: review laws, deadlines and templates in my specialty",
      message: "What matters to you in the platform? (optional)",
      busy: "Sending…",
      submit: "Apply",
      privacy: "We check your status against registries. We use your data only for verification and to contact you.",
      doneTitle: "Application received",
      doneText: "We will check your status and get in touch. Meanwhile, here is your personal link. Every colleague who joins through it moves you up in case matching, and 10 invites give you priority in early case matching and a badge on your profile.",
      copy: "Copy",
      share: "I'm joining Konsiliér AI, a platform where lawyers get ready cases with a case file, 0% commission on their fee and stage-by-stage payment. Apply through my link: ",
    },
    hero: {
      chip: "For advocates, lawyers and human rights defenders",
      title: "Clients come to you with a ready case. You practice law instead of chasing clients and doing paperwork.",
      sub: "AI gathers the facts, documents and timeline of the case before it reaches you. You choose cases in your specialty and set your own price. 0% of your fee.",
      apply: "Become a partner",
      rating: "What the rating looks like",
      perks: "Partners and scenario experts get a status on their profile and priority in case matching. The subscription is paid; 0% of your fee.",
    },
    painsTitle: "Sound familiar?",
    benefitsTitle: "What you get",
    soon: "soon",
    reputationTitle: "Your reputation is your asset",
    reputation: "A card with your rating based on proven results is your digital business card. Share it on Instagram, Telegram and LinkedIn: clients book with you directly, with no commission.",
    growthTitle: "Grow with the platform",
    growth: [
      ["handshake", "Invite a colleague", "Every colleague you invite moves you up in case matching. 10 invites: priority in early case matching and a profile badge."],
      ["send", "Case of the week", "AI prepares an anonymized post about your won case. Publish it in one click."],
      ["chart", "Top of the month", "Leaders in money recovered in each category and city, on our home page and social media."],
      ["receipt", "Your own clients, no commission", "Invite your clients with your personal link and manage them in the CRM: deadlines and documents, with no commission on your fee."],
    ],
    partner: {
      title: "The Konsiliér AI Partner program",
      intro: "The first 100 verified lawyers, advocates and human rights defenders who run the platform pilot with us. The status is earned by taking part, not by signing up.",
      doesTitle: "What a partner does",
      does: ["Passes status and identity verification.", "Takes on 3–5 cases from the platform per month.", "Follows the standards: clear price before work starts, stage deadlines, progress updates on the case card.", "Once a month gives feedback on documents and scenarios: what to fix and what is missing."],
      getsTitle: "What a partner gets",
      gets: ["\"Partner\" status on the profile and card.", "Priority in case matching during the pilot.", "A say in the product: scenarios and templates are built with partners' practice in mind."],
      lose: "If the terms are not met, the status is removed and the account stays on the Basic plan.",
    },
    expert: {
      title: "Scenario expert",
      chip: "Name on every verified scenario",
      intro: "Lawyers who are responsible for the platform's legal accuracy. Each scenario (for example, \"refund for goods\") is a ready sequence of documents, deadlines and recipients. The expert reviews it and signs it with their name.",
      doesTitle: "What an expert does",
      does: ["Reviews the laws, deadlines and recipients in scenarios for their specialty.", "Reviews document templates (claims, complaints, applications).", "Updates the scenario when the law changes.", "Reviews disputed cases using the methodology."],
      getsTitle: "What an expert gets",
      gets: ["\"Expert\" status and their name in every verified scenario: \"Scenario verified by: …\".", "First access to cases in their scenarios.", "Mentions in Konsiliér AI materials and social media."],
    },
    pricing: {
      pilot: "The subscription for lawyers is paid from day one. Subscription payment and stage-by-stage payment through a payment partner are being set up — we will tell you in advance.",
      title: "Plans",
      basic: "Basic",
      basicPrice: "price announced when payments go live",
      basicText: "Profile, status verification, responses to cases (monthly limit), rating.",
      proChip: "Priority in case matching",
      proText: "Unlimited responses, priority in matching, AI document preparation, deadline tracking, CRM for your own clients.",
      ngo: "Human rights defenders and NGOs",
      ngoPrice: "0 ₸ forever",
      ngoText: "Pro features for pro bono work and assistance reports for donors.",
    },
    faqTitle: "Questions",
  };

export default en;
