import type { LawyerText } from "./ru";

// Texts of /for-lawyers (Turkish).
const tr: LawyerText = {
    proPrice: "15 000–25 000 ₸/ay",
    pains: [
      ["Müvekkiller «beni kandırdılar» diyerek bir yığın ekran görüntüsüyle geliyor", "Hazır bir dosya alırsınız: olgular, tarihler, tutarlar, deliller, yazışmalar ve kronoloji; yapay zekâ bunları sizden önce topladı ve kontrol etti."],
      ["Reklam pahalı, tavsiye ile gelen iş öngörülemez", "Uzmanlık alanınıza ve şehrinize göre dosyalar kendiliğinden gelir. Hangilerine teklif vereceğinizi siz seçer, ücretinizi siz belirlersiniz."],
      ["Müvekkil ilk aşamadan sonra kayboldu ve ödeme yapmadı", "Bloke hesapla aşamalı ödeme: müvekkil tutarı önceden yatırır, siz aşama tamamlanır tamamlanmaz alırsınız."],
    ],
    benefits: [
      ["briefcase", "Hazır dosyalar", "İlk görüşme yerine dosya özeti: her müvekkilde 1–2 saat tasarruf.", false],
      ["coin", "Ücretinizden %0", "Ücretiniz sizindir. Hizmet bedelini güvenli işlem için müvekkil öder.", false],
      ["lock", "Ödeme güvencesi", "Müvekkilin parası aşama tamamlanana kadar bloke. «Yarın gönderirim» yok.", true],
      ["document", "Yapay zekâ asistanı", "Dava dilekçesi ve şikâyet hazırlama, dosya özeti, hatırlatmalı usul süresi takibi.", false],
      ["chart", "Satın alınamayan itibar", "Kanıtlanmış sonuçlara dayalı puan: arkadaş yorumları değil, kazanılan dosyalar ve geri alınan para.", false],
      ["users", "Müvekkilleriniz sizindir", "Kendi müvekkillerinizi de platformda yönetin: CRM, süreler, belgeler. Getirdiğiniz müvekkillerde komisyon yok.", true],
    ] as [string, string, string, boolean][],
    faq: [
      ["Platform avukattan ne kadar alıyor?", "Ücretten %0. Avukatlar için abonelik ilk günden itibaren ücretlidir. Pro (sınırsız teklif, öncelik, yapay zekâ araçları, CRM): 15 000–25 000 ₸/ay. Temel paketin fiyatını ödeme sistemi devreye girdiğinde açıklayacağız; önceden haber vereceğiz."],
      ["Kimler katılabilir?", "Avukatlar, odaya üye hukuk danışmanları, insan hakları kuruluşları. Statüyü sicillerden, kimliği e-imza ile doğruluyoruz."],
      ["Avukat-müvekkil gizliliği ve meslek etiği ne olacak?", "Müvekkilin kişisel verileri sözleşme yapılana kadar gizlidir: anonimleştirilmiş dosya kartını görürsünüz. Sözleşmeyi müvekkille doğrudan siz yaparsınız, platform teknolojik aracıdır."],
      ["İnsan hakları savunucuları da ödeyecek mi?", "Hayır. STK'lar ve pro bono için süresiz ücretsiz; bağışçılar ve hibe verenler için yardım raporlarıyla."],
    ],
    calc: {
      title: "Kendiniz için hesaplayın",
      cases: "Platformdan aylık yeni dosya sayısı",
      fee: "Dosya başına ortalama ücret",
      income: "ayda ek gelir, ücretten komisyon olmadan",
      hoursUnit: "sa",
      hours: "ilk incelemede tasarruf edilen süre (dosya başına ≈1,5 sa)",
      note: "Girdiğiniz verilere göre örnek hesap.",
    },
    dossier: {
      chip: "Yeni dosya · Tüketici hakları",
      example: "örnek",
      title: "Teslim edilmeyen kanepe için 180 000 ₸ iadesi (pazaryeri)",
      rows: [["Şehir", "Almatı"], ["Talep tutarı", "180 000 ₸"], ["Ödeme tarihi", "15.08.2026"], ["Deliller", "fiş, sipariş ekran görüntüsü, yazışma"], ["Yapılanlar", "satıcıya ihtarname 01.09'da gönderildi"], ["Satıcının cevabı", "ret (süre doldu)"]],
      hidden: "Müvekkilin adı soyadı ve iletişim bilgileri sözleşmeden sonra açılır.",
      respond: "Teklif ver: ücretim",
      ask: "Müvekkile soru sor",
    },
    card: {
      sample: "örnek kart",
      partner: "platform ortağı",
      spec: "Tüketici hakları · Almatı",
      score: "kanıtlanmış sonuçlara dayalı puan",
      cases: "dosya",
      recovered: "geri alındı",
      mln: "mn",
      pending: "Konsiliér AI ortağı. Kanıtlanmış sonuçlara dayalı puan, ilk dosyalar tamamlandıktan sonra görünecek.",
      footer: "konsilier.com · avukattan randevu",
    },
    form: {
      title: "Konsiliér AI ortağı olun",
      invited: "Sizi bir meslektaşınız davet etti",
      name: "Ad soyad",
      kind: "Mesleğiniz",
      kinds: [["advocate", "Avukat"], ["legal_consultant", "Hukuk danışmanı"], ["human_rights", "İnsan hakları kuruluşu / STK"]],
      org: "Baro / oda / kuruluş",
      license: "Ruhsat / meslek kimliği numarası",
      city: "Şehir",
      kindPick: "Statünüzü seçin",
      phone: "Cep telefonu",
      phoneHint: "Kazakistan numarası: +7 7XX XXX XX XX",
      email: "E-posta (isteğe bağlı)",
      licenseAdvocate: "Avukatlık ruhsatı numarası",
      licenseConsultant: "Hukuk danışmanları odası üyelik belgesi numarası",
      licenseOptional: "Kayıt veya belge numarası (isteğe bağlı)",
      consent: "Statümün doğrulanması ve benimle iletişim kurulması için kişisel verilerimin işlenmesine, doğrulamadan sonra da profilimin (ad soyad, statü, kuruluş, şehir, uzmanlık alanları) avukat dizininde yayımlanmasına onay veriyorum. Telefon ve e-posta yayımlanmaz.",
      linked: "E-imzanız, bu numarayla daha önce yapılan başvuruya bağlandı. Başvuru doğrulamaya gönderildi.",
      specs: [["consumer", "Tüketici hakları"], ["credit_fraud", "Dolandırıcılıkla çekilen krediler"], ["debt_collectors", "Tahsilatçılar ve borçlar"], ["labor", "İş uyuşmazlıkları"], ["family", "Aile hukuku"], ["business", "Ticaret ve alacaklar"]],
      expert: "Senaryo uzmanı olmak istiyorum: kendi alanımda mevzuat, süre ve şablonları kontrol etmek",
      message: "Platformda sizin için ne önemli? (isteğe bağlı)",
      busy: "Gönderiliyor…",
      submit: "Başvur",
      privacy: "Statüyü sicillerden kontrol ederiz. Verileri yalnızca doğrulama ve sizinle iletişim için kullanırız.",
      doneTitle: "Başvurunuz alındı",
      doneText: "Statünüzü kontrol edip sizinle iletişime geçeceğiz. Bu arada kişisel bağlantınız burada. Bu bağlantıyla katılan her meslektaş sizi dosya dağıtımında öne çıkarır; 10 davetle erken dosya dağıtımında öncelik ve profilinizde bir rozet kazanırsınız.",
      copy: "Kopyala",
      share: "Konsiliér AI'ya katılıyorum: avukatların dosya özetiyle hazır dosyalar aldığı, ücretten %0 komisyon ve aşamalı ödeme sunan platform. Bağlantım üzerinden başvurun: ",
    },
    hero: {
      chip: "Avukatlar, hukukçular ve insan hakları savunucuları için",
      title: "Müvekkiller size hazır dosyayla gelir. Siz hukukla ilgilenirsiniz, müvekkil aramak ve evrak işiyle değil.",
      sub: "Yapay zekâ dosyanın olgularını, belgelerini ve kronolojisini size gelmeden önce toplar. Uzmanlık alanınızdaki dosyaları siz seçer, ücreti siz belirlersiniz. Ücretinizden %0 kesinti.",
      apply: "Ortak olun",
      rating: "Puan nasıl görünür",
      perks: "Ortaklara ve senaryo uzmanlarına: profilde statü ve dosya dağıtımında öncelik. Abonelik ücretlidir, ücretten %0.",
    },
    painsTitle: "Tanıdık geliyor mu?",
    benefitsTitle: "Neler kazanırsınız",
    soon: "yakında",
    reputationTitle: "İtibarınız sizin sermayeniz",
    reputation: "Kanıtlanmış sonuçlara dayalı puanlı kart, dijital kartvizitinizdir. Instagram, Telegram ve LinkedIn'de paylaşın: müvekkiller size doğrudan, komisyonsuz randevu alır.",
    growthTitle: "Platformla birlikte büyüyün",
    growth: [
      ["handshake", "Meslektaşınızı davet edin", "Davet ettiğiniz her meslektaş sizi dosya dağıtımında öne çıkarır. 10 davetli: erken dosya dağıtımında öncelik ve profilde rozet."],
      ["send", "Haftanın dosyası", "Yapay zekâ kazandığınız dosya hakkında anonim bir paylaşım hazırlar; tek tıkla yayınlayın."],
      ["chart", "Ayın en iyileri", "Her kategori ve şehirde en çok iade sağlayanlar ana sayfada ve sosyal medya hesaplarımızda."],
      ["receipt", "Kendi müvekkilleriniz: komisyonsuz", "Müvekkillerinizi kişisel bağlantıyla davet edin ve CRM'de yönetin: süreler ve belgeler, ücretinizden komisyon olmadan."],
    ],
    partner: {
      title: "«Konsiliér AI Ortağı» programı",
      intro: "Platformun pilot sürecini bizimle birlikte yürüten ilk 100 doğrulanmış hukukçu, avukat ve insan hakları savunucusu. Statü kayıtla değil, katılımla kazanılır.",
      doesTitle: "Ortak ne yapar",
      does: ["Statü ve kimlik doğrulamasından geçer.", "Platformdan ayda 3–5 dosya üstlenir.", "Standartlara uyar: iş başlamadan şeffaf ücret, aşama süreleri, kartta dosyanın seyrine dair notlar.", "Ayda bir belgeler ve senaryolar hakkında geri bildirim verir: neyin düzeltilmesi, neyin eksik olduğu."],
      getsTitle: "Ortak ne kazanır",
      gets: ["Profilde ve kartta «Ortak» statüsü.", "Pilot dönemde dosya dağıtımında öncelik.", "Ürüne etki: senaryolar ve şablonlar ortakların uygulamasına göre oluşturulur."],
      lose: "Katılım koşulları yerine getirilmezse statü kaldırılır, hesap temel pakette kalır.",
    },
    expert: {
      title: "Senaryo uzmanı",
      chip: "Doğrulanan her senaryoda adı",
      intro: "Platformun hukuki doğruluğundan sorumlu hukukçular. Her senaryo (örneğin «ürün için para iadesi») belgeler, süreler ve muhataplardan oluşan hazır bir dizidir. Uzman onu kontrol eder ve kendi adıyla onaylar.",
      doesTitle: "Uzman ne yapar",
      does: ["Kendi alanındaki senaryoda mevzuatı, süreleri ve muhatapları kontrol eder.", "Belge şablonlarını kontrol eder (ihtarnameler, şikâyetler, dilekçeler).", "Mevzuat değiştiğinde senaryoyu günceller.", "Tartışmalı durumları metodolojiye göre inceler."],
      getsTitle: "Uzman ne kazanır",
      gets: ["«Uzman» statüsü ve her doğrulanmış senaryoda adı: «Senaryoyu kontrol eden: …».", "Kendi senaryolarındaki dosyaları ilk o alır.", "Konsiliér AI materyallerinde ve sosyal medyasında anılma."],
    },
    pricing: {
      pilot: "Avukatlar için abonelik ilk günden itibaren ücretlidir. Abonelik ödemesi ve ödeme ortağı üzerinden aşamalı ödeme devreye alınıyor; önceden haber vereceğiz.",
      title: "Paketler",
      basic: "Temel",
      basicPrice: "fiyat, ödeme devreye girince açıklanacak",
      basicText: "Profil, statü doğrulaması, dosyalara teklif verme (aylık sınırlı), puan.",
      proChip: "Dosya dağıtımında öncelik",
      proText: "Sınırsız teklif, dağıtımda öncelik, yapay zekâ ile belge hazırlama, süre takibi, kendi müvekkilleriniz için CRM.",
      ngo: "İnsan hakları savunucuları ve STK'lar için",
      ngoPrice: "0 ₸, süresiz",
      ngoText: "Pro bono için Pro özellikleri ve bağışçılara yardım raporları.",
    },
    faqTitle: "Sorular",
  };

export default tr;
