import type { LawyerText } from "./ru";

// Texts of /for-lawyers (Turkish).
const tr: LawyerText = {
    proPrice: "15 000–25 000 ₸/ay",
    pains: [
      ["Müvekkiller «dolandırıldım» diyerek bir yığın ekran görüntüsüyle geliyor", "Hazır bir dosya alırsınız: olgular, tarihler, tutarlar, deliller, yazışmalar ve kronoloji; yapay zekâ bunları sizden önce topladı ve kontrol etti."],
      ["Reklam pahalı, tavsiye ile gelen iş öngörülemez", "Uzmanlık alanınıza ve şehrinize göre dosyalar kendiliğinden gelir. Hangisine başvuracağınızı siz seçer, ücretinizi siz belirlersiniz."],
      ["Müvekkil ilk aşamadan sonra kayboldu ve ödeme yapmadı", "Bloke hesapla aşamalı ödeme: müvekkil tutarı önceden yatırır, siz aşama tamamlanır tamamlanmaz alırsınız."],
    ],
    benefits: [
      ["briefcase", "Hazır dosyalar", "İlk görüşme yerine dosya özeti: her müvekkilde 1–2 saat tasarruf.", false],
      ["coin", "Ücretinizden %0", "Ücretiniz sizindir. Hizmet bedelini güvenli işlem için müvekkil öder.", false],
      ["lock", "Ödeme güvencesi", "Müvekkilin parası aşama tamamlanana kadar bloke. «Yarın gönderirim» yok.", true],
      ["document", "Yapay zekâ asistanı", "Dava dilekçesi ve şikâyet taslakları, dosya özeti, hatırlatmalı usul süresi takibi.", false],
      ["chart", "Satın alınamayan itibar", "Kanıtlanmış sonuçlara dayalı puan: arkadaş yorumları değil, kazanılan dosyalar ve geri alınan para.", false],
      ["users", "Müvekkilleriniz sizindir", "Kendi müvekkillerinizi de platformda yönetin: CRM, süreler, belgeler. Getirdiğiniz müvekkillerde komisyon yok.", false],
    ] as [string, string, string, boolean][],
    faq: [
      ["Platform avukattan ne kadar alıyor?", "Ücretten %0. Temel paket ücretsiz. Pro (sınırsız başvuru, öncelik, yapay zekâ araçları, CRM): 15 000–25 000 ₸/ay. Konsiliér AI ortaklarına Pro 6 ay, senaryo uzmanlarına 12 ay ücretsiz."],
      ["Kimler katılabilir?", "Avukatlar, odaya üye hukuk danışmanları, insan hakları kuruluşları. Statüyü sicillerden, kimliği e-imza ile doğruluyoruz."],
      ["Avukat-müvekkil gizliliği ve meslek etiği ne olacak?", "Müvekkilin kişisel verileri sözleşme yapılana kadar gizlidir: anonimleştirilmiş dosya kartını görürsünüz. Sözleşmeyi müvekkille doğrudan siz yaparsınız, platform teknolojik aracıdır."],
      ["İnsan hakları savunucuları da ödeyecek mi?", "Hayır. STK'lar ve pro bono için sonsuza kadar ücretsiz; bağışçılar ve hibe verenler için yardım raporlarıyla."],
    ],
    calc: {
      title: "Kendiniz için hesaplayın",
      cases: "Platformdan ayda yeni dosya",
      fee: "Dosya başına ortalama ücret",
      income: "ayda ek gelir, ücretten komisyon olmadan",
      hoursUnit: "sa",
      hours: "ilk incelemede tasarruf (dosya başına ≈1,5 sa)",
      note: "Girdiğiniz verilere göre örnek hesap.",
    },
    dossier: {
      chip: "Yeni dosya · Tüketici hakları",
      example: "örnek",
      title: "Teslim edilmeyen kanepe için 180 000 ₸ iadesi (pazaryeri)",
      rows: [["Şehir", "Almatı"], ["Talep tutarı", "180 000 ₸"], ["Ödeme tarihi", "15.08.2026"], ["Deliller", "fiş, sipariş ekran görüntüsü, yazışma"], ["Yapılanlar", "satıcıya ihtarname 01.09'da gönderildi"], ["Satıcının cevabı", "ret (süre doldu)"]],
      hidden: "Müvekkilin adı soyadı ve iletişim bilgileri sözleşmeden sonra açılır.",
      respond: "Başvur: ücretim",
      ask: "Müvekkile soru sor",
    },
    card: {
      sample: "örnek kart",
      partner: "platform ortağı",
      spec: "Tüketici hakları · Almatı",
      score: "kanıtlanmış sonuçlara dayalı puan",
      cases: "dosya",
      recovered: "geri alındı",
      mln: "mn",
      pending: "Konsiliér AI ortağı. Kanıtlanmış sonuçlara dayalı puan, ilk dosyalar tamamlandıktan sonra görünecek.",
      footer: "konsilier.com · avukattan randevu",
    },
    form: {
      title: "Konsiliér AI ortağı olun",
      invited: "Sizi bir meslektaşınız davet etti · +3 ay Pro",
      name: "Ad soyad",
      kind: "Mesleğiniz",
      kinds: [["advocate", "Avukat"], ["legal_consultant", "Hukuk danışmanı"], ["human_rights", "İnsan hakları kuruluşu / STK"], ["other", "Diğer"]],
      org: "Baro / oda / kuruluş",
      license: "Ruhsat / kimlik kartı numarası",
      city: "Şehir",
      contact: "Telefon, Telegram veya e-posta",
      specs: [["consumer", "Tüketici hakları"], ["credit_fraud", "Dolandırıcılıkla çekilen krediler"], ["debt_collectors", "Tahsilatçılar ve borçlar"], ["labor", "İş uyuşmazlıkları"], ["family", "Aile hukuku"], ["business", "Ticaret ve alacaklar"]],
      expert: "Senaryo uzmanı olmak istiyorum: kendi alanımda mevzuat, süre ve şablonları kontrol etmek (12 ay Pro)",
      message: "Platformda sizin için ne önemli? (isteğe bağlı)",
      busy: "Gönderiliyor…",
      submit: "Başvur",
      privacy: "Statüyü sicillerden kontrol ederiz. Verileri yalnızca doğrulama ve sizinle iletişim için kullanırız.",
      doneTitle: "Başvurunuz alındı",
      doneText: "Statünüzü kontrol edip sizinle iletişime geçeceğiz. Bu arada kişisel bağlantınız burada. Bu bağlantıyla katılan her meslektaş hem size hem kendisine +3 ay Pro kazandırır; ilk 10 davetli sizi erken dosya dağıtımında öne çıkarır.",
      copy: "Kopyala",
      share: "Konsiliér AI'ya katılıyorum: avukatların dosya özetiyle hazır dosyalar aldığı, ücretten %0 komisyon ve aşamalı ödeme sunan platform. «Konsiliér AI Ortağı» programı: 6 ay ücretsiz Pro. ",
    },
    hero: {
      chip: "Avukatlar, hukukçular ve insan hakları savunucuları için",
      title: "Müvekkiller size hazır dosyayla gelir. Siz hukukla ilgilenirsiniz, müvekkil aramak ve evrak işiyle değil.",
      sub: "Yapay zekâ olguları ve delilleri toplar, platform aşamalı ödemeyi güvenceye alır, puanınız gerçekten kazanılan dosyalara dayanır. Ücretinizden %0.",
      apply: "Ortak olun, ücretsiz",
      rating: "Puan nasıl görünür",
      perks: "Ortaklara 6 ay, senaryo uzmanlarına 12 ay ücretsiz Pro.",
    },
    painsTitle: "Tanıdık geliyor mu?",
    benefitsTitle: "Neler kazanırsınız",
    soon: "yakında",
    reputationTitle: "İtibarınız sizin sermayeniz",
    reputation: "Kanıtlanmış sonuçlara dayalı puanlı kart, dijital kartvizitinizdir. Instagram, Telegram ve LinkedIn'de paylaşın: müvekkiller size doğrudan, komisyonsuz randevu alır.",
    growthTitle: "Platformla birlikte büyüyün",
    growth: [
      ["handshake", "Meslektaşınızı davet edin", "Size ve ona +3 ay Pro. 10 davetli: dosya dağıtımında öncelik."],
      ["send", "Haftanın dosyası", "Yapay zekâ kazandığınız dosya hakkında anonim bir paylaşım hazırlar; tek tıkla yayınlayın."],
      ["chart", "Ayın en iyileri", "Her kategori ve şehirde en çok iade sağlayanlar ana sayfada ve sosyal medya hesaplarımızda."],
      ["receipt", "Kendi müvekkilleriniz: komisyonsuz", "Müvekkillerinizi kişisel bağlantıyla davet edin: CRM, süreler ve belgeler ücretsiz."],
    ],
    partner: {
      title: "«Konsiliér AI Ortağı» programı",
      intro: "Platformun pilot sürecini bizimle birlikte yürüten ilk 100 doğrulanmış hukukçu, avukat ve insan hakları savunucusu. Statü kayıtla değil, katılımla kazanılır.",
      doesTitle: "Ortak ne yapar",
      does: ["Statü ve kimlik doğrulamasından geçer.", "Platformdan ayda 3–5 dosya üstlenir.", "Standartlara uyar: iş başlamadan şeffaf ücret, aşama süreleri, kartta dosyanın seyrine dair notlar.", "Ayda bir belgeler ve senaryolar hakkında geri bildirim verir: neyin düzeltilmesi, neyin eksik olduğu."],
      getsTitle: "Ortak ne kazanır",
      gets: ["6 ay ücretsiz Pro.", "Profilde ve kartta «Ortak» statüsü.", "Pilot dönemde dosya dağıtımında öncelik.", "Ürüne etki: senaryolar ve şablonlar ortakların uygulamasına göre oluşturulur."],
      lose: "Katılım koşulları yerine getirilmezse statü kaldırılır, hesap temel pakette kalır.",
    },
    expert: {
      title: "Senaryo uzmanı",
      chip: "12 ay ücretsiz Pro",
      intro: "Platformun hukuki doğruluğundan sorumlu hukukçular. Her senaryo (örneğin «ürün için para iadesi») belgeler, süreler ve muhataplardan oluşan hazır bir dizidir. Uzman onu kontrol eder ve kendi adıyla onaylar.",
      doesTitle: "Uzman ne yapar",
      does: ["Kendi alanındaki senaryoda mevzuatı, süreleri ve muhatapları kontrol eder.", "Belge şablonlarını kontrol eder (ihtarnameler, şikâyetler, dilekçeler).", "Mevzuat değiştiğinde senaryoyu günceller.", "Tartışmalı durumları metodolojiye göre inceler."],
      getsTitle: "Uzman ne kazanır",
      gets: ["12 ay ücretsiz Pro.", "«Uzman» statüsü ve her doğrulanmış senaryoda adı: «Senaryoyu kontrol eden: …».", "Kendi senaryolarındaki dosyaları ilk o alır.", "Konsiliér AI materyallerinde ve sosyal medyasında anılma."],
    },
    pricing: {
      title: "Paketler",
      basic: "Temel",
      basicText: "Profil, statü doğrulaması, dosyalara başvuru (aylık sınırlı), puan.",
      proChip: "Ortaklara 6 ay, uzmanlara 12 ay ücretsiz",
      proText: "Sınırsız başvuru, dağıtımda öncelik, yapay zekâ taslakları, süre takibi, kendi müvekkilleriniz için CRM.",
      ngo: "İnsan hakları savunucuları ve STK'lar için",
      ngoPrice: "0 ₸, süresiz",
      ngoText: "Pro bono için Pro özellikleri ve bağışçılara yardım raporları.",
    },
    faqTitle: "Sorular",
  };

export default tr;
