"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 08:03:27.208382
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('registration_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_token', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=False)

    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_country'), ['country'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=2), nullable=True),
    sa.Column('ontology_code', sa.String(length=64), nullable=True),
    sa.Column('scenario_id', sa.String(length=128), nullable=True),
    sa.Column('scenario_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('qualification_confidence', sa.Double(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('amount_at_stake', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('skipped_fields', sa.JSON(), nullable=False),
    sa.Column('pending_field', sa.String(length=64), nullable=True),
    sa.Column('initial_text', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('pii_map', sa.JSON(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_jurisdiction'), ['jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('submitted_via', sa.String(length=32), nullable=True),
    sa.Column('addressee', sa.JSON(), nullable=False),
    sa.Column('docx_key', sa.String(length=300), nullable=True),
    sa.Column('pdf_key', sa.String(length=300), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('is_draft_scenario', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_class', sa.String(length=16), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_case_id'), ['case_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('norm_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_case_id'), ['case_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('extracted_facts', sa.JSON(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('days_to_resolution', sa.Integer(), nullable=False),
    sa.Column('resolved_at_step', sa.String(length=64), nullable=True),
    sa.Column('scenario_id', sa.String(length=128), nullable=True),
    sa.Column('scenario_version', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_case_id'), ['case_id'], unique=False)

    op.create_table('deadlines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('norm_ref', sa.String(length=200), nullable=True),
    sa.Column('remind_before_days', sa.JSON(), nullable=False),
    sa.Column('reminders_sent', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadlines_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadlines_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadlines_status'))
        batch_op.drop_index(batch_op.f('ix_deadlines_due_date'))
        batch_op.drop_index(batch_op.f('ix_deadlines_case_id'))
        batch_op.drop_index(batch_op.f('ix_deadlines_action_id'))

    op.drop_table('deadlines')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_case_id'))

    op.drop_table('parties')
    op.drop_table('outcomes')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_case_id'))

    op.drop_table('claims')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_case_id'))
        batch_op.drop_index(batch_op.f('ix_actions_approval_status'))

    op.drop_table('actions')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_cases_owner_id'))
        batch_op.drop_index(batch_op.f('ix_cases_needs_review'))
        batch_op.drop_index(batch_op.f('ix_cases_jurisdiction'))

    op.drop_table('cases')
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_country'))

    op.drop_table('waitlist')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_id'))
        batch_op.drop_index(batch_op.f('ix_users_api_token'))

    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
