"""lawyer applications

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 11:34:18.207517
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('organization', sa.String(length=300), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawyer_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawyer_applications_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_lawyer_applications_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lawyer_applications_referred_by'), ['referred_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyer_applications_referred_by'))
        batch_op.drop_index(batch_op.f('ix_lawyer_applications_referral_code'))
        batch_op.drop_index(batch_op.f('ix_lawyer_applications_country'))

    op.drop_table('lawyer_applications')
    # ### end Alembic commands ###
