"""lawyer application expert flag

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 11:55:18.815997
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_expert', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_applications', schema=None) as batch_op:
        batch_op.drop_column('wants_expert')

    # ### end Alembic commands ###
